/*
 * generated by Xtext 2.9.2
 */
package ch.raiffeisen.ipricer.definition.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DefinitionDSLGrammarAccess extends AbstractGrammarElementFinder {
	
	public class DefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.Definition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDefinitionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMethodNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMethodNameIDTerminalRuleCall_1_0 = (RuleCall)cMethodNameAssignment_1.eContents().get(0);
		private final Assignment cGuiLabelMethodAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cGuiLabelMethodSTRINGTerminalRuleCall_2_0 = (RuleCall)cGuiLabelMethodAssignment_2.eContents().get(0);
		private final Assignment cGuiLabelParentAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cGuiLabelParentSTRINGTerminalRuleCall_3_0 = (RuleCall)cGuiLabelParentAssignment_3.eContents().get(0);
		private final Assignment cGuiLabelChildAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cGuiLabelChildSTRINGTerminalRuleCall_4_0 = (RuleCall)cGuiLabelChildAssignment_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cDataAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cDataDataParserRuleCall_6_0 = (RuleCall)cDataAssignment_6.eContents().get(0);
		private final Assignment cInitSectionAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cInitSectionInitSectionParserRuleCall_7_0 = (RuleCall)cInitSectionAssignment_7.eContents().get(0);
		private final Assignment cTypeMaskSectionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cTypeMaskSectionTypeMaskSectionParserRuleCall_8_0 = (RuleCall)cTypeMaskSectionAssignment_8.eContents().get(0);
		private final Assignment cUnderlyingListSectionAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cUnderlyingListSectionUnderlyingListSectionParserRuleCall_9_0 = (RuleCall)cUnderlyingListSectionAssignment_9.eContents().get(0);
		private final Assignment cUnderlyingMaskSectionAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cUnderlyingMaskSectionUnderlyingMaskSectionParserRuleCall_10_0 = (RuleCall)cUnderlyingMaskSectionAssignment_10.eContents().get(0);
		private final Assignment cOptionListSectionAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cOptionListSectionOptionListSectionParserRuleCall_11_0 = (RuleCall)cOptionListSectionAssignment_11.eContents().get(0);
		private final Assignment cOptionListLabelSectionAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cOptionListLabelSectionOptionListLabelSectionParserRuleCall_12_0 = (RuleCall)cOptionListLabelSectionAssignment_12.eContents().get(0);
		private final Assignment cOptionMaskSectionAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cOptionMaskSectionOptionMaskSectionParserRuleCall_13_0 = (RuleCall)cOptionMaskSectionAssignment_13.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Assignment cEventuellTclProceduresAssignment_15 = (Assignment)cGroup.eContents().get(15);
		private final Alternatives cEventuellTclProceduresAlternatives_15_0 = (Alternatives)cEventuellTclProceduresAssignment_15.eContents().get(0);
		private final RuleCall cEventuellTclProceduresIDTerminalRuleCall_15_0_0 = (RuleCall)cEventuellTclProceduresAlternatives_15_0.eContents().get(0);
		private final RuleCall cEventuellTclProceduresANY_OTHERTerminalRuleCall_15_0_1 = (RuleCall)cEventuellTclProceduresAlternatives_15_0.eContents().get(1);
		
		//Definition:
		//	'Definition' methodName=ID guiLabelMethod=STRING guiLabelParent=STRING guiLabelChild=STRING '{'
		//	data=Data
		//	initSection=InitSection
		//	typeMaskSection=TypeMaskSection
		//	underlyingListSection=UnderlyingListSection
		//	underlyingMaskSection=UnderlyingMaskSection
		//	optionListSection=OptionListSection
		//	optionListLabelSection=OptionListLabelSection
		//	optionMaskSection=OptionMaskSection
		//	'}'
		//	eventuellTclProcedures+=(ID | ANY_OTHER)*;
		@Override public ParserRule getRule() { return rule; }
		
		//'Definition' methodName=ID guiLabelMethod=STRING guiLabelParent=STRING guiLabelChild=STRING '{' data=Data
		//initSection=InitSection typeMaskSection=TypeMaskSection underlyingListSection=UnderlyingListSection
		//underlyingMaskSection=UnderlyingMaskSection optionListSection=OptionListSection
		//optionListLabelSection=OptionListLabelSection optionMaskSection=OptionMaskSection '}' eventuellTclProcedures+=(ID |
		//ANY_OTHER)*
		public Group getGroup() { return cGroup; }
		
		//'Definition'
		public Keyword getDefinitionKeyword_0() { return cDefinitionKeyword_0; }
		
		//methodName=ID
		public Assignment getMethodNameAssignment_1() { return cMethodNameAssignment_1; }
		
		//ID
		public RuleCall getMethodNameIDTerminalRuleCall_1_0() { return cMethodNameIDTerminalRuleCall_1_0; }
		
		//guiLabelMethod=STRING
		public Assignment getGuiLabelMethodAssignment_2() { return cGuiLabelMethodAssignment_2; }
		
		//STRING
		public RuleCall getGuiLabelMethodSTRINGTerminalRuleCall_2_0() { return cGuiLabelMethodSTRINGTerminalRuleCall_2_0; }
		
		//guiLabelParent=STRING
		public Assignment getGuiLabelParentAssignment_3() { return cGuiLabelParentAssignment_3; }
		
		//STRING
		public RuleCall getGuiLabelParentSTRINGTerminalRuleCall_3_0() { return cGuiLabelParentSTRINGTerminalRuleCall_3_0; }
		
		//guiLabelChild=STRING
		public Assignment getGuiLabelChildAssignment_4() { return cGuiLabelChildAssignment_4; }
		
		//STRING
		public RuleCall getGuiLabelChildSTRINGTerminalRuleCall_4_0() { return cGuiLabelChildSTRINGTerminalRuleCall_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//data=Data
		public Assignment getDataAssignment_6() { return cDataAssignment_6; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_6_0() { return cDataDataParserRuleCall_6_0; }
		
		//initSection=InitSection
		public Assignment getInitSectionAssignment_7() { return cInitSectionAssignment_7; }
		
		//InitSection
		public RuleCall getInitSectionInitSectionParserRuleCall_7_0() { return cInitSectionInitSectionParserRuleCall_7_0; }
		
		//typeMaskSection=TypeMaskSection
		public Assignment getTypeMaskSectionAssignment_8() { return cTypeMaskSectionAssignment_8; }
		
		//TypeMaskSection
		public RuleCall getTypeMaskSectionTypeMaskSectionParserRuleCall_8_0() { return cTypeMaskSectionTypeMaskSectionParserRuleCall_8_0; }
		
		//underlyingListSection=UnderlyingListSection
		public Assignment getUnderlyingListSectionAssignment_9() { return cUnderlyingListSectionAssignment_9; }
		
		//UnderlyingListSection
		public RuleCall getUnderlyingListSectionUnderlyingListSectionParserRuleCall_9_0() { return cUnderlyingListSectionUnderlyingListSectionParserRuleCall_9_0; }
		
		//underlyingMaskSection=UnderlyingMaskSection
		public Assignment getUnderlyingMaskSectionAssignment_10() { return cUnderlyingMaskSectionAssignment_10; }
		
		//UnderlyingMaskSection
		public RuleCall getUnderlyingMaskSectionUnderlyingMaskSectionParserRuleCall_10_0() { return cUnderlyingMaskSectionUnderlyingMaskSectionParserRuleCall_10_0; }
		
		//optionListSection=OptionListSection
		public Assignment getOptionListSectionAssignment_11() { return cOptionListSectionAssignment_11; }
		
		//OptionListSection
		public RuleCall getOptionListSectionOptionListSectionParserRuleCall_11_0() { return cOptionListSectionOptionListSectionParserRuleCall_11_0; }
		
		//optionListLabelSection=OptionListLabelSection
		public Assignment getOptionListLabelSectionAssignment_12() { return cOptionListLabelSectionAssignment_12; }
		
		//OptionListLabelSection
		public RuleCall getOptionListLabelSectionOptionListLabelSectionParserRuleCall_12_0() { return cOptionListLabelSectionOptionListLabelSectionParserRuleCall_12_0; }
		
		//optionMaskSection=OptionMaskSection
		public Assignment getOptionMaskSectionAssignment_13() { return cOptionMaskSectionAssignment_13; }
		
		//OptionMaskSection
		public RuleCall getOptionMaskSectionOptionMaskSectionParserRuleCall_13_0() { return cOptionMaskSectionOptionMaskSectionParserRuleCall_13_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
		
		//eventuellTclProcedures+=(ID | ANY_OTHER)*
		public Assignment getEventuellTclProceduresAssignment_15() { return cEventuellTclProceduresAssignment_15; }
		
		//(ID | ANY_OTHER)
		public Alternatives getEventuellTclProceduresAlternatives_15_0() { return cEventuellTclProceduresAlternatives_15_0; }
		
		//ID
		public RuleCall getEventuellTclProceduresIDTerminalRuleCall_15_0_0() { return cEventuellTclProceduresIDTerminalRuleCall_15_0_0; }
		
		//ANY_OTHER
		public RuleCall getEventuellTclProceduresANY_OTHERTerminalRuleCall_15_0_1() { return cEventuellTclProceduresANY_OTHERTerminalRuleCall_15_0_1; }
	}
	public class DataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.Data");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDataKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final RuleCall cDEF_COMMENTTerminalRuleCall_2_0 = (RuleCall)cAlternatives_2.eContents().get(0);
		private final Assignment cFieldDefinitionsAssignment_2_1 = (Assignment)cAlternatives_2.eContents().get(1);
		private final RuleCall cFieldDefinitionsFieldDefinitionParserRuleCall_2_1_0 = (RuleCall)cFieldDefinitionsAssignment_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Data:
		//	'Data' '{' (DEF_COMMENT | fieldDefinitions+=FieldDefinition)+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Data' '{' (DEF_COMMENT | fieldDefinitions+=FieldDefinition)+ '}'
		public Group getGroup() { return cGroup; }
		
		//'Data'
		public Keyword getDataKeyword_0() { return cDataKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//(DEF_COMMENT | fieldDefinitions+=FieldDefinition)+
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//DEF_COMMENT
		public RuleCall getDEF_COMMENTTerminalRuleCall_2_0() { return cDEF_COMMENTTerminalRuleCall_2_0; }
		
		//fieldDefinitions+=FieldDefinition
		public Assignment getFieldDefinitionsAssignment_2_1() { return cFieldDefinitionsAssignment_2_1; }
		
		//FieldDefinition
		public RuleCall getFieldDefinitionsFieldDefinitionParserRuleCall_2_1_0() { return cFieldDefinitionsFieldDefinitionParserRuleCall_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class InitSectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.InitSection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInitKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final RuleCall cDEF_COMMENTTerminalRuleCall_2_0 = (RuleCall)cAlternatives_2.eContents().get(0);
		private final Assignment cInitDefinitionsAssignment_2_1 = (Assignment)cAlternatives_2.eContents().get(1);
		private final RuleCall cInitDefinitionsInitDefinitionParserRuleCall_2_1_0 = (RuleCall)cInitDefinitionsAssignment_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//InitSection:
		//	'Init' '{' (DEF_COMMENT | initDefinitions+=InitDefinition)*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Init' '{' (DEF_COMMENT | initDefinitions+=InitDefinition)* '}'
		public Group getGroup() { return cGroup; }
		
		//'Init'
		public Keyword getInitKeyword_0() { return cInitKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//(DEF_COMMENT | initDefinitions+=InitDefinition)*
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//DEF_COMMENT
		public RuleCall getDEF_COMMENTTerminalRuleCall_2_0() { return cDEF_COMMENTTerminalRuleCall_2_0; }
		
		//initDefinitions+=InitDefinition
		public Assignment getInitDefinitionsAssignment_2_1() { return cInitDefinitionsAssignment_2_1; }
		
		//InitDefinition
		public RuleCall getInitDefinitionsInitDefinitionParserRuleCall_2_1_0() { return cInitDefinitionsInitDefinitionParserRuleCall_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class TypeMaskSectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.TypeMaskSection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTypeMaskKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final RuleCall cDEF_COMMENTTerminalRuleCall_2_0 = (RuleCall)cAlternatives_2.eContents().get(0);
		private final Assignment cTypeMaskDefinitionsAssignment_2_1 = (Assignment)cAlternatives_2.eContents().get(1);
		private final RuleCall cTypeMaskDefinitionsTypeMaskDefinitionParserRuleCall_2_1_0 = (RuleCall)cTypeMaskDefinitionsAssignment_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//TypeMaskSection:
		//	'TypeMask' '{' (DEF_COMMENT | typeMaskDefinitions+=TypeMaskDefinition)+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'TypeMask' '{' (DEF_COMMENT | typeMaskDefinitions+=TypeMaskDefinition)+ '}'
		public Group getGroup() { return cGroup; }
		
		//'TypeMask'
		public Keyword getTypeMaskKeyword_0() { return cTypeMaskKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//(DEF_COMMENT | typeMaskDefinitions+=TypeMaskDefinition)+
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//DEF_COMMENT
		public RuleCall getDEF_COMMENTTerminalRuleCall_2_0() { return cDEF_COMMENTTerminalRuleCall_2_0; }
		
		//typeMaskDefinitions+=TypeMaskDefinition
		public Assignment getTypeMaskDefinitionsAssignment_2_1() { return cTypeMaskDefinitionsAssignment_2_1; }
		
		//TypeMaskDefinition
		public RuleCall getTypeMaskDefinitionsTypeMaskDefinitionParserRuleCall_2_1_0() { return cTypeMaskDefinitionsTypeMaskDefinitionParserRuleCall_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class UnderlyingMaskSectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.UnderlyingMaskSection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUnderlyingMaskKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final RuleCall cDEF_COMMENTTerminalRuleCall_2_0 = (RuleCall)cAlternatives_2.eContents().get(0);
		private final Assignment cUnderlyingMaskDefinitionsAssignment_2_1 = (Assignment)cAlternatives_2.eContents().get(1);
		private final RuleCall cUnderlyingMaskDefinitionsTypeMaskDefinitionParserRuleCall_2_1_0 = (RuleCall)cUnderlyingMaskDefinitionsAssignment_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//UnderlyingMaskSection:
		//	'UnderlyingMask' '{' (DEF_COMMENT | underlyingMaskDefinitions+=TypeMaskDefinition)*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'UnderlyingMask' '{' (DEF_COMMENT | underlyingMaskDefinitions+=TypeMaskDefinition)* '}'
		public Group getGroup() { return cGroup; }
		
		//'UnderlyingMask'
		public Keyword getUnderlyingMaskKeyword_0() { return cUnderlyingMaskKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//(DEF_COMMENT | underlyingMaskDefinitions+=TypeMaskDefinition)*
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//DEF_COMMENT
		public RuleCall getDEF_COMMENTTerminalRuleCall_2_0() { return cDEF_COMMENTTerminalRuleCall_2_0; }
		
		//underlyingMaskDefinitions+=TypeMaskDefinition
		public Assignment getUnderlyingMaskDefinitionsAssignment_2_1() { return cUnderlyingMaskDefinitionsAssignment_2_1; }
		
		//TypeMaskDefinition
		public RuleCall getUnderlyingMaskDefinitionsTypeMaskDefinitionParserRuleCall_2_1_0() { return cUnderlyingMaskDefinitionsTypeMaskDefinitionParserRuleCall_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class UnderlyingListSectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.UnderlyingListSection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUnderlyingListKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final RuleCall cDEF_COMMENTTerminalRuleCall_2_0 = (RuleCall)cAlternatives_2.eContents().get(0);
		private final Assignment cUnderlyingListDefinitionsAssignment_2_1 = (Assignment)cAlternatives_2.eContents().get(1);
		private final RuleCall cUnderlyingListDefinitionsUnderlyingListDefintionParserRuleCall_2_1_0 = (RuleCall)cUnderlyingListDefinitionsAssignment_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//UnderlyingListSection:
		//	'UnderlyingList' '{' (DEF_COMMENT | underlyingListDefinitions+=UnderlyingListDefintion)*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'UnderlyingList' '{' (DEF_COMMENT | underlyingListDefinitions+=UnderlyingListDefintion)* '}'
		public Group getGroup() { return cGroup; }
		
		//'UnderlyingList'
		public Keyword getUnderlyingListKeyword_0() { return cUnderlyingListKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//(DEF_COMMENT | underlyingListDefinitions+=UnderlyingListDefintion)*
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//DEF_COMMENT
		public RuleCall getDEF_COMMENTTerminalRuleCall_2_0() { return cDEF_COMMENTTerminalRuleCall_2_0; }
		
		//underlyingListDefinitions+=UnderlyingListDefintion
		public Assignment getUnderlyingListDefinitionsAssignment_2_1() { return cUnderlyingListDefinitionsAssignment_2_1; }
		
		//UnderlyingListDefintion
		public RuleCall getUnderlyingListDefinitionsUnderlyingListDefintionParserRuleCall_2_1_0() { return cUnderlyingListDefinitionsUnderlyingListDefintionParserRuleCall_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class OptionListSectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.OptionListSection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOptionListKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final RuleCall cDEF_COMMENTTerminalRuleCall_2_0 = (RuleCall)cAlternatives_2.eContents().get(0);
		private final Assignment cOptionListDefinitionsAssignment_2_1 = (Assignment)cAlternatives_2.eContents().get(1);
		private final RuleCall cOptionListDefinitionsUnderlyingListDefintionParserRuleCall_2_1_0 = (RuleCall)cOptionListDefinitionsAssignment_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//OptionListSection:
		//	'OptionList' '{' (DEF_COMMENT | optionListDefinitions+=UnderlyingListDefintion)*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'OptionList' '{' (DEF_COMMENT | optionListDefinitions+=UnderlyingListDefintion)* '}'
		public Group getGroup() { return cGroup; }
		
		//'OptionList'
		public Keyword getOptionListKeyword_0() { return cOptionListKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//(DEF_COMMENT | optionListDefinitions+=UnderlyingListDefintion)*
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//DEF_COMMENT
		public RuleCall getDEF_COMMENTTerminalRuleCall_2_0() { return cDEF_COMMENTTerminalRuleCall_2_0; }
		
		//optionListDefinitions+=UnderlyingListDefintion
		public Assignment getOptionListDefinitionsAssignment_2_1() { return cOptionListDefinitionsAssignment_2_1; }
		
		//UnderlyingListDefintion
		public RuleCall getOptionListDefinitionsUnderlyingListDefintionParserRuleCall_2_1_0() { return cOptionListDefinitionsUnderlyingListDefintionParserRuleCall_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class OptionListLabelSectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.OptionListLabelSection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOptionListLabelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cDEF_COMMENTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//OptionListLabelSection:
		//	'OptionListLabel' '{'
		//	DEF_COMMENT*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'OptionListLabel' '{' DEF_COMMENT* '}'
		public Group getGroup() { return cGroup; }
		
		//'OptionListLabel'
		public Keyword getOptionListLabelKeyword_0() { return cOptionListLabelKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//DEF_COMMENT*
		public RuleCall getDEF_COMMENTTerminalRuleCall_2() { return cDEF_COMMENTTerminalRuleCall_2; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class OptionMaskSectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.OptionMaskSection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOptionMaskKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final RuleCall cDEF_COMMENTTerminalRuleCall_2_0 = (RuleCall)cAlternatives_2.eContents().get(0);
		private final Assignment cOptionMaskDefinitionsAssignment_2_1 = (Assignment)cAlternatives_2.eContents().get(1);
		private final RuleCall cOptionMaskDefinitionsTypeMaskDefinitionParserRuleCall_2_1_0 = (RuleCall)cOptionMaskDefinitionsAssignment_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//OptionMaskSection:
		//	'OptionMask' '{' (DEF_COMMENT | optionMaskDefinitions+=TypeMaskDefinition)*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'OptionMask' '{' (DEF_COMMENT | optionMaskDefinitions+=TypeMaskDefinition)* '}'
		public Group getGroup() { return cGroup; }
		
		//'OptionMask'
		public Keyword getOptionMaskKeyword_0() { return cOptionMaskKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//(DEF_COMMENT | optionMaskDefinitions+=TypeMaskDefinition)*
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//DEF_COMMENT
		public RuleCall getDEF_COMMENTTerminalRuleCall_2_0() { return cDEF_COMMENTTerminalRuleCall_2_0; }
		
		//optionMaskDefinitions+=TypeMaskDefinition
		public Assignment getOptionMaskDefinitionsAssignment_2_1() { return cOptionMaskDefinitionsAssignment_2_1; }
		
		//TypeMaskDefinition
		public RuleCall getOptionMaskDefinitionsTypeMaskDefinitionParserRuleCall_2_1_0() { return cOptionMaskDefinitionsTypeMaskDefinitionParserRuleCall_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class UnderlyingListDefintionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.UnderlyingListDefintion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAddColumnKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Keyword cWidthKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cWidthAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cWidthINTTerminalRuleCall_3_0 = (RuleCall)cWidthAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTitleKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTitleAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTitleSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cTitleAssignment_4_1.eContents().get(0);
		
		//UnderlyingListDefintion:
		//	'AddColumn' id=ID '-width' width=INT ('-title' title=STRING)*;
		@Override public ParserRule getRule() { return rule; }
		
		//'AddColumn' id=ID '-width' width=INT ('-title' title=STRING)*
		public Group getGroup() { return cGroup; }
		
		//'AddColumn'
		public Keyword getAddColumnKeyword_0() { return cAddColumnKeyword_0; }
		
		//id=ID
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//ID
		public RuleCall getIdIDTerminalRuleCall_1_0() { return cIdIDTerminalRuleCall_1_0; }
		
		//'-width'
		public Keyword getWidthKeyword_2() { return cWidthKeyword_2; }
		
		//width=INT
		public Assignment getWidthAssignment_3() { return cWidthAssignment_3; }
		
		//INT
		public RuleCall getWidthINTTerminalRuleCall_3_0() { return cWidthINTTerminalRuleCall_3_0; }
		
		//('-title' title=STRING)*
		public Group getGroup_4() { return cGroup_4; }
		
		//'-title'
		public Keyword getTitleKeyword_4_0() { return cTitleKeyword_4_0; }
		
		//title=STRING
		public Assignment getTitleAssignment_4_1() { return cTitleAssignment_4_1; }
		
		//STRING
		public RuleCall getTitleSTRINGTerminalRuleCall_4_1_0() { return cTitleSTRINGTerminalRuleCall_4_1_0; }
	}
	public class TypeMaskDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.TypeMaskDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAddColumnKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Keyword cRowKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRowAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRowINTTerminalRuleCall_3_0 = (RuleCall)cRowAssignment_3.eContents().get(0);
		private final Keyword cColKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cColAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cColINTTerminalRuleCall_5_0 = (RuleCall)cColAssignment_5.eContents().get(0);
		private final Alternatives cAlternatives_6 = (Alternatives)cGroup.eContents().get(6);
		private final Group cGroup_6_0 = (Group)cAlternatives_6.eContents().get(0);
		private final Keyword cWidthKeyword_6_0_0 = (Keyword)cGroup_6_0.eContents().get(0);
		private final Assignment cWidthAssignment_6_0_1 = (Assignment)cGroup_6_0.eContents().get(1);
		private final RuleCall cWidthINTTerminalRuleCall_6_0_1_0 = (RuleCall)cWidthAssignment_6_0_1.eContents().get(0);
		private final Assignment cSeparatorAssignment_6_1 = (Assignment)cAlternatives_6.eContents().get(1);
		private final Keyword cSeparatorSepKeyword_6_1_0 = (Keyword)cSeparatorAssignment_6_1.eContents().get(0);
		
		//TypeMaskDefinition:
		//	'AddColumn' id=ID '-row' row=INT '-col' col=INT ('-width' width=INT | separator='-sep');
		@Override public ParserRule getRule() { return rule; }
		
		//'AddColumn' id=ID '-row' row=INT '-col' col=INT ('-width' width=INT | separator='-sep')
		public Group getGroup() { return cGroup; }
		
		//'AddColumn'
		public Keyword getAddColumnKeyword_0() { return cAddColumnKeyword_0; }
		
		//id=ID
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//ID
		public RuleCall getIdIDTerminalRuleCall_1_0() { return cIdIDTerminalRuleCall_1_0; }
		
		//'-row'
		public Keyword getRowKeyword_2() { return cRowKeyword_2; }
		
		//row=INT
		public Assignment getRowAssignment_3() { return cRowAssignment_3; }
		
		//INT
		public RuleCall getRowINTTerminalRuleCall_3_0() { return cRowINTTerminalRuleCall_3_0; }
		
		//'-col'
		public Keyword getColKeyword_4() { return cColKeyword_4; }
		
		//col=INT
		public Assignment getColAssignment_5() { return cColAssignment_5; }
		
		//INT
		public RuleCall getColINTTerminalRuleCall_5_0() { return cColINTTerminalRuleCall_5_0; }
		
		//('-width' width=INT | separator='-sep')
		public Alternatives getAlternatives_6() { return cAlternatives_6; }
		
		//'-width' width=INT
		public Group getGroup_6_0() { return cGroup_6_0; }
		
		//'-width'
		public Keyword getWidthKeyword_6_0_0() { return cWidthKeyword_6_0_0; }
		
		//width=INT
		public Assignment getWidthAssignment_6_0_1() { return cWidthAssignment_6_0_1; }
		
		//INT
		public RuleCall getWidthINTTerminalRuleCall_6_0_1_0() { return cWidthINTTerminalRuleCall_6_0_1_0; }
		
		//separator='-sep'
		public Assignment getSeparatorAssignment_6_1() { return cSeparatorAssignment_6_1; }
		
		//'-sep'
		public Keyword getSeparatorSepKeyword_6_1_0() { return cSeparatorSepKeyword_6_1_0; }
	}
	public class UnderlyingMaskDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.UnderlyingMaskDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAddColumnKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Keyword cRowKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRowAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRowINTTerminalRuleCall_3_0 = (RuleCall)cRowAssignment_3.eContents().get(0);
		private final Keyword cColKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cColAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cColINTTerminalRuleCall_5_0 = (RuleCall)cColAssignment_5.eContents().get(0);
		private final Alternatives cAlternatives_6 = (Alternatives)cGroup.eContents().get(6);
		private final Group cGroup_6_0 = (Group)cAlternatives_6.eContents().get(0);
		private final Keyword cWidthKeyword_6_0_0 = (Keyword)cGroup_6_0.eContents().get(0);
		private final Assignment cWidthAssignment_6_0_1 = (Assignment)cGroup_6_0.eContents().get(1);
		private final RuleCall cWidthINTTerminalRuleCall_6_0_1_0 = (RuleCall)cWidthAssignment_6_0_1.eContents().get(0);
		private final Assignment cSeparatorAssignment_6_1 = (Assignment)cAlternatives_6.eContents().get(1);
		private final Keyword cSeparatorSepKeyword_6_1_0 = (Keyword)cSeparatorAssignment_6_1.eContents().get(0);
		
		//UnderlyingMaskDefinition:
		//	'AddColumn' id=ID '-row' row=INT '-col' col=INT ('-width' width=INT | separator='-sep');
		@Override public ParserRule getRule() { return rule; }
		
		//'AddColumn' id=ID '-row' row=INT '-col' col=INT ('-width' width=INT | separator='-sep')
		public Group getGroup() { return cGroup; }
		
		//'AddColumn'
		public Keyword getAddColumnKeyword_0() { return cAddColumnKeyword_0; }
		
		//id=ID
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//ID
		public RuleCall getIdIDTerminalRuleCall_1_0() { return cIdIDTerminalRuleCall_1_0; }
		
		//'-row'
		public Keyword getRowKeyword_2() { return cRowKeyword_2; }
		
		//row=INT
		public Assignment getRowAssignment_3() { return cRowAssignment_3; }
		
		//INT
		public RuleCall getRowINTTerminalRuleCall_3_0() { return cRowINTTerminalRuleCall_3_0; }
		
		//'-col'
		public Keyword getColKeyword_4() { return cColKeyword_4; }
		
		//col=INT
		public Assignment getColAssignment_5() { return cColAssignment_5; }
		
		//INT
		public RuleCall getColINTTerminalRuleCall_5_0() { return cColINTTerminalRuleCall_5_0; }
		
		//('-width' width=INT | separator='-sep')
		public Alternatives getAlternatives_6() { return cAlternatives_6; }
		
		//'-width' width=INT
		public Group getGroup_6_0() { return cGroup_6_0; }
		
		//'-width'
		public Keyword getWidthKeyword_6_0_0() { return cWidthKeyword_6_0_0; }
		
		//width=INT
		public Assignment getWidthAssignment_6_0_1() { return cWidthAssignment_6_0_1; }
		
		//INT
		public RuleCall getWidthINTTerminalRuleCall_6_0_1_0() { return cWidthINTTerminalRuleCall_6_0_1_0; }
		
		//separator='-sep'
		public Assignment getSeparatorAssignment_6_1() { return cSeparatorAssignment_6_1; }
		
		//'-sep'
		public Keyword getSeparatorSepKeyword_6_1_0() { return cSeparatorSepKeyword_6_1_0; }
	}
	public class InitDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.InitDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInitFieldKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Assignment cInitValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cInitValueSTRINGTerminalRuleCall_2_0 = (RuleCall)cInitValueAssignment_2.eContents().get(0);
		
		//InitDefinition:
		//	'InitField' id=ID initValue=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'InitField' id=ID initValue=STRING
		public Group getGroup() { return cGroup; }
		
		//'InitField'
		public Keyword getInitFieldKeyword_0() { return cInitFieldKeyword_0; }
		
		//id=ID
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//ID
		public RuleCall getIdIDTerminalRuleCall_1_0() { return cIdIDTerminalRuleCall_1_0; }
		
		//initValue=STRING
		public Assignment getInitValueAssignment_2() { return cInitValueAssignment_2; }
		
		//STRING
		public RuleCall getInitValueSTRINGTerminalRuleCall_2_0() { return cInitValueSTRINGTerminalRuleCall_2_0; }
	}
	public class FieldDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.FieldDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cFieldTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cFieldTypeFIELD_TYPEEnumRuleCall_0_0 = (RuleCall)cFieldTypeAssignment_0.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Assignment cAccessAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAccessROLEEnumRuleCall_3_0 = (RuleCall)cAccessAssignment_3.eContents().get(0);
		private final Assignment cRecordClassAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRecordClassRECORDCLASSEnumRuleCall_4_0 = (RuleCall)cRecordClassAssignment_4.eContents().get(0);
		private final Keyword cColonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cFieldNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cFieldNameIDTerminalRuleCall_6_0 = (RuleCall)cFieldNameAssignment_6.eContents().get(0);
		private final Assignment cLengthAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cLengthINTTerminalRuleCall_7_0 = (RuleCall)cLengthAssignment_7.eContents().get(0);
		private final Assignment cOptionsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cOptionsOptionParserRuleCall_8_0 = (RuleCall)cOptionsAssignment_8.eContents().get(0);
		
		//FieldDefinition:
		//	fieldType=FIELD_TYPE id=ID name=STRING access=ROLE recordClass=RECORDCLASS ":" fieldName=ID length=INT?
		//	options+=Option*;
		@Override public ParserRule getRule() { return rule; }
		
		//fieldType=FIELD_TYPE id=ID name=STRING access=ROLE recordClass=RECORDCLASS ":" fieldName=ID length=INT? options+=Option*
		public Group getGroup() { return cGroup; }
		
		//fieldType=FIELD_TYPE
		public Assignment getFieldTypeAssignment_0() { return cFieldTypeAssignment_0; }
		
		//FIELD_TYPE
		public RuleCall getFieldTypeFIELD_TYPEEnumRuleCall_0_0() { return cFieldTypeFIELD_TYPEEnumRuleCall_0_0; }
		
		//id=ID
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//ID
		public RuleCall getIdIDTerminalRuleCall_1_0() { return cIdIDTerminalRuleCall_1_0; }
		
		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }
		
		//access=ROLE
		public Assignment getAccessAssignment_3() { return cAccessAssignment_3; }
		
		//ROLE
		public RuleCall getAccessROLEEnumRuleCall_3_0() { return cAccessROLEEnumRuleCall_3_0; }
		
		//recordClass=RECORDCLASS
		public Assignment getRecordClassAssignment_4() { return cRecordClassAssignment_4; }
		
		//RECORDCLASS
		public RuleCall getRecordClassRECORDCLASSEnumRuleCall_4_0() { return cRecordClassRECORDCLASSEnumRuleCall_4_0; }
		
		//":"
		public Keyword getColonKeyword_5() { return cColonKeyword_5; }
		
		//fieldName=ID
		public Assignment getFieldNameAssignment_6() { return cFieldNameAssignment_6; }
		
		//ID
		public RuleCall getFieldNameIDTerminalRuleCall_6_0() { return cFieldNameIDTerminalRuleCall_6_0; }
		
		//length=INT?
		public Assignment getLengthAssignment_7() { return cLengthAssignment_7; }
		
		//INT
		public RuleCall getLengthINTTerminalRuleCall_7_0() { return cLengthINTTerminalRuleCall_7_0; }
		
		//options+=Option*
		public Assignment getOptionsAssignment_8() { return cOptionsAssignment_8; }
		
		//Option
		public RuleCall getOptionsOptionParserRuleCall_8_0() { return cOptionsOptionParserRuleCall_8_0; }
	}
	public class OptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.Option");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cOptionValprocParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cOptionStrictParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cOptionRangeParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cOptionContribParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Option:
		//	OptionValproc | OptionStrict | OptionRange | OptionContrib;
		@Override public ParserRule getRule() { return rule; }
		
		//OptionValproc | OptionStrict | OptionRange | OptionContrib
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//OptionValproc
		public RuleCall getOptionValprocParserRuleCall_0() { return cOptionValprocParserRuleCall_0; }
		
		//OptionStrict
		public RuleCall getOptionStrictParserRuleCall_1() { return cOptionStrictParserRuleCall_1; }
		
		//OptionRange
		public RuleCall getOptionRangeParserRuleCall_2() { return cOptionRangeParserRuleCall_2; }
		
		//OptionContrib
		public RuleCall getOptionContribParserRuleCall_3() { return cOptionContribParserRuleCall_3; }
	}
	public class OptionValprocElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.OptionValproc");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cValprocAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cValprocValprocKeyword_0_0 = (Keyword)cValprocAssignment_0.eContents().get(0);
		private final Assignment cTclProcAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTclProcIDTerminalRuleCall_1_0 = (RuleCall)cTclProcAssignment_1.eContents().get(0);
		
		//OptionValproc:
		//	valproc="-valproc" tclProc=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//valproc="-valproc" tclProc=ID
		public Group getGroup() { return cGroup; }
		
		//valproc="-valproc"
		public Assignment getValprocAssignment_0() { return cValprocAssignment_0; }
		
		//"-valproc"
		public Keyword getValprocValprocKeyword_0_0() { return cValprocValprocKeyword_0_0; }
		
		//tclProc=ID
		public Assignment getTclProcAssignment_1() { return cTclProcAssignment_1; }
		
		//ID
		public RuleCall getTclProcIDTerminalRuleCall_1_0() { return cTclProcIDTerminalRuleCall_1_0; }
	}
	public class OptionStrictElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.OptionStrict");
		private final Assignment cStrictAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cStrictStrictKeyword_0 = (Keyword)cStrictAssignment.eContents().get(0);
		
		//OptionStrict:
		//	strict?="-strict";
		@Override public ParserRule getRule() { return rule; }
		
		//strict?="-strict"
		public Assignment getStrictAssignment() { return cStrictAssignment; }
		
		//"-strict"
		public Keyword getStrictStrictKeyword_0() { return cStrictStrictKeyword_0; }
	}
	public class OptionRangeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.OptionRange");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRangeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cListKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMinAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMinINTTerminalRuleCall_2_0 = (RuleCall)cMinAssignment_2.eContents().get(0);
		private final Assignment cMaxAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMaxINTTerminalRuleCall_3_0 = (RuleCall)cMaxAssignment_3.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//OptionRange:
		//	"-range" "[list" min=INT max=INT "]";
		@Override public ParserRule getRule() { return rule; }
		
		//"-range" "[list" min=INT max=INT "]"
		public Group getGroup() { return cGroup; }
		
		//"-range"
		public Keyword getRangeKeyword_0() { return cRangeKeyword_0; }
		
		//"[list"
		public Keyword getListKeyword_1() { return cListKeyword_1; }
		
		//min=INT
		public Assignment getMinAssignment_2() { return cMinAssignment_2; }
		
		//INT
		public RuleCall getMinINTTerminalRuleCall_2_0() { return cMinINTTerminalRuleCall_2_0; }
		
		//max=INT
		public Assignment getMaxAssignment_3() { return cMaxAssignment_3; }
		
		//INT
		public RuleCall getMaxINTTerminalRuleCall_3_0() { return cMaxINTTerminalRuleCall_3_0; }
		
		//"]"
		public Keyword getRightSquareBracketKeyword_4() { return cRightSquareBracketKeyword_4; }
	}
	public class OptionContribElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.OptionContrib");
		private final Assignment cContribAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cContribContribKeyword_0 = (Keyword)cContribAssignment.eContents().get(0);
		
		//OptionContrib:
		//	contrib?="-contrib";
		@Override public ParserRule getRule() { return rule; }
		
		//contrib?="-contrib"
		public Assignment getContribAssignment() { return cContribAssignment; }
		
		//"-contrib"
		public Keyword getContribContribKeyword_0() { return cContribContribKeyword_0; }
	}
	
	public class FIELD_TYPEElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.FIELD_TYPE");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSTRING_FIELDEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSTRING_FIELDStringFieldKeyword_0_0 = (Keyword)cSTRING_FIELDEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cTIME_FIELDEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cTIME_FIELDTimeFieldKeyword_1_0 = (Keyword)cTIME_FIELDEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cINTEGER_FIELDEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cINTEGER_FIELDIntegerFieldKeyword_2_0 = (Keyword)cINTEGER_FIELDEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cPRICE_FIELDEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cPRICE_FIELDPriceFieldKeyword_3_0 = (Keyword)cPRICE_FIELDEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cDOUBLE_FIELDEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cDOUBLE_FIELDDoubleFieldKeyword_4_0 = (Keyword)cDOUBLE_FIELDEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cZAHL_FIELDEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cZAHL_FIELDZahlFieldKeyword_5_0 = (Keyword)cZAHL_FIELDEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cDATE_FIELDEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cDATE_FIELDDateFieldKeyword_6_0 = (Keyword)cDATE_FIELDEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum FIELD_TYPE:
		//	STRING_FIELD='StringField' | TIME_FIELD='TimeField' | INTEGER_FIELD='IntegerField' | PRICE_FIELD='PriceField' |
		//	DOUBLE_FIELD='DoubleField' | ZAHL_FIELD='ZahlField' | DATE_FIELD='DateField';
		public EnumRule getRule() { return rule; }
		
		//STRING_FIELD='StringField' | TIME_FIELD='TimeField' | INTEGER_FIELD='IntegerField' | PRICE_FIELD='PriceField' |
		//DOUBLE_FIELD='DoubleField' | ZAHL_FIELD='ZahlField' | DATE_FIELD='DateField'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING_FIELD='StringField'
		public EnumLiteralDeclaration getSTRING_FIELDEnumLiteralDeclaration_0() { return cSTRING_FIELDEnumLiteralDeclaration_0; }
		
		//'StringField'
		public Keyword getSTRING_FIELDStringFieldKeyword_0_0() { return cSTRING_FIELDStringFieldKeyword_0_0; }
		
		//TIME_FIELD='TimeField'
		public EnumLiteralDeclaration getTIME_FIELDEnumLiteralDeclaration_1() { return cTIME_FIELDEnumLiteralDeclaration_1; }
		
		//'TimeField'
		public Keyword getTIME_FIELDTimeFieldKeyword_1_0() { return cTIME_FIELDTimeFieldKeyword_1_0; }
		
		//INTEGER_FIELD='IntegerField'
		public EnumLiteralDeclaration getINTEGER_FIELDEnumLiteralDeclaration_2() { return cINTEGER_FIELDEnumLiteralDeclaration_2; }
		
		//'IntegerField'
		public Keyword getINTEGER_FIELDIntegerFieldKeyword_2_0() { return cINTEGER_FIELDIntegerFieldKeyword_2_0; }
		
		//PRICE_FIELD='PriceField'
		public EnumLiteralDeclaration getPRICE_FIELDEnumLiteralDeclaration_3() { return cPRICE_FIELDEnumLiteralDeclaration_3; }
		
		//'PriceField'
		public Keyword getPRICE_FIELDPriceFieldKeyword_3_0() { return cPRICE_FIELDPriceFieldKeyword_3_0; }
		
		//DOUBLE_FIELD='DoubleField'
		public EnumLiteralDeclaration getDOUBLE_FIELDEnumLiteralDeclaration_4() { return cDOUBLE_FIELDEnumLiteralDeclaration_4; }
		
		//'DoubleField'
		public Keyword getDOUBLE_FIELDDoubleFieldKeyword_4_0() { return cDOUBLE_FIELDDoubleFieldKeyword_4_0; }
		
		//ZAHL_FIELD='ZahlField'
		public EnumLiteralDeclaration getZAHL_FIELDEnumLiteralDeclaration_5() { return cZAHL_FIELDEnumLiteralDeclaration_5; }
		
		//'ZahlField'
		public Keyword getZAHL_FIELDZahlFieldKeyword_5_0() { return cZAHL_FIELDZahlFieldKeyword_5_0; }
		
		//DATE_FIELD='DateField'
		public EnumLiteralDeclaration getDATE_FIELDEnumLiteralDeclaration_6() { return cDATE_FIELDEnumLiteralDeclaration_6; }
		
		//'DateField'
		public Keyword getDATE_FIELDDateFieldKeyword_6_0() { return cDATE_FIELDDateFieldKeyword_6_0; }
	}
	public class ROLEElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.ROLE");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cRADMINEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cRADMINRadminKeyword_0_0 = (Keyword)cRADMINEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cNONEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cNONENoneKeyword_1_0 = (Keyword)cNONEEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cRTRADEREnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cRTRADERRtraderKeyword_2_0 = (Keyword)cRTRADEREnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cSUPERVISOREnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cSUPERVISORSupervisorKeyword_3_0 = (Keyword)cSUPERVISOREnumLiteralDeclaration_3.eContents().get(0);
		
		//enum ROLE:
		//	RADMIN='radmin' | NONE='none' | RTRADER='rtrader' | SUPERVISOR='supervisor';
		public EnumRule getRule() { return rule; }
		
		//RADMIN='radmin' | NONE='none' | RTRADER='rtrader' | SUPERVISOR='supervisor'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//RADMIN='radmin'
		public EnumLiteralDeclaration getRADMINEnumLiteralDeclaration_0() { return cRADMINEnumLiteralDeclaration_0; }
		
		//'radmin'
		public Keyword getRADMINRadminKeyword_0_0() { return cRADMINRadminKeyword_0_0; }
		
		//NONE='none'
		public EnumLiteralDeclaration getNONEEnumLiteralDeclaration_1() { return cNONEEnumLiteralDeclaration_1; }
		
		//'none'
		public Keyword getNONENoneKeyword_1_0() { return cNONENoneKeyword_1_0; }
		
		//RTRADER='rtrader'
		public EnumLiteralDeclaration getRTRADEREnumLiteralDeclaration_2() { return cRTRADEREnumLiteralDeclaration_2; }
		
		//'rtrader'
		public Keyword getRTRADERRtraderKeyword_2_0() { return cRTRADERRtraderKeyword_2_0; }
		
		//SUPERVISOR='supervisor'
		public EnumLiteralDeclaration getSUPERVISOREnumLiteralDeclaration_3() { return cSUPERVISOREnumLiteralDeclaration_3; }
		
		//'supervisor'
		public Keyword getSUPERVISORSupervisorKeyword_3_0() { return cSUPERVISORSupervisorKeyword_3_0; }
	}
	public class RECORDCLASSElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.RECORDCLASS");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMETHOD_READ_ONLYEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMETHOD_READ_ONLYBKeyword_0_0 = (Keyword)cMETHOD_READ_ONLYEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPARENT_READ_ONLYEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPARENT_READ_ONLYUKeyword_1_0 = (Keyword)cPARENT_READ_ONLYEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cPARENT_READ_WRITEEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cPARENT_READ_WRITEGKeyword_2_0 = (Keyword)cPARENT_READ_WRITEEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cPARENT_READ_REFERENCEEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cPARENT_READ_REFERENCERKeyword_3_0 = (Keyword)cPARENT_READ_REFERENCEEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cCHILD_READ_ONLYEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cCHILD_READ_ONLYDKeyword_4_0 = (Keyword)cCHILD_READ_ONLYEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cCHILD_READ_WRITEEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cCHILD_READ_WRITEPKeyword_5_0 = (Keyword)cCHILD_READ_WRITEEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cCHILD_READ_REFERENCEEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cCHILD_READ_REFERENCESKeyword_6_0 = (Keyword)cCHILD_READ_REFERENCEEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum RECORDCLASS:
		//	METHOD_READ_ONLY='B' | PARENT_READ_ONLY='U' | PARENT_READ_WRITE='G' | PARENT_READ_REFERENCE='R' | CHILD_READ_ONLY='D'
		//	| CHILD_READ_WRITE='P' | CHILD_READ_REFERENCE='S';
		public EnumRule getRule() { return rule; }
		
		//METHOD_READ_ONLY='B' | PARENT_READ_ONLY='U' | PARENT_READ_WRITE='G' | PARENT_READ_REFERENCE='R' | CHILD_READ_ONLY='D' |
		//CHILD_READ_WRITE='P' | CHILD_READ_REFERENCE='S'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//METHOD_READ_ONLY='B'
		public EnumLiteralDeclaration getMETHOD_READ_ONLYEnumLiteralDeclaration_0() { return cMETHOD_READ_ONLYEnumLiteralDeclaration_0; }
		
		//'B'
		public Keyword getMETHOD_READ_ONLYBKeyword_0_0() { return cMETHOD_READ_ONLYBKeyword_0_0; }
		
		//PARENT_READ_ONLY='U'
		public EnumLiteralDeclaration getPARENT_READ_ONLYEnumLiteralDeclaration_1() { return cPARENT_READ_ONLYEnumLiteralDeclaration_1; }
		
		//'U'
		public Keyword getPARENT_READ_ONLYUKeyword_1_0() { return cPARENT_READ_ONLYUKeyword_1_0; }
		
		//PARENT_READ_WRITE='G'
		public EnumLiteralDeclaration getPARENT_READ_WRITEEnumLiteralDeclaration_2() { return cPARENT_READ_WRITEEnumLiteralDeclaration_2; }
		
		//'G'
		public Keyword getPARENT_READ_WRITEGKeyword_2_0() { return cPARENT_READ_WRITEGKeyword_2_0; }
		
		//PARENT_READ_REFERENCE='R'
		public EnumLiteralDeclaration getPARENT_READ_REFERENCEEnumLiteralDeclaration_3() { return cPARENT_READ_REFERENCEEnumLiteralDeclaration_3; }
		
		//'R'
		public Keyword getPARENT_READ_REFERENCERKeyword_3_0() { return cPARENT_READ_REFERENCERKeyword_3_0; }
		
		//CHILD_READ_ONLY='D'
		public EnumLiteralDeclaration getCHILD_READ_ONLYEnumLiteralDeclaration_4() { return cCHILD_READ_ONLYEnumLiteralDeclaration_4; }
		
		//'D'
		public Keyword getCHILD_READ_ONLYDKeyword_4_0() { return cCHILD_READ_ONLYDKeyword_4_0; }
		
		//CHILD_READ_WRITE='P'
		public EnumLiteralDeclaration getCHILD_READ_WRITEEnumLiteralDeclaration_5() { return cCHILD_READ_WRITEEnumLiteralDeclaration_5; }
		
		//'P'
		public Keyword getCHILD_READ_WRITEPKeyword_5_0() { return cCHILD_READ_WRITEPKeyword_5_0; }
		
		//CHILD_READ_REFERENCE='S'
		public EnumLiteralDeclaration getCHILD_READ_REFERENCEEnumLiteralDeclaration_6() { return cCHILD_READ_REFERENCEEnumLiteralDeclaration_6; }
		
		//'S'
		public Keyword getCHILD_READ_REFERENCESKeyword_6_0() { return cCHILD_READ_REFERENCESKeyword_6_0; }
	}
	
	private final DefinitionElements pDefinition;
	private final DataElements pData;
	private final InitSectionElements pInitSection;
	private final TypeMaskSectionElements pTypeMaskSection;
	private final UnderlyingMaskSectionElements pUnderlyingMaskSection;
	private final UnderlyingListSectionElements pUnderlyingListSection;
	private final OptionListSectionElements pOptionListSection;
	private final OptionListLabelSectionElements pOptionListLabelSection;
	private final OptionMaskSectionElements pOptionMaskSection;
	private final UnderlyingListDefintionElements pUnderlyingListDefintion;
	private final TypeMaskDefinitionElements pTypeMaskDefinition;
	private final UnderlyingMaskDefinitionElements pUnderlyingMaskDefinition;
	private final InitDefinitionElements pInitDefinition;
	private final FieldDefinitionElements pFieldDefinition;
	private final OptionElements pOption;
	private final OptionValprocElements pOptionValproc;
	private final OptionStrictElements pOptionStrict;
	private final OptionRangeElements pOptionRange;
	private final OptionContribElements pOptionContrib;
	private final TerminalRule tDEF_COMMENT;
	private final FIELD_TYPEElements eFIELD_TYPE;
	private final ROLEElements eROLE;
	private final RECORDCLASSElements eRECORDCLASS;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DefinitionDSLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDefinition = new DefinitionElements();
		this.pData = new DataElements();
		this.pInitSection = new InitSectionElements();
		this.pTypeMaskSection = new TypeMaskSectionElements();
		this.pUnderlyingMaskSection = new UnderlyingMaskSectionElements();
		this.pUnderlyingListSection = new UnderlyingListSectionElements();
		this.pOptionListSection = new OptionListSectionElements();
		this.pOptionListLabelSection = new OptionListLabelSectionElements();
		this.pOptionMaskSection = new OptionMaskSectionElements();
		this.pUnderlyingListDefintion = new UnderlyingListDefintionElements();
		this.pTypeMaskDefinition = new TypeMaskDefinitionElements();
		this.pUnderlyingMaskDefinition = new UnderlyingMaskDefinitionElements();
		this.pInitDefinition = new InitDefinitionElements();
		this.pFieldDefinition = new FieldDefinitionElements();
		this.pOption = new OptionElements();
		this.pOptionValproc = new OptionValprocElements();
		this.pOptionStrict = new OptionStrictElements();
		this.pOptionRange = new OptionRangeElements();
		this.pOptionContrib = new OptionContribElements();
		this.tDEF_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ch.raiffeisen.ipricer.definition.DefinitionDSL.DEF_COMMENT");
		this.eFIELD_TYPE = new FIELD_TYPEElements();
		this.eROLE = new ROLEElements();
		this.eRECORDCLASS = new RECORDCLASSElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("ch.raiffeisen.ipricer.definition.DefinitionDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Definition:
	//	'Definition' methodName=ID guiLabelMethod=STRING guiLabelParent=STRING guiLabelChild=STRING '{'
	//	data=Data
	//	initSection=InitSection
	//	typeMaskSection=TypeMaskSection
	//	underlyingListSection=UnderlyingListSection
	//	underlyingMaskSection=UnderlyingMaskSection
	//	optionListSection=OptionListSection
	//	optionListLabelSection=OptionListLabelSection
	//	optionMaskSection=OptionMaskSection
	//	'}'
	//	eventuellTclProcedures+=(ID | ANY_OTHER)*;
	public DefinitionElements getDefinitionAccess() {
		return pDefinition;
	}
	
	public ParserRule getDefinitionRule() {
		return getDefinitionAccess().getRule();
	}
	
	//Data:
	//	'Data' '{' (DEF_COMMENT | fieldDefinitions+=FieldDefinition)+
	//	'}';
	public DataElements getDataAccess() {
		return pData;
	}
	
	public ParserRule getDataRule() {
		return getDataAccess().getRule();
	}
	
	//InitSection:
	//	'Init' '{' (DEF_COMMENT | initDefinitions+=InitDefinition)*
	//	'}';
	public InitSectionElements getInitSectionAccess() {
		return pInitSection;
	}
	
	public ParserRule getInitSectionRule() {
		return getInitSectionAccess().getRule();
	}
	
	//TypeMaskSection:
	//	'TypeMask' '{' (DEF_COMMENT | typeMaskDefinitions+=TypeMaskDefinition)+
	//	'}';
	public TypeMaskSectionElements getTypeMaskSectionAccess() {
		return pTypeMaskSection;
	}
	
	public ParserRule getTypeMaskSectionRule() {
		return getTypeMaskSectionAccess().getRule();
	}
	
	//UnderlyingMaskSection:
	//	'UnderlyingMask' '{' (DEF_COMMENT | underlyingMaskDefinitions+=TypeMaskDefinition)*
	//	'}';
	public UnderlyingMaskSectionElements getUnderlyingMaskSectionAccess() {
		return pUnderlyingMaskSection;
	}
	
	public ParserRule getUnderlyingMaskSectionRule() {
		return getUnderlyingMaskSectionAccess().getRule();
	}
	
	//UnderlyingListSection:
	//	'UnderlyingList' '{' (DEF_COMMENT | underlyingListDefinitions+=UnderlyingListDefintion)*
	//	'}';
	public UnderlyingListSectionElements getUnderlyingListSectionAccess() {
		return pUnderlyingListSection;
	}
	
	public ParserRule getUnderlyingListSectionRule() {
		return getUnderlyingListSectionAccess().getRule();
	}
	
	//OptionListSection:
	//	'OptionList' '{' (DEF_COMMENT | optionListDefinitions+=UnderlyingListDefintion)*
	//	'}';
	public OptionListSectionElements getOptionListSectionAccess() {
		return pOptionListSection;
	}
	
	public ParserRule getOptionListSectionRule() {
		return getOptionListSectionAccess().getRule();
	}
	
	//OptionListLabelSection:
	//	'OptionListLabel' '{'
	//	DEF_COMMENT*
	//	'}';
	public OptionListLabelSectionElements getOptionListLabelSectionAccess() {
		return pOptionListLabelSection;
	}
	
	public ParserRule getOptionListLabelSectionRule() {
		return getOptionListLabelSectionAccess().getRule();
	}
	
	//OptionMaskSection:
	//	'OptionMask' '{' (DEF_COMMENT | optionMaskDefinitions+=TypeMaskDefinition)*
	//	'}';
	public OptionMaskSectionElements getOptionMaskSectionAccess() {
		return pOptionMaskSection;
	}
	
	public ParserRule getOptionMaskSectionRule() {
		return getOptionMaskSectionAccess().getRule();
	}
	
	//UnderlyingListDefintion:
	//	'AddColumn' id=ID '-width' width=INT ('-title' title=STRING)*;
	public UnderlyingListDefintionElements getUnderlyingListDefintionAccess() {
		return pUnderlyingListDefintion;
	}
	
	public ParserRule getUnderlyingListDefintionRule() {
		return getUnderlyingListDefintionAccess().getRule();
	}
	
	//TypeMaskDefinition:
	//	'AddColumn' id=ID '-row' row=INT '-col' col=INT ('-width' width=INT | separator='-sep');
	public TypeMaskDefinitionElements getTypeMaskDefinitionAccess() {
		return pTypeMaskDefinition;
	}
	
	public ParserRule getTypeMaskDefinitionRule() {
		return getTypeMaskDefinitionAccess().getRule();
	}
	
	//UnderlyingMaskDefinition:
	//	'AddColumn' id=ID '-row' row=INT '-col' col=INT ('-width' width=INT | separator='-sep');
	public UnderlyingMaskDefinitionElements getUnderlyingMaskDefinitionAccess() {
		return pUnderlyingMaskDefinition;
	}
	
	public ParserRule getUnderlyingMaskDefinitionRule() {
		return getUnderlyingMaskDefinitionAccess().getRule();
	}
	
	//InitDefinition:
	//	'InitField' id=ID initValue=STRING;
	public InitDefinitionElements getInitDefinitionAccess() {
		return pInitDefinition;
	}
	
	public ParserRule getInitDefinitionRule() {
		return getInitDefinitionAccess().getRule();
	}
	
	//FieldDefinition:
	//	fieldType=FIELD_TYPE id=ID name=STRING access=ROLE recordClass=RECORDCLASS ":" fieldName=ID length=INT?
	//	options+=Option*;
	public FieldDefinitionElements getFieldDefinitionAccess() {
		return pFieldDefinition;
	}
	
	public ParserRule getFieldDefinitionRule() {
		return getFieldDefinitionAccess().getRule();
	}
	
	//Option:
	//	OptionValproc | OptionStrict | OptionRange | OptionContrib;
	public OptionElements getOptionAccess() {
		return pOption;
	}
	
	public ParserRule getOptionRule() {
		return getOptionAccess().getRule();
	}
	
	//OptionValproc:
	//	valproc="-valproc" tclProc=ID;
	public OptionValprocElements getOptionValprocAccess() {
		return pOptionValproc;
	}
	
	public ParserRule getOptionValprocRule() {
		return getOptionValprocAccess().getRule();
	}
	
	//OptionStrict:
	//	strict?="-strict";
	public OptionStrictElements getOptionStrictAccess() {
		return pOptionStrict;
	}
	
	public ParserRule getOptionStrictRule() {
		return getOptionStrictAccess().getRule();
	}
	
	//OptionRange:
	//	"-range" "[list" min=INT max=INT "]";
	public OptionRangeElements getOptionRangeAccess() {
		return pOptionRange;
	}
	
	public ParserRule getOptionRangeRule() {
		return getOptionRangeAccess().getRule();
	}
	
	//OptionContrib:
	//	contrib?="-contrib";
	public OptionContribElements getOptionContribAccess() {
		return pOptionContrib;
	}
	
	public ParserRule getOptionContribRule() {
		return getOptionContribAccess().getRule();
	}
	
	//terminal DEF_COMMENT:
	//	'#' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getDEF_COMMENTRule() {
		return tDEF_COMMENT;
	}
	
	//enum FIELD_TYPE:
	//	STRING_FIELD='StringField' | TIME_FIELD='TimeField' | INTEGER_FIELD='IntegerField' | PRICE_FIELD='PriceField' |
	//	DOUBLE_FIELD='DoubleField' | ZAHL_FIELD='ZahlField' | DATE_FIELD='DateField';
	public FIELD_TYPEElements getFIELD_TYPEAccess() {
		return eFIELD_TYPE;
	}
	
	public EnumRule getFIELD_TYPERule() {
		return getFIELD_TYPEAccess().getRule();
	}
	
	//enum ROLE:
	//	RADMIN='radmin' | NONE='none' | RTRADER='rtrader' | SUPERVISOR='supervisor';
	public ROLEElements getROLEAccess() {
		return eROLE;
	}
	
	public EnumRule getROLERule() {
		return getROLEAccess().getRule();
	}
	
	//enum RECORDCLASS:
	//	METHOD_READ_ONLY='B' | PARENT_READ_ONLY='U' | PARENT_READ_WRITE='G' | PARENT_READ_REFERENCE='R' | CHILD_READ_ONLY='D'
	//	| CHILD_READ_WRITE='P' | CHILD_READ_REFERENCE='S';
	public RECORDCLASSElements getRECORDCLASSAccess() {
		return eRECORDCLASS;
	}
	
	public EnumRule getRECORDCLASSRule() {
		return getRECORDCLASSAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
