/*
 * generated by Xtext 2.9.2
 */
package ch.raiffeisen.ipricer.definition.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class DefinitionDSLIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new DefinitionDSLStandaloneSetupIdea().createInjector
	}

}
