/*
 * generated by Xtext 2.9.2
 */
package ch.raiffeisen.ipricer.definition.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class DefinitionDSLIdeaModule extends AbstractDefinitionDSLIdeaModule {
}
