/**
 * generated by Xtext 2.9.2
 */
package ch.raiffeisen.ipricer.definition.definitionDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ch.raiffeisen.ipricer.definition.definitionDSL.DefinitionDSLFactory
 * @model kind="package"
 * @generated
 */
public interface DefinitionDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "definitionDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.raiffeisen.ch/ipricer/definition/DefinitionDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "definitionDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DefinitionDSLPackage eINSTANCE = ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionImpl <em>Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionImpl
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getDefinition()
   * @generated
   */
  int DEFINITION = 0;

  /**
   * The feature id for the '<em><b>Method Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__METHOD_NAME = 0;

  /**
   * The feature id for the '<em><b>Gui Label Method</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__GUI_LABEL_METHOD = 1;

  /**
   * The feature id for the '<em><b>Gui Label Parent</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__GUI_LABEL_PARENT = 2;

  /**
   * The feature id for the '<em><b>Gui Label Child</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__GUI_LABEL_CHILD = 3;

  /**
   * The feature id for the '<em><b>Data</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__DATA = 4;

  /**
   * The feature id for the '<em><b>Init Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__INIT_SECTION = 5;

  /**
   * The feature id for the '<em><b>Type Mask Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__TYPE_MASK_SECTION = 6;

  /**
   * The feature id for the '<em><b>Underlying List Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__UNDERLYING_LIST_SECTION = 7;

  /**
   * The feature id for the '<em><b>Underlying Mask Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__UNDERLYING_MASK_SECTION = 8;

  /**
   * The feature id for the '<em><b>Option List Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__OPTION_LIST_SECTION = 9;

  /**
   * The feature id for the '<em><b>Option List Label Section</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__OPTION_LIST_LABEL_SECTION = 10;

  /**
   * The feature id for the '<em><b>Option Mask Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__OPTION_MASK_SECTION = 11;

  /**
   * The feature id for the '<em><b>Eventuell Tcl Procedures</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__EVENTUELL_TCL_PROCEDURES = 12;

  /**
   * The number of structural features of the '<em>Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION_FEATURE_COUNT = 13;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.DataImpl <em>Data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DataImpl
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getData()
   * @generated
   */
  int DATA = 1;

  /**
   * The feature id for the '<em><b>Field Definitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA__FIELD_DEFINITIONS = 0;

  /**
   * The number of structural features of the '<em>Data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.InitSectionImpl <em>Init Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.InitSectionImpl
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getInitSection()
   * @generated
   */
  int INIT_SECTION = 2;

  /**
   * The feature id for the '<em><b>Init Definitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INIT_SECTION__INIT_DEFINITIONS = 0;

  /**
   * The number of structural features of the '<em>Init Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INIT_SECTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.TypeMaskSectionImpl <em>Type Mask Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.TypeMaskSectionImpl
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getTypeMaskSection()
   * @generated
   */
  int TYPE_MASK_SECTION = 3;

  /**
   * The feature id for the '<em><b>Type Mask Definitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_MASK_SECTION__TYPE_MASK_DEFINITIONS = 0;

  /**
   * The number of structural features of the '<em>Type Mask Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_MASK_SECTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.UnderlyingMaskSectionImpl <em>Underlying Mask Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.UnderlyingMaskSectionImpl
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getUnderlyingMaskSection()
   * @generated
   */
  int UNDERLYING_MASK_SECTION = 4;

  /**
   * The feature id for the '<em><b>Underlying Mask Definitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNDERLYING_MASK_SECTION__UNDERLYING_MASK_DEFINITIONS = 0;

  /**
   * The number of structural features of the '<em>Underlying Mask Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNDERLYING_MASK_SECTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.UnderlyingListSectionImpl <em>Underlying List Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.UnderlyingListSectionImpl
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getUnderlyingListSection()
   * @generated
   */
  int UNDERLYING_LIST_SECTION = 5;

  /**
   * The feature id for the '<em><b>Underlying List Definitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNDERLYING_LIST_SECTION__UNDERLYING_LIST_DEFINITIONS = 0;

  /**
   * The number of structural features of the '<em>Underlying List Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNDERLYING_LIST_SECTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionListSectionImpl <em>Option List Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionListSectionImpl
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getOptionListSection()
   * @generated
   */
  int OPTION_LIST_SECTION = 6;

  /**
   * The feature id for the '<em><b>Option List Definitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_LIST_SECTION__OPTION_LIST_DEFINITIONS = 0;

  /**
   * The number of structural features of the '<em>Option List Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_LIST_SECTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionMaskSectionImpl <em>Option Mask Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionMaskSectionImpl
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getOptionMaskSection()
   * @generated
   */
  int OPTION_MASK_SECTION = 7;

  /**
   * The feature id for the '<em><b>Option Mask Definitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_MASK_SECTION__OPTION_MASK_DEFINITIONS = 0;

  /**
   * The number of structural features of the '<em>Option Mask Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_MASK_SECTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.UnderlyingListDefintionImpl <em>Underlying List Defintion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.UnderlyingListDefintionImpl
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getUnderlyingListDefintion()
   * @generated
   */
  int UNDERLYING_LIST_DEFINTION = 8;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNDERLYING_LIST_DEFINTION__ID = 0;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNDERLYING_LIST_DEFINTION__WIDTH = 1;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNDERLYING_LIST_DEFINTION__TITLE = 2;

  /**
   * The number of structural features of the '<em>Underlying List Defintion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNDERLYING_LIST_DEFINTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.TypeMaskDefinitionImpl <em>Type Mask Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.TypeMaskDefinitionImpl
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getTypeMaskDefinition()
   * @generated
   */
  int TYPE_MASK_DEFINITION = 9;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_MASK_DEFINITION__ID = 0;

  /**
   * The feature id for the '<em><b>Row</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_MASK_DEFINITION__ROW = 1;

  /**
   * The feature id for the '<em><b>Col</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_MASK_DEFINITION__COL = 2;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_MASK_DEFINITION__WIDTH = 3;

  /**
   * The feature id for the '<em><b>Separator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_MASK_DEFINITION__SEPARATOR = 4;

  /**
   * The number of structural features of the '<em>Type Mask Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_MASK_DEFINITION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.UnderlyingMaskDefinitionImpl <em>Underlying Mask Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.UnderlyingMaskDefinitionImpl
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getUnderlyingMaskDefinition()
   * @generated
   */
  int UNDERLYING_MASK_DEFINITION = 10;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNDERLYING_MASK_DEFINITION__ID = 0;

  /**
   * The feature id for the '<em><b>Row</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNDERLYING_MASK_DEFINITION__ROW = 1;

  /**
   * The feature id for the '<em><b>Col</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNDERLYING_MASK_DEFINITION__COL = 2;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNDERLYING_MASK_DEFINITION__WIDTH = 3;

  /**
   * The feature id for the '<em><b>Separator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNDERLYING_MASK_DEFINITION__SEPARATOR = 4;

  /**
   * The number of structural features of the '<em>Underlying Mask Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNDERLYING_MASK_DEFINITION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.InitDefinitionImpl <em>Init Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.InitDefinitionImpl
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getInitDefinition()
   * @generated
   */
  int INIT_DEFINITION = 11;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INIT_DEFINITION__ID = 0;

  /**
   * The feature id for the '<em><b>Init Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INIT_DEFINITION__INIT_VALUE = 1;

  /**
   * The number of structural features of the '<em>Init Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INIT_DEFINITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.FieldDefinitionImpl <em>Field Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.FieldDefinitionImpl
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getFieldDefinition()
   * @generated
   */
  int FIELD_DEFINITION = 12;

  /**
   * The feature id for the '<em><b>Field Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_DEFINITION__FIELD_TYPE = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_DEFINITION__ID = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_DEFINITION__NAME = 2;

  /**
   * The feature id for the '<em><b>Access</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_DEFINITION__ACCESS = 3;

  /**
   * The feature id for the '<em><b>Record Class</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_DEFINITION__RECORD_CLASS = 4;

  /**
   * The feature id for the '<em><b>Field Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_DEFINITION__FIELD_NAME = 5;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_DEFINITION__LENGTH = 6;

  /**
   * The feature id for the '<em><b>Options</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_DEFINITION__OPTIONS = 7;

  /**
   * The number of structural features of the '<em>Field Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_DEFINITION_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionImpl <em>Option</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionImpl
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getOption()
   * @generated
   */
  int OPTION = 13;

  /**
   * The number of structural features of the '<em>Option</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionValprocImpl <em>Option Valproc</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionValprocImpl
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getOptionValproc()
   * @generated
   */
  int OPTION_VALPROC = 14;

  /**
   * The feature id for the '<em><b>Valproc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_VALPROC__VALPROC = OPTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Tcl Proc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_VALPROC__TCL_PROC = OPTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Option Valproc</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_VALPROC_FEATURE_COUNT = OPTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionStrictImpl <em>Option Strict</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionStrictImpl
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getOptionStrict()
   * @generated
   */
  int OPTION_STRICT = 15;

  /**
   * The feature id for the '<em><b>Strict</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_STRICT__STRICT = OPTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Option Strict</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_STRICT_FEATURE_COUNT = OPTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionRangeImpl <em>Option Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionRangeImpl
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getOptionRange()
   * @generated
   */
  int OPTION_RANGE = 16;

  /**
   * The feature id for the '<em><b>Min</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_RANGE__MIN = OPTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_RANGE__MAX = OPTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Option Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_RANGE_FEATURE_COUNT = OPTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionContribImpl <em>Option Contrib</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionContribImpl
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getOptionContrib()
   * @generated
   */
  int OPTION_CONTRIB = 17;

  /**
   * The feature id for the '<em><b>Contrib</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_CONTRIB__CONTRIB = OPTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Option Contrib</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_CONTRIB_FEATURE_COUNT = OPTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.FIELD_TYPE <em>FIELD TYPE</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.FIELD_TYPE
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getFIELD_TYPE()
   * @generated
   */
  int FIELD_TYPE = 18;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.ROLE <em>ROLE</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.ROLE
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getROLE()
   * @generated
   */
  int ROLE = 19;

  /**
   * The meta object id for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.RECORDCLASS <em>RECORDCLASS</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.RECORDCLASS
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getRECORDCLASS()
   * @generated
   */
  int RECORDCLASS = 20;


  /**
   * Returns the meta object for class '{@link ch.raiffeisen.ipricer.definition.definitionDSL.Definition <em>Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Definition</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.Definition
   * @generated
   */
  EClass getDefinition();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getMethodName <em>Method Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Method Name</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getMethodName()
   * @see #getDefinition()
   * @generated
   */
  EAttribute getDefinition_MethodName();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getGuiLabelMethod <em>Gui Label Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Gui Label Method</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getGuiLabelMethod()
   * @see #getDefinition()
   * @generated
   */
  EAttribute getDefinition_GuiLabelMethod();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getGuiLabelParent <em>Gui Label Parent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Gui Label Parent</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getGuiLabelParent()
   * @see #getDefinition()
   * @generated
   */
  EAttribute getDefinition_GuiLabelParent();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getGuiLabelChild <em>Gui Label Child</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Gui Label Child</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getGuiLabelChild()
   * @see #getDefinition()
   * @generated
   */
  EAttribute getDefinition_GuiLabelChild();

  /**
   * Returns the meta object for the containment reference '{@link ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getData <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Data</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getData()
   * @see #getDefinition()
   * @generated
   */
  EReference getDefinition_Data();

  /**
   * Returns the meta object for the containment reference '{@link ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getInitSection <em>Init Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Init Section</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getInitSection()
   * @see #getDefinition()
   * @generated
   */
  EReference getDefinition_InitSection();

  /**
   * Returns the meta object for the containment reference '{@link ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getTypeMaskSection <em>Type Mask Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type Mask Section</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getTypeMaskSection()
   * @see #getDefinition()
   * @generated
   */
  EReference getDefinition_TypeMaskSection();

  /**
   * Returns the meta object for the containment reference '{@link ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getUnderlyingListSection <em>Underlying List Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Underlying List Section</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getUnderlyingListSection()
   * @see #getDefinition()
   * @generated
   */
  EReference getDefinition_UnderlyingListSection();

  /**
   * Returns the meta object for the containment reference '{@link ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getUnderlyingMaskSection <em>Underlying Mask Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Underlying Mask Section</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getUnderlyingMaskSection()
   * @see #getDefinition()
   * @generated
   */
  EReference getDefinition_UnderlyingMaskSection();

  /**
   * Returns the meta object for the containment reference '{@link ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getOptionListSection <em>Option List Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Option List Section</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getOptionListSection()
   * @see #getDefinition()
   * @generated
   */
  EReference getDefinition_OptionListSection();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getOptionListLabelSection <em>Option List Label Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Option List Label Section</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getOptionListLabelSection()
   * @see #getDefinition()
   * @generated
   */
  EAttribute getDefinition_OptionListLabelSection();

  /**
   * Returns the meta object for the containment reference '{@link ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getOptionMaskSection <em>Option Mask Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Option Mask Section</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getOptionMaskSection()
   * @see #getDefinition()
   * @generated
   */
  EReference getDefinition_OptionMaskSection();

  /**
   * Returns the meta object for the attribute list '{@link ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getEventuellTclProcedures <em>Eventuell Tcl Procedures</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Eventuell Tcl Procedures</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.Definition#getEventuellTclProcedures()
   * @see #getDefinition()
   * @generated
   */
  EAttribute getDefinition_EventuellTclProcedures();

  /**
   * Returns the meta object for class '{@link ch.raiffeisen.ipricer.definition.definitionDSL.Data <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.Data
   * @generated
   */
  EClass getData();

  /**
   * Returns the meta object for the containment reference list '{@link ch.raiffeisen.ipricer.definition.definitionDSL.Data#getFieldDefinitions <em>Field Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Field Definitions</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.Data#getFieldDefinitions()
   * @see #getData()
   * @generated
   */
  EReference getData_FieldDefinitions();

  /**
   * Returns the meta object for class '{@link ch.raiffeisen.ipricer.definition.definitionDSL.InitSection <em>Init Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Init Section</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.InitSection
   * @generated
   */
  EClass getInitSection();

  /**
   * Returns the meta object for the containment reference list '{@link ch.raiffeisen.ipricer.definition.definitionDSL.InitSection#getInitDefinitions <em>Init Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Init Definitions</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.InitSection#getInitDefinitions()
   * @see #getInitSection()
   * @generated
   */
  EReference getInitSection_InitDefinitions();

  /**
   * Returns the meta object for class '{@link ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskSection <em>Type Mask Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Mask Section</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskSection
   * @generated
   */
  EClass getTypeMaskSection();

  /**
   * Returns the meta object for the containment reference list '{@link ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskSection#getTypeMaskDefinitions <em>Type Mask Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Type Mask Definitions</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskSection#getTypeMaskDefinitions()
   * @see #getTypeMaskSection()
   * @generated
   */
  EReference getTypeMaskSection_TypeMaskDefinitions();

  /**
   * Returns the meta object for class '{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingMaskSection <em>Underlying Mask Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Underlying Mask Section</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingMaskSection
   * @generated
   */
  EClass getUnderlyingMaskSection();

  /**
   * Returns the meta object for the containment reference list '{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingMaskSection#getUnderlyingMaskDefinitions <em>Underlying Mask Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Underlying Mask Definitions</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingMaskSection#getUnderlyingMaskDefinitions()
   * @see #getUnderlyingMaskSection()
   * @generated
   */
  EReference getUnderlyingMaskSection_UnderlyingMaskDefinitions();

  /**
   * Returns the meta object for class '{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListSection <em>Underlying List Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Underlying List Section</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListSection
   * @generated
   */
  EClass getUnderlyingListSection();

  /**
   * Returns the meta object for the containment reference list '{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListSection#getUnderlyingListDefinitions <em>Underlying List Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Underlying List Definitions</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListSection#getUnderlyingListDefinitions()
   * @see #getUnderlyingListSection()
   * @generated
   */
  EReference getUnderlyingListSection_UnderlyingListDefinitions();

  /**
   * Returns the meta object for class '{@link ch.raiffeisen.ipricer.definition.definitionDSL.OptionListSection <em>Option List Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Option List Section</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.OptionListSection
   * @generated
   */
  EClass getOptionListSection();

  /**
   * Returns the meta object for the containment reference list '{@link ch.raiffeisen.ipricer.definition.definitionDSL.OptionListSection#getOptionListDefinitions <em>Option List Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Option List Definitions</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.OptionListSection#getOptionListDefinitions()
   * @see #getOptionListSection()
   * @generated
   */
  EReference getOptionListSection_OptionListDefinitions();

  /**
   * Returns the meta object for class '{@link ch.raiffeisen.ipricer.definition.definitionDSL.OptionMaskSection <em>Option Mask Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Option Mask Section</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.OptionMaskSection
   * @generated
   */
  EClass getOptionMaskSection();

  /**
   * Returns the meta object for the containment reference list '{@link ch.raiffeisen.ipricer.definition.definitionDSL.OptionMaskSection#getOptionMaskDefinitions <em>Option Mask Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Option Mask Definitions</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.OptionMaskSection#getOptionMaskDefinitions()
   * @see #getOptionMaskSection()
   * @generated
   */
  EReference getOptionMaskSection_OptionMaskDefinitions();

  /**
   * Returns the meta object for class '{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListDefintion <em>Underlying List Defintion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Underlying List Defintion</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListDefintion
   * @generated
   */
  EClass getUnderlyingListDefintion();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListDefintion#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListDefintion#getId()
   * @see #getUnderlyingListDefintion()
   * @generated
   */
  EAttribute getUnderlyingListDefintion_Id();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListDefintion#getWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListDefintion#getWidth()
   * @see #getUnderlyingListDefintion()
   * @generated
   */
  EAttribute getUnderlyingListDefintion_Width();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListDefintion#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListDefintion#getTitle()
   * @see #getUnderlyingListDefintion()
   * @generated
   */
  EAttribute getUnderlyingListDefintion_Title();

  /**
   * Returns the meta object for class '{@link ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskDefinition <em>Type Mask Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Mask Definition</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskDefinition
   * @generated
   */
  EClass getTypeMaskDefinition();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskDefinition#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskDefinition#getId()
   * @see #getTypeMaskDefinition()
   * @generated
   */
  EAttribute getTypeMaskDefinition_Id();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskDefinition#getRow <em>Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Row</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskDefinition#getRow()
   * @see #getTypeMaskDefinition()
   * @generated
   */
  EAttribute getTypeMaskDefinition_Row();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskDefinition#getCol <em>Col</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Col</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskDefinition#getCol()
   * @see #getTypeMaskDefinition()
   * @generated
   */
  EAttribute getTypeMaskDefinition_Col();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskDefinition#getWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskDefinition#getWidth()
   * @see #getTypeMaskDefinition()
   * @generated
   */
  EAttribute getTypeMaskDefinition_Width();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskDefinition#getSeparator <em>Separator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Separator</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskDefinition#getSeparator()
   * @see #getTypeMaskDefinition()
   * @generated
   */
  EAttribute getTypeMaskDefinition_Separator();

  /**
   * Returns the meta object for class '{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingMaskDefinition <em>Underlying Mask Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Underlying Mask Definition</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingMaskDefinition
   * @generated
   */
  EClass getUnderlyingMaskDefinition();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingMaskDefinition#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingMaskDefinition#getId()
   * @see #getUnderlyingMaskDefinition()
   * @generated
   */
  EAttribute getUnderlyingMaskDefinition_Id();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingMaskDefinition#getRow <em>Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Row</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingMaskDefinition#getRow()
   * @see #getUnderlyingMaskDefinition()
   * @generated
   */
  EAttribute getUnderlyingMaskDefinition_Row();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingMaskDefinition#getCol <em>Col</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Col</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingMaskDefinition#getCol()
   * @see #getUnderlyingMaskDefinition()
   * @generated
   */
  EAttribute getUnderlyingMaskDefinition_Col();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingMaskDefinition#getWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingMaskDefinition#getWidth()
   * @see #getUnderlyingMaskDefinition()
   * @generated
   */
  EAttribute getUnderlyingMaskDefinition_Width();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingMaskDefinition#getSeparator <em>Separator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Separator</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingMaskDefinition#getSeparator()
   * @see #getUnderlyingMaskDefinition()
   * @generated
   */
  EAttribute getUnderlyingMaskDefinition_Separator();

  /**
   * Returns the meta object for class '{@link ch.raiffeisen.ipricer.definition.definitionDSL.InitDefinition <em>Init Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Init Definition</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.InitDefinition
   * @generated
   */
  EClass getInitDefinition();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.InitDefinition#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.InitDefinition#getId()
   * @see #getInitDefinition()
   * @generated
   */
  EAttribute getInitDefinition_Id();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.InitDefinition#getInitValue <em>Init Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Init Value</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.InitDefinition#getInitValue()
   * @see #getInitDefinition()
   * @generated
   */
  EAttribute getInitDefinition_InitValue();

  /**
   * Returns the meta object for class '{@link ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition <em>Field Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Field Definition</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition
   * @generated
   */
  EClass getFieldDefinition();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition#getFieldType <em>Field Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Field Type</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition#getFieldType()
   * @see #getFieldDefinition()
   * @generated
   */
  EAttribute getFieldDefinition_FieldType();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition#getId()
   * @see #getFieldDefinition()
   * @generated
   */
  EAttribute getFieldDefinition_Id();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition#getName()
   * @see #getFieldDefinition()
   * @generated
   */
  EAttribute getFieldDefinition_Name();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition#getAccess <em>Access</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Access</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition#getAccess()
   * @see #getFieldDefinition()
   * @generated
   */
  EAttribute getFieldDefinition_Access();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition#getRecordClass <em>Record Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Record Class</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition#getRecordClass()
   * @see #getFieldDefinition()
   * @generated
   */
  EAttribute getFieldDefinition_RecordClass();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition#getFieldName <em>Field Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Field Name</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition#getFieldName()
   * @see #getFieldDefinition()
   * @generated
   */
  EAttribute getFieldDefinition_FieldName();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition#getLength()
   * @see #getFieldDefinition()
   * @generated
   */
  EAttribute getFieldDefinition_Length();

  /**
   * Returns the meta object for the containment reference list '{@link ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition#getOptions <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Options</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition#getOptions()
   * @see #getFieldDefinition()
   * @generated
   */
  EReference getFieldDefinition_Options();

  /**
   * Returns the meta object for class '{@link ch.raiffeisen.ipricer.definition.definitionDSL.Option <em>Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Option</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.Option
   * @generated
   */
  EClass getOption();

  /**
   * Returns the meta object for class '{@link ch.raiffeisen.ipricer.definition.definitionDSL.OptionValproc <em>Option Valproc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Option Valproc</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.OptionValproc
   * @generated
   */
  EClass getOptionValproc();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.OptionValproc#getValproc <em>Valproc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Valproc</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.OptionValproc#getValproc()
   * @see #getOptionValproc()
   * @generated
   */
  EAttribute getOptionValproc_Valproc();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.OptionValproc#getTclProc <em>Tcl Proc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tcl Proc</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.OptionValproc#getTclProc()
   * @see #getOptionValproc()
   * @generated
   */
  EAttribute getOptionValproc_TclProc();

  /**
   * Returns the meta object for class '{@link ch.raiffeisen.ipricer.definition.definitionDSL.OptionStrict <em>Option Strict</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Option Strict</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.OptionStrict
   * @generated
   */
  EClass getOptionStrict();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.OptionStrict#isStrict <em>Strict</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Strict</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.OptionStrict#isStrict()
   * @see #getOptionStrict()
   * @generated
   */
  EAttribute getOptionStrict_Strict();

  /**
   * Returns the meta object for class '{@link ch.raiffeisen.ipricer.definition.definitionDSL.OptionRange <em>Option Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Option Range</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.OptionRange
   * @generated
   */
  EClass getOptionRange();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.OptionRange#getMin <em>Min</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Min</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.OptionRange#getMin()
   * @see #getOptionRange()
   * @generated
   */
  EAttribute getOptionRange_Min();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.OptionRange#getMax <em>Max</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.OptionRange#getMax()
   * @see #getOptionRange()
   * @generated
   */
  EAttribute getOptionRange_Max();

  /**
   * Returns the meta object for class '{@link ch.raiffeisen.ipricer.definition.definitionDSL.OptionContrib <em>Option Contrib</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Option Contrib</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.OptionContrib
   * @generated
   */
  EClass getOptionContrib();

  /**
   * Returns the meta object for the attribute '{@link ch.raiffeisen.ipricer.definition.definitionDSL.OptionContrib#isContrib <em>Contrib</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Contrib</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.OptionContrib#isContrib()
   * @see #getOptionContrib()
   * @generated
   */
  EAttribute getOptionContrib_Contrib();

  /**
   * Returns the meta object for enum '{@link ch.raiffeisen.ipricer.definition.definitionDSL.FIELD_TYPE <em>FIELD TYPE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>FIELD TYPE</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.FIELD_TYPE
   * @generated
   */
  EEnum getFIELD_TYPE();

  /**
   * Returns the meta object for enum '{@link ch.raiffeisen.ipricer.definition.definitionDSL.ROLE <em>ROLE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>ROLE</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.ROLE
   * @generated
   */
  EEnum getROLE();

  /**
   * Returns the meta object for enum '{@link ch.raiffeisen.ipricer.definition.definitionDSL.RECORDCLASS <em>RECORDCLASS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>RECORDCLASS</em>'.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.RECORDCLASS
   * @generated
   */
  EEnum getRECORDCLASS();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DefinitionDSLFactory getDefinitionDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionImpl <em>Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionImpl
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getDefinition()
     * @generated
     */
    EClass DEFINITION = eINSTANCE.getDefinition();

    /**
     * The meta object literal for the '<em><b>Method Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINITION__METHOD_NAME = eINSTANCE.getDefinition_MethodName();

    /**
     * The meta object literal for the '<em><b>Gui Label Method</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINITION__GUI_LABEL_METHOD = eINSTANCE.getDefinition_GuiLabelMethod();

    /**
     * The meta object literal for the '<em><b>Gui Label Parent</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINITION__GUI_LABEL_PARENT = eINSTANCE.getDefinition_GuiLabelParent();

    /**
     * The meta object literal for the '<em><b>Gui Label Child</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINITION__GUI_LABEL_CHILD = eINSTANCE.getDefinition_GuiLabelChild();

    /**
     * The meta object literal for the '<em><b>Data</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__DATA = eINSTANCE.getDefinition_Data();

    /**
     * The meta object literal for the '<em><b>Init Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__INIT_SECTION = eINSTANCE.getDefinition_InitSection();

    /**
     * The meta object literal for the '<em><b>Type Mask Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__TYPE_MASK_SECTION = eINSTANCE.getDefinition_TypeMaskSection();

    /**
     * The meta object literal for the '<em><b>Underlying List Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__UNDERLYING_LIST_SECTION = eINSTANCE.getDefinition_UnderlyingListSection();

    /**
     * The meta object literal for the '<em><b>Underlying Mask Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__UNDERLYING_MASK_SECTION = eINSTANCE.getDefinition_UnderlyingMaskSection();

    /**
     * The meta object literal for the '<em><b>Option List Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__OPTION_LIST_SECTION = eINSTANCE.getDefinition_OptionListSection();

    /**
     * The meta object literal for the '<em><b>Option List Label Section</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINITION__OPTION_LIST_LABEL_SECTION = eINSTANCE.getDefinition_OptionListLabelSection();

    /**
     * The meta object literal for the '<em><b>Option Mask Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__OPTION_MASK_SECTION = eINSTANCE.getDefinition_OptionMaskSection();

    /**
     * The meta object literal for the '<em><b>Eventuell Tcl Procedures</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINITION__EVENTUELL_TCL_PROCEDURES = eINSTANCE.getDefinition_EventuellTclProcedures();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.DataImpl <em>Data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DataImpl
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getData()
     * @generated
     */
    EClass DATA = eINSTANCE.getData();

    /**
     * The meta object literal for the '<em><b>Field Definitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA__FIELD_DEFINITIONS = eINSTANCE.getData_FieldDefinitions();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.InitSectionImpl <em>Init Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.InitSectionImpl
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getInitSection()
     * @generated
     */
    EClass INIT_SECTION = eINSTANCE.getInitSection();

    /**
     * The meta object literal for the '<em><b>Init Definitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INIT_SECTION__INIT_DEFINITIONS = eINSTANCE.getInitSection_InitDefinitions();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.TypeMaskSectionImpl <em>Type Mask Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.TypeMaskSectionImpl
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getTypeMaskSection()
     * @generated
     */
    EClass TYPE_MASK_SECTION = eINSTANCE.getTypeMaskSection();

    /**
     * The meta object literal for the '<em><b>Type Mask Definitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE_MASK_SECTION__TYPE_MASK_DEFINITIONS = eINSTANCE.getTypeMaskSection_TypeMaskDefinitions();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.UnderlyingMaskSectionImpl <em>Underlying Mask Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.UnderlyingMaskSectionImpl
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getUnderlyingMaskSection()
     * @generated
     */
    EClass UNDERLYING_MASK_SECTION = eINSTANCE.getUnderlyingMaskSection();

    /**
     * The meta object literal for the '<em><b>Underlying Mask Definitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNDERLYING_MASK_SECTION__UNDERLYING_MASK_DEFINITIONS = eINSTANCE.getUnderlyingMaskSection_UnderlyingMaskDefinitions();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.UnderlyingListSectionImpl <em>Underlying List Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.UnderlyingListSectionImpl
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getUnderlyingListSection()
     * @generated
     */
    EClass UNDERLYING_LIST_SECTION = eINSTANCE.getUnderlyingListSection();

    /**
     * The meta object literal for the '<em><b>Underlying List Definitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNDERLYING_LIST_SECTION__UNDERLYING_LIST_DEFINITIONS = eINSTANCE.getUnderlyingListSection_UnderlyingListDefinitions();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionListSectionImpl <em>Option List Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionListSectionImpl
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getOptionListSection()
     * @generated
     */
    EClass OPTION_LIST_SECTION = eINSTANCE.getOptionListSection();

    /**
     * The meta object literal for the '<em><b>Option List Definitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPTION_LIST_SECTION__OPTION_LIST_DEFINITIONS = eINSTANCE.getOptionListSection_OptionListDefinitions();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionMaskSectionImpl <em>Option Mask Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionMaskSectionImpl
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getOptionMaskSection()
     * @generated
     */
    EClass OPTION_MASK_SECTION = eINSTANCE.getOptionMaskSection();

    /**
     * The meta object literal for the '<em><b>Option Mask Definitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPTION_MASK_SECTION__OPTION_MASK_DEFINITIONS = eINSTANCE.getOptionMaskSection_OptionMaskDefinitions();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.UnderlyingListDefintionImpl <em>Underlying List Defintion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.UnderlyingListDefintionImpl
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getUnderlyingListDefintion()
     * @generated
     */
    EClass UNDERLYING_LIST_DEFINTION = eINSTANCE.getUnderlyingListDefintion();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNDERLYING_LIST_DEFINTION__ID = eINSTANCE.getUnderlyingListDefintion_Id();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNDERLYING_LIST_DEFINTION__WIDTH = eINSTANCE.getUnderlyingListDefintion_Width();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNDERLYING_LIST_DEFINTION__TITLE = eINSTANCE.getUnderlyingListDefintion_Title();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.TypeMaskDefinitionImpl <em>Type Mask Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.TypeMaskDefinitionImpl
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getTypeMaskDefinition()
     * @generated
     */
    EClass TYPE_MASK_DEFINITION = eINSTANCE.getTypeMaskDefinition();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_MASK_DEFINITION__ID = eINSTANCE.getTypeMaskDefinition_Id();

    /**
     * The meta object literal for the '<em><b>Row</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_MASK_DEFINITION__ROW = eINSTANCE.getTypeMaskDefinition_Row();

    /**
     * The meta object literal for the '<em><b>Col</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_MASK_DEFINITION__COL = eINSTANCE.getTypeMaskDefinition_Col();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_MASK_DEFINITION__WIDTH = eINSTANCE.getTypeMaskDefinition_Width();

    /**
     * The meta object literal for the '<em><b>Separator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_MASK_DEFINITION__SEPARATOR = eINSTANCE.getTypeMaskDefinition_Separator();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.UnderlyingMaskDefinitionImpl <em>Underlying Mask Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.UnderlyingMaskDefinitionImpl
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getUnderlyingMaskDefinition()
     * @generated
     */
    EClass UNDERLYING_MASK_DEFINITION = eINSTANCE.getUnderlyingMaskDefinition();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNDERLYING_MASK_DEFINITION__ID = eINSTANCE.getUnderlyingMaskDefinition_Id();

    /**
     * The meta object literal for the '<em><b>Row</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNDERLYING_MASK_DEFINITION__ROW = eINSTANCE.getUnderlyingMaskDefinition_Row();

    /**
     * The meta object literal for the '<em><b>Col</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNDERLYING_MASK_DEFINITION__COL = eINSTANCE.getUnderlyingMaskDefinition_Col();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNDERLYING_MASK_DEFINITION__WIDTH = eINSTANCE.getUnderlyingMaskDefinition_Width();

    /**
     * The meta object literal for the '<em><b>Separator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNDERLYING_MASK_DEFINITION__SEPARATOR = eINSTANCE.getUnderlyingMaskDefinition_Separator();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.InitDefinitionImpl <em>Init Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.InitDefinitionImpl
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getInitDefinition()
     * @generated
     */
    EClass INIT_DEFINITION = eINSTANCE.getInitDefinition();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INIT_DEFINITION__ID = eINSTANCE.getInitDefinition_Id();

    /**
     * The meta object literal for the '<em><b>Init Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INIT_DEFINITION__INIT_VALUE = eINSTANCE.getInitDefinition_InitValue();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.FieldDefinitionImpl <em>Field Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.FieldDefinitionImpl
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getFieldDefinition()
     * @generated
     */
    EClass FIELD_DEFINITION = eINSTANCE.getFieldDefinition();

    /**
     * The meta object literal for the '<em><b>Field Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD_DEFINITION__FIELD_TYPE = eINSTANCE.getFieldDefinition_FieldType();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD_DEFINITION__ID = eINSTANCE.getFieldDefinition_Id();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD_DEFINITION__NAME = eINSTANCE.getFieldDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Access</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD_DEFINITION__ACCESS = eINSTANCE.getFieldDefinition_Access();

    /**
     * The meta object literal for the '<em><b>Record Class</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD_DEFINITION__RECORD_CLASS = eINSTANCE.getFieldDefinition_RecordClass();

    /**
     * The meta object literal for the '<em><b>Field Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD_DEFINITION__FIELD_NAME = eINSTANCE.getFieldDefinition_FieldName();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD_DEFINITION__LENGTH = eINSTANCE.getFieldDefinition_Length();

    /**
     * The meta object literal for the '<em><b>Options</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD_DEFINITION__OPTIONS = eINSTANCE.getFieldDefinition_Options();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionImpl <em>Option</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionImpl
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getOption()
     * @generated
     */
    EClass OPTION = eINSTANCE.getOption();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionValprocImpl <em>Option Valproc</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionValprocImpl
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getOptionValproc()
     * @generated
     */
    EClass OPTION_VALPROC = eINSTANCE.getOptionValproc();

    /**
     * The meta object literal for the '<em><b>Valproc</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTION_VALPROC__VALPROC = eINSTANCE.getOptionValproc_Valproc();

    /**
     * The meta object literal for the '<em><b>Tcl Proc</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTION_VALPROC__TCL_PROC = eINSTANCE.getOptionValproc_TclProc();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionStrictImpl <em>Option Strict</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionStrictImpl
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getOptionStrict()
     * @generated
     */
    EClass OPTION_STRICT = eINSTANCE.getOptionStrict();

    /**
     * The meta object literal for the '<em><b>Strict</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTION_STRICT__STRICT = eINSTANCE.getOptionStrict_Strict();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionRangeImpl <em>Option Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionRangeImpl
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getOptionRange()
     * @generated
     */
    EClass OPTION_RANGE = eINSTANCE.getOptionRange();

    /**
     * The meta object literal for the '<em><b>Min</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTION_RANGE__MIN = eINSTANCE.getOptionRange_Min();

    /**
     * The meta object literal for the '<em><b>Max</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTION_RANGE__MAX = eINSTANCE.getOptionRange_Max();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionContribImpl <em>Option Contrib</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.OptionContribImpl
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getOptionContrib()
     * @generated
     */
    EClass OPTION_CONTRIB = eINSTANCE.getOptionContrib();

    /**
     * The meta object literal for the '<em><b>Contrib</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTION_CONTRIB__CONTRIB = eINSTANCE.getOptionContrib_Contrib();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.FIELD_TYPE <em>FIELD TYPE</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.FIELD_TYPE
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getFIELD_TYPE()
     * @generated
     */
    EEnum FIELD_TYPE = eINSTANCE.getFIELD_TYPE();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.ROLE <em>ROLE</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.ROLE
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getROLE()
     * @generated
     */
    EEnum ROLE = eINSTANCE.getROLE();

    /**
     * The meta object literal for the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.RECORDCLASS <em>RECORDCLASS</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.RECORDCLASS
     * @see ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLPackageImpl#getRECORDCLASS()
     * @generated
     */
    EEnum RECORDCLASS = eINSTANCE.getRECORDCLASS();

  }

} //DefinitionDSLPackage
