/**
 * generated by Xtext 2.9.2
 */
package ch.raiffeisen.ipricer.definition.definitionDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see ch.raiffeisen.ipricer.definition.definitionDSL.DefinitionDSLPackage
 * @generated
 */
public interface DefinitionDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DefinitionDSLFactory eINSTANCE = ch.raiffeisen.ipricer.definition.definitionDSL.impl.DefinitionDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Definition</em>'.
   * @generated
   */
  Definition createDefinition();

  /**
   * Returns a new object of class '<em>Data</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data</em>'.
   * @generated
   */
  Data createData();

  /**
   * Returns a new object of class '<em>Init Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Init Section</em>'.
   * @generated
   */
  InitSection createInitSection();

  /**
   * Returns a new object of class '<em>Type Mask Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type Mask Section</em>'.
   * @generated
   */
  TypeMaskSection createTypeMaskSection();

  /**
   * Returns a new object of class '<em>Underlying Mask Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Underlying Mask Section</em>'.
   * @generated
   */
  UnderlyingMaskSection createUnderlyingMaskSection();

  /**
   * Returns a new object of class '<em>Underlying List Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Underlying List Section</em>'.
   * @generated
   */
  UnderlyingListSection createUnderlyingListSection();

  /**
   * Returns a new object of class '<em>Option List Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Option List Section</em>'.
   * @generated
   */
  OptionListSection createOptionListSection();

  /**
   * Returns a new object of class '<em>Option Mask Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Option Mask Section</em>'.
   * @generated
   */
  OptionMaskSection createOptionMaskSection();

  /**
   * Returns a new object of class '<em>Underlying List Defintion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Underlying List Defintion</em>'.
   * @generated
   */
  UnderlyingListDefintion createUnderlyingListDefintion();

  /**
   * Returns a new object of class '<em>Type Mask Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type Mask Definition</em>'.
   * @generated
   */
  TypeMaskDefinition createTypeMaskDefinition();

  /**
   * Returns a new object of class '<em>Underlying Mask Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Underlying Mask Definition</em>'.
   * @generated
   */
  UnderlyingMaskDefinition createUnderlyingMaskDefinition();

  /**
   * Returns a new object of class '<em>Init Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Init Definition</em>'.
   * @generated
   */
  InitDefinition createInitDefinition();

  /**
   * Returns a new object of class '<em>Field Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Field Definition</em>'.
   * @generated
   */
  FieldDefinition createFieldDefinition();

  /**
   * Returns a new object of class '<em>Option</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Option</em>'.
   * @generated
   */
  Option createOption();

  /**
   * Returns a new object of class '<em>Option Valproc</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Option Valproc</em>'.
   * @generated
   */
  OptionValproc createOptionValproc();

  /**
   * Returns a new object of class '<em>Option Strict</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Option Strict</em>'.
   * @generated
   */
  OptionStrict createOptionStrict();

  /**
   * Returns a new object of class '<em>Option Range</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Option Range</em>'.
   * @generated
   */
  OptionRange createOptionRange();

  /**
   * Returns a new object of class '<em>Option Contrib</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Option Contrib</em>'.
   * @generated
   */
  OptionContrib createOptionContrib();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  DefinitionDSLPackage getDefinitionDSLPackage();

} //DefinitionDSLFactory
