/**
 * generated by Xtext 2.9.2
 */
package ch.raiffeisen.ipricer.definition.definitionDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Option Mask Section</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ch.raiffeisen.ipricer.definition.definitionDSL.OptionMaskSection#getOptionMaskDefinitions <em>Option Mask Definitions</em>}</li>
 * </ul>
 *
 * @see ch.raiffeisen.ipricer.definition.definitionDSL.DefinitionDSLPackage#getOptionMaskSection()
 * @model
 * @generated
 */
public interface OptionMaskSection extends EObject
{
  /**
   * Returns the value of the '<em><b>Option Mask Definitions</b></em>' containment reference list.
   * The list contents are of type {@link ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskDefinition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Option Mask Definitions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Option Mask Definitions</em>' containment reference list.
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.DefinitionDSLPackage#getOptionMaskSection_OptionMaskDefinitions()
   * @model containment="true"
   * @generated
   */
  EList<TypeMaskDefinition> getOptionMaskDefinitions();

} // OptionMaskSection
