/**
 * generated by Xtext 2.9.2
 */
package ch.raiffeisen.ipricer.definition.definitionDSL;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>RECORDCLASS</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see ch.raiffeisen.ipricer.definition.definitionDSL.DefinitionDSLPackage#getRECORDCLASS()
 * @model
 * @generated
 */
public enum RECORDCLASS implements Enumerator
{
  /**
   * The '<em><b>METHOD READ ONLY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #METHOD_READ_ONLY_VALUE
   * @generated
   * @ordered
   */
  METHOD_READ_ONLY(0, "METHOD_READ_ONLY", "B"),

  /**
   * The '<em><b>PARENT READ ONLY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PARENT_READ_ONLY_VALUE
   * @generated
   * @ordered
   */
  PARENT_READ_ONLY(1, "PARENT_READ_ONLY", "U"),

  /**
   * The '<em><b>PARENT READ WRITE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PARENT_READ_WRITE_VALUE
   * @generated
   * @ordered
   */
  PARENT_READ_WRITE(2, "PARENT_READ_WRITE", "G"),

  /**
   * The '<em><b>PARENT READ REFERENCE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PARENT_READ_REFERENCE_VALUE
   * @generated
   * @ordered
   */
  PARENT_READ_REFERENCE(3, "PARENT_READ_REFERENCE", "R"),

  /**
   * The '<em><b>CHILD READ ONLY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CHILD_READ_ONLY_VALUE
   * @generated
   * @ordered
   */
  CHILD_READ_ONLY(4, "CHILD_READ_ONLY", "D"),

  /**
   * The '<em><b>CHILD READ WRITE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CHILD_READ_WRITE_VALUE
   * @generated
   * @ordered
   */
  CHILD_READ_WRITE(5, "CHILD_READ_WRITE", "P"),

  /**
   * The '<em><b>CHILD READ REFERENCE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CHILD_READ_REFERENCE_VALUE
   * @generated
   * @ordered
   */
  CHILD_READ_REFERENCE(6, "CHILD_READ_REFERENCE", "S");

  /**
   * The '<em><b>METHOD READ ONLY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>METHOD READ ONLY</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #METHOD_READ_ONLY
   * @model literal="B"
   * @generated
   * @ordered
   */
  public static final int METHOD_READ_ONLY_VALUE = 0;

  /**
   * The '<em><b>PARENT READ ONLY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>PARENT READ ONLY</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PARENT_READ_ONLY
   * @model literal="U"
   * @generated
   * @ordered
   */
  public static final int PARENT_READ_ONLY_VALUE = 1;

  /**
   * The '<em><b>PARENT READ WRITE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>PARENT READ WRITE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PARENT_READ_WRITE
   * @model literal="G"
   * @generated
   * @ordered
   */
  public static final int PARENT_READ_WRITE_VALUE = 2;

  /**
   * The '<em><b>PARENT READ REFERENCE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>PARENT READ REFERENCE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PARENT_READ_REFERENCE
   * @model literal="R"
   * @generated
   * @ordered
   */
  public static final int PARENT_READ_REFERENCE_VALUE = 3;

  /**
   * The '<em><b>CHILD READ ONLY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>CHILD READ ONLY</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CHILD_READ_ONLY
   * @model literal="D"
   * @generated
   * @ordered
   */
  public static final int CHILD_READ_ONLY_VALUE = 4;

  /**
   * The '<em><b>CHILD READ WRITE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>CHILD READ WRITE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CHILD_READ_WRITE
   * @model literal="P"
   * @generated
   * @ordered
   */
  public static final int CHILD_READ_WRITE_VALUE = 5;

  /**
   * The '<em><b>CHILD READ REFERENCE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>CHILD READ REFERENCE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CHILD_READ_REFERENCE
   * @model literal="S"
   * @generated
   * @ordered
   */
  public static final int CHILD_READ_REFERENCE_VALUE = 6;

  /**
   * An array of all the '<em><b>RECORDCLASS</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final RECORDCLASS[] VALUES_ARRAY =
    new RECORDCLASS[]
    {
      METHOD_READ_ONLY,
      PARENT_READ_ONLY,
      PARENT_READ_WRITE,
      PARENT_READ_REFERENCE,
      CHILD_READ_ONLY,
      CHILD_READ_WRITE,
      CHILD_READ_REFERENCE,
    };

  /**
   * A public read-only list of all the '<em><b>RECORDCLASS</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<RECORDCLASS> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>RECORDCLASS</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static RECORDCLASS get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      RECORDCLASS result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>RECORDCLASS</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static RECORDCLASS getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      RECORDCLASS result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>RECORDCLASS</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static RECORDCLASS get(int value)
  {
    switch (value)
    {
      case METHOD_READ_ONLY_VALUE: return METHOD_READ_ONLY;
      case PARENT_READ_ONLY_VALUE: return PARENT_READ_ONLY;
      case PARENT_READ_WRITE_VALUE: return PARENT_READ_WRITE;
      case PARENT_READ_REFERENCE_VALUE: return PARENT_READ_REFERENCE;
      case CHILD_READ_ONLY_VALUE: return CHILD_READ_ONLY;
      case CHILD_READ_WRITE_VALUE: return CHILD_READ_WRITE;
      case CHILD_READ_REFERENCE_VALUE: return CHILD_READ_REFERENCE;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private RECORDCLASS(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //RECORDCLASS
