/**
 * generated by Xtext 2.9.2
 */
package ch.raiffeisen.ipricer.definition.definitionDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Underlying List Defintion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListDefintion#getId <em>Id</em>}</li>
 *   <li>{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListDefintion#getWidth <em>Width</em>}</li>
 *   <li>{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListDefintion#getTitle <em>Title</em>}</li>
 * </ul>
 *
 * @see ch.raiffeisen.ipricer.definition.definitionDSL.DefinitionDSLPackage#getUnderlyingListDefintion()
 * @model
 * @generated
 */
public interface UnderlyingListDefintion extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.DefinitionDSLPackage#getUnderlyingListDefintion_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListDefintion#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Width</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Width</em>' attribute.
   * @see #setWidth(int)
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.DefinitionDSLPackage#getUnderlyingListDefintion_Width()
   * @model
   * @generated
   */
  int getWidth();

  /**
   * Sets the value of the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListDefintion#getWidth <em>Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Width</em>' attribute.
   * @see #getWidth()
   * @generated
   */
  void setWidth(int value);

  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Title</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.DefinitionDSLPackage#getUnderlyingListDefintion_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListDefintion#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

} // UnderlyingListDefintion
