/*
 * generated by Xtext 2.9.2
 */
package ch.raiffeisen.ipricer.definition.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class DefinitionDSLLanguage extends AbstractXtextLanguage {

	public static final DefinitionDSLLanguage INSTANCE = new DefinitionDSLLanguage();

	private DefinitionDSLLanguage() {
		super("ch.raiffeisen.ipricer.definition.DefinitionDSL");
	}

}
