/*
 * generated by Xtext 2.9.2
 */
package ch.raiffeisen.ipricer.definition.idea.lang;

import ch.raiffeisen.ipricer.definition.idea.lang.psi.impl.DefinitionDSLFileImpl;
import ch.raiffeisen.ipricer.definition.services.DefinitionDSLGrammarAccess;
import com.intellij.psi.tree.IFileElementType;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.idea.lang.IElementTypeProvider;
import org.eclipse.xtext.psi.stubs.XtextFileElementType;
import org.eclipse.xtext.psi.stubs.XtextFileStub;
import org.eclipse.xtext.psi.tree.IGrammarAwareElementType;

public class DefinitionDSLElementTypeProvider implements IElementTypeProvider {

	public static final IFileElementType FILE_TYPE = new XtextFileElementType<XtextFileStub<DefinitionDSLFileImpl>>(DefinitionDSLLanguage.INSTANCE);

	private static final Map<EObject, IGrammarAwareElementType> GRAMMAR_ELEMENT_TYPE = new HashMap<EObject, IGrammarAwareElementType>();

	private static IGrammarAwareElementType associate(IGrammarAwareElementType grammarAwareElementType) {
		GRAMMAR_ELEMENT_TYPE.put(grammarAwareElementType.getGrammarElement(), grammarAwareElementType);
		return grammarAwareElementType;
	}

	private static final DefinitionDSLGrammarAccess GRAMMAR_ACCESS = DefinitionDSLLanguage.INSTANCE.getInstance(DefinitionDSLGrammarAccess.class);

	private static class DefinitionFactory {
		public static IGrammarAwareElementType createDefinitionElementType() {
			return new IGrammarAwareElementType("Definition_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionRule());
		}
		public static IGrammarAwareElementType createDefinition_GroupElementType() {
			return new IGrammarAwareElementType("Definition_Group_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getGroup());
		}
		public static IGrammarAwareElementType createDefinition_DefinitionKeyword_0ElementType() {
			return new IGrammarAwareElementType("Definition_DefinitionKeyword_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getDefinitionKeyword_0());
		}
		public static IGrammarAwareElementType createDefinition_MethodNameAssignment_1ElementType() {
			return new IGrammarAwareElementType("Definition_MethodNameAssignment_1_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getMethodNameAssignment_1());
		}
		public static IGrammarAwareElementType createDefinition_MethodNameIDTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("Definition_MethodNameIDTerminalRuleCall_1_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getMethodNameIDTerminalRuleCall_1_0());
		}
		public static IGrammarAwareElementType createDefinition_GuiLabelMethodAssignment_2ElementType() {
			return new IGrammarAwareElementType("Definition_GuiLabelMethodAssignment_2_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getGuiLabelMethodAssignment_2());
		}
		public static IGrammarAwareElementType createDefinition_GuiLabelMethodSTRINGTerminalRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("Definition_GuiLabelMethodSTRINGTerminalRuleCall_2_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getGuiLabelMethodSTRINGTerminalRuleCall_2_0());
		}
		public static IGrammarAwareElementType createDefinition_GuiLabelParentAssignment_3ElementType() {
			return new IGrammarAwareElementType("Definition_GuiLabelParentAssignment_3_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getGuiLabelParentAssignment_3());
		}
		public static IGrammarAwareElementType createDefinition_GuiLabelParentSTRINGTerminalRuleCall_3_0ElementType() {
			return new IGrammarAwareElementType("Definition_GuiLabelParentSTRINGTerminalRuleCall_3_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getGuiLabelParentSTRINGTerminalRuleCall_3_0());
		}
		public static IGrammarAwareElementType createDefinition_GuiLabelChildAssignment_4ElementType() {
			return new IGrammarAwareElementType("Definition_GuiLabelChildAssignment_4_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getGuiLabelChildAssignment_4());
		}
		public static IGrammarAwareElementType createDefinition_GuiLabelChildSTRINGTerminalRuleCall_4_0ElementType() {
			return new IGrammarAwareElementType("Definition_GuiLabelChildSTRINGTerminalRuleCall_4_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getGuiLabelChildSTRINGTerminalRuleCall_4_0());
		}
		public static IGrammarAwareElementType createDefinition_LeftCurlyBracketKeyword_5ElementType() {
			return new IGrammarAwareElementType("Definition_LeftCurlyBracketKeyword_5_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getLeftCurlyBracketKeyword_5());
		}
		public static IGrammarAwareElementType createDefinition_DataAssignment_6ElementType() {
			return new IGrammarAwareElementType("Definition_DataAssignment_6_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getDataAssignment_6());
		}
		public static IGrammarAwareElementType createDefinition_DataDataParserRuleCall_6_0ElementType() {
			return new IGrammarAwareElementType("Definition_DataDataParserRuleCall_6_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getDataDataParserRuleCall_6_0());
		}
		public static IGrammarAwareElementType createDefinition_InitSectionAssignment_7ElementType() {
			return new IGrammarAwareElementType("Definition_InitSectionAssignment_7_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getInitSectionAssignment_7());
		}
		public static IGrammarAwareElementType createDefinition_InitSectionInitSectionParserRuleCall_7_0ElementType() {
			return new IGrammarAwareElementType("Definition_InitSectionInitSectionParserRuleCall_7_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getInitSectionInitSectionParserRuleCall_7_0());
		}
		public static IGrammarAwareElementType createDefinition_RightCurlyBracketKeyword_8ElementType() {
			return new IGrammarAwareElementType("Definition_RightCurlyBracketKeyword_8_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getRightCurlyBracketKeyword_8());
		}
		public static IGrammarAwareElementType createDefinition_EventuellTclProceduresAssignment_9ElementType() {
			return new IGrammarAwareElementType("Definition_EventuellTclProceduresAssignment_9_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getEventuellTclProceduresAssignment_9());
		}
		public static IGrammarAwareElementType createDefinition_EventuellTclProceduresAlternatives_9_0ElementType() {
			return new IGrammarAwareElementType("Definition_EventuellTclProceduresAlternatives_9_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getEventuellTclProceduresAlternatives_9_0());
		}
		public static IGrammarAwareElementType createDefinition_EventuellTclProceduresIDTerminalRuleCall_9_0_0ElementType() {
			return new IGrammarAwareElementType("Definition_EventuellTclProceduresIDTerminalRuleCall_9_0_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getEventuellTclProceduresIDTerminalRuleCall_9_0_0());
		}
		public static IGrammarAwareElementType createDefinition_EventuellTclProceduresANY_OTHERTerminalRuleCall_9_0_1ElementType() {
			return new IGrammarAwareElementType("Definition_EventuellTclProceduresANY_OTHERTerminalRuleCall_9_0_1_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDefinitionAccess().getEventuellTclProceduresANY_OTHERTerminalRuleCall_9_0_1());
		}
	}

	public static final IGrammarAwareElementType Definition_ELEMENT_TYPE = associate(DefinitionFactory.createDefinitionElementType());

	public static final IGrammarAwareElementType Definition_Group_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_GroupElementType());

	public static final IGrammarAwareElementType Definition_DefinitionKeyword_0_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_DefinitionKeyword_0ElementType());

	public static final IGrammarAwareElementType Definition_MethodNameAssignment_1_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_MethodNameAssignment_1ElementType());

	public static final IGrammarAwareElementType Definition_MethodNameIDTerminalRuleCall_1_0_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_MethodNameIDTerminalRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType Definition_GuiLabelMethodAssignment_2_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_GuiLabelMethodAssignment_2ElementType());

	public static final IGrammarAwareElementType Definition_GuiLabelMethodSTRINGTerminalRuleCall_2_0_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_GuiLabelMethodSTRINGTerminalRuleCall_2_0ElementType());

	public static final IGrammarAwareElementType Definition_GuiLabelParentAssignment_3_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_GuiLabelParentAssignment_3ElementType());

	public static final IGrammarAwareElementType Definition_GuiLabelParentSTRINGTerminalRuleCall_3_0_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_GuiLabelParentSTRINGTerminalRuleCall_3_0ElementType());

	public static final IGrammarAwareElementType Definition_GuiLabelChildAssignment_4_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_GuiLabelChildAssignment_4ElementType());

	public static final IGrammarAwareElementType Definition_GuiLabelChildSTRINGTerminalRuleCall_4_0_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_GuiLabelChildSTRINGTerminalRuleCall_4_0ElementType());

	public static final IGrammarAwareElementType Definition_LeftCurlyBracketKeyword_5_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_LeftCurlyBracketKeyword_5ElementType());

	public static final IGrammarAwareElementType Definition_DataAssignment_6_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_DataAssignment_6ElementType());

	public static final IGrammarAwareElementType Definition_DataDataParserRuleCall_6_0_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_DataDataParserRuleCall_6_0ElementType());

	public static final IGrammarAwareElementType Definition_InitSectionAssignment_7_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_InitSectionAssignment_7ElementType());

	public static final IGrammarAwareElementType Definition_InitSectionInitSectionParserRuleCall_7_0_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_InitSectionInitSectionParserRuleCall_7_0ElementType());

	public static final IGrammarAwareElementType Definition_RightCurlyBracketKeyword_8_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_RightCurlyBracketKeyword_8ElementType());

	public static final IGrammarAwareElementType Definition_EventuellTclProceduresAssignment_9_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_EventuellTclProceduresAssignment_9ElementType());

	public static final IGrammarAwareElementType Definition_EventuellTclProceduresAlternatives_9_0_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_EventuellTclProceduresAlternatives_9_0ElementType());

	public static final IGrammarAwareElementType Definition_EventuellTclProceduresIDTerminalRuleCall_9_0_0_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_EventuellTclProceduresIDTerminalRuleCall_9_0_0ElementType());

	public static final IGrammarAwareElementType Definition_EventuellTclProceduresANY_OTHERTerminalRuleCall_9_0_1_ELEMENT_TYPE = associate(DefinitionFactory.createDefinition_EventuellTclProceduresANY_OTHERTerminalRuleCall_9_0_1ElementType());

	private static class DataFactory {
		public static IGrammarAwareElementType createDataElementType() {
			return new IGrammarAwareElementType("Data_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDataRule());
		}
		public static IGrammarAwareElementType createData_GroupElementType() {
			return new IGrammarAwareElementType("Data_Group_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDataAccess().getGroup());
		}
		public static IGrammarAwareElementType createData_DataKeyword_0ElementType() {
			return new IGrammarAwareElementType("Data_DataKeyword_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDataAccess().getDataKeyword_0());
		}
		public static IGrammarAwareElementType createData_LeftCurlyBracketKeyword_1ElementType() {
			return new IGrammarAwareElementType("Data_LeftCurlyBracketKeyword_1_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDataAccess().getLeftCurlyBracketKeyword_1());
		}
		public static IGrammarAwareElementType createData_Alternatives_2ElementType() {
			return new IGrammarAwareElementType("Data_Alternatives_2_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDataAccess().getAlternatives_2());
		}
		public static IGrammarAwareElementType createData_DEF_COMMENTTerminalRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("Data_DEF_COMMENTTerminalRuleCall_2_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDataAccess().getDEF_COMMENTTerminalRuleCall_2_0());
		}
		public static IGrammarAwareElementType createData_FieldDefinitionsAssignment_2_1ElementType() {
			return new IGrammarAwareElementType("Data_FieldDefinitionsAssignment_2_1_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDataAccess().getFieldDefinitionsAssignment_2_1());
		}
		public static IGrammarAwareElementType createData_FieldDefinitionsFieldDefinitionParserRuleCall_2_1_0ElementType() {
			return new IGrammarAwareElementType("Data_FieldDefinitionsFieldDefinitionParserRuleCall_2_1_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDataAccess().getFieldDefinitionsFieldDefinitionParserRuleCall_2_1_0());
		}
		public static IGrammarAwareElementType createData_RightCurlyBracketKeyword_3ElementType() {
			return new IGrammarAwareElementType("Data_RightCurlyBracketKeyword_3_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getDataAccess().getRightCurlyBracketKeyword_3());
		}
	}

	public static final IGrammarAwareElementType Data_ELEMENT_TYPE = associate(DataFactory.createDataElementType());

	public static final IGrammarAwareElementType Data_Group_ELEMENT_TYPE = associate(DataFactory.createData_GroupElementType());

	public static final IGrammarAwareElementType Data_DataKeyword_0_ELEMENT_TYPE = associate(DataFactory.createData_DataKeyword_0ElementType());

	public static final IGrammarAwareElementType Data_LeftCurlyBracketKeyword_1_ELEMENT_TYPE = associate(DataFactory.createData_LeftCurlyBracketKeyword_1ElementType());

	public static final IGrammarAwareElementType Data_Alternatives_2_ELEMENT_TYPE = associate(DataFactory.createData_Alternatives_2ElementType());

	public static final IGrammarAwareElementType Data_DEF_COMMENTTerminalRuleCall_2_0_ELEMENT_TYPE = associate(DataFactory.createData_DEF_COMMENTTerminalRuleCall_2_0ElementType());

	public static final IGrammarAwareElementType Data_FieldDefinitionsAssignment_2_1_ELEMENT_TYPE = associate(DataFactory.createData_FieldDefinitionsAssignment_2_1ElementType());

	public static final IGrammarAwareElementType Data_FieldDefinitionsFieldDefinitionParserRuleCall_2_1_0_ELEMENT_TYPE = associate(DataFactory.createData_FieldDefinitionsFieldDefinitionParserRuleCall_2_1_0ElementType());

	public static final IGrammarAwareElementType Data_RightCurlyBracketKeyword_3_ELEMENT_TYPE = associate(DataFactory.createData_RightCurlyBracketKeyword_3ElementType());

	private static class InitSectionFactory {
		public static IGrammarAwareElementType createInitSectionElementType() {
			return new IGrammarAwareElementType("InitSection_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getInitSectionRule());
		}
		public static IGrammarAwareElementType createInitSection_GroupElementType() {
			return new IGrammarAwareElementType("InitSection_Group_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getInitSectionAccess().getGroup());
		}
		public static IGrammarAwareElementType createInitSection_InitKeyword_0ElementType() {
			return new IGrammarAwareElementType("InitSection_InitKeyword_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getInitSectionAccess().getInitKeyword_0());
		}
		public static IGrammarAwareElementType createInitSection_LeftCurlyBracketKeyword_1ElementType() {
			return new IGrammarAwareElementType("InitSection_LeftCurlyBracketKeyword_1_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getInitSectionAccess().getLeftCurlyBracketKeyword_1());
		}
		public static IGrammarAwareElementType createInitSection_Alternatives_2ElementType() {
			return new IGrammarAwareElementType("InitSection_Alternatives_2_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getInitSectionAccess().getAlternatives_2());
		}
		public static IGrammarAwareElementType createInitSection_DEF_COMMENTTerminalRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("InitSection_DEF_COMMENTTerminalRuleCall_2_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getInitSectionAccess().getDEF_COMMENTTerminalRuleCall_2_0());
		}
		public static IGrammarAwareElementType createInitSection_InitDefinitionsAssignment_2_1ElementType() {
			return new IGrammarAwareElementType("InitSection_InitDefinitionsAssignment_2_1_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getInitSectionAccess().getInitDefinitionsAssignment_2_1());
		}
		public static IGrammarAwareElementType createInitSection_InitDefinitionsInitDefinitionParserRuleCall_2_1_0ElementType() {
			return new IGrammarAwareElementType("InitSection_InitDefinitionsInitDefinitionParserRuleCall_2_1_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getInitSectionAccess().getInitDefinitionsInitDefinitionParserRuleCall_2_1_0());
		}
		public static IGrammarAwareElementType createInitSection_RightCurlyBracketKeyword_3ElementType() {
			return new IGrammarAwareElementType("InitSection_RightCurlyBracketKeyword_3_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getInitSectionAccess().getRightCurlyBracketKeyword_3());
		}
	}

	public static final IGrammarAwareElementType InitSection_ELEMENT_TYPE = associate(InitSectionFactory.createInitSectionElementType());

	public static final IGrammarAwareElementType InitSection_Group_ELEMENT_TYPE = associate(InitSectionFactory.createInitSection_GroupElementType());

	public static final IGrammarAwareElementType InitSection_InitKeyword_0_ELEMENT_TYPE = associate(InitSectionFactory.createInitSection_InitKeyword_0ElementType());

	public static final IGrammarAwareElementType InitSection_LeftCurlyBracketKeyword_1_ELEMENT_TYPE = associate(InitSectionFactory.createInitSection_LeftCurlyBracketKeyword_1ElementType());

	public static final IGrammarAwareElementType InitSection_Alternatives_2_ELEMENT_TYPE = associate(InitSectionFactory.createInitSection_Alternatives_2ElementType());

	public static final IGrammarAwareElementType InitSection_DEF_COMMENTTerminalRuleCall_2_0_ELEMENT_TYPE = associate(InitSectionFactory.createInitSection_DEF_COMMENTTerminalRuleCall_2_0ElementType());

	public static final IGrammarAwareElementType InitSection_InitDefinitionsAssignment_2_1_ELEMENT_TYPE = associate(InitSectionFactory.createInitSection_InitDefinitionsAssignment_2_1ElementType());

	public static final IGrammarAwareElementType InitSection_InitDefinitionsInitDefinitionParserRuleCall_2_1_0_ELEMENT_TYPE = associate(InitSectionFactory.createInitSection_InitDefinitionsInitDefinitionParserRuleCall_2_1_0ElementType());

	public static final IGrammarAwareElementType InitSection_RightCurlyBracketKeyword_3_ELEMENT_TYPE = associate(InitSectionFactory.createInitSection_RightCurlyBracketKeyword_3ElementType());

	private static class InitDefinitionFactory {
		public static IGrammarAwareElementType createInitDefinitionElementType() {
			return new IGrammarAwareElementType("InitDefinition_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getInitDefinitionRule());
		}
		public static IGrammarAwareElementType createInitDefinition_GroupElementType() {
			return new IGrammarAwareElementType("InitDefinition_Group_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getInitDefinitionAccess().getGroup());
		}
		public static IGrammarAwareElementType createInitDefinition_InitFieldKeyword_0ElementType() {
			return new IGrammarAwareElementType("InitDefinition_InitFieldKeyword_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getInitDefinitionAccess().getInitFieldKeyword_0());
		}
		public static IGrammarAwareElementType createInitDefinition_IdAssignment_1ElementType() {
			return new IGrammarAwareElementType("InitDefinition_IdAssignment_1_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getInitDefinitionAccess().getIdAssignment_1());
		}
		public static IGrammarAwareElementType createInitDefinition_IdIDTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("InitDefinition_IdIDTerminalRuleCall_1_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getInitDefinitionAccess().getIdIDTerminalRuleCall_1_0());
		}
		public static IGrammarAwareElementType createInitDefinition_InitValueAssignment_2ElementType() {
			return new IGrammarAwareElementType("InitDefinition_InitValueAssignment_2_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getInitDefinitionAccess().getInitValueAssignment_2());
		}
		public static IGrammarAwareElementType createInitDefinition_InitValueSTRINGTerminalRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("InitDefinition_InitValueSTRINGTerminalRuleCall_2_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getInitDefinitionAccess().getInitValueSTRINGTerminalRuleCall_2_0());
		}
	}

	public static final IGrammarAwareElementType InitDefinition_ELEMENT_TYPE = associate(InitDefinitionFactory.createInitDefinitionElementType());

	public static final IGrammarAwareElementType InitDefinition_Group_ELEMENT_TYPE = associate(InitDefinitionFactory.createInitDefinition_GroupElementType());

	public static final IGrammarAwareElementType InitDefinition_InitFieldKeyword_0_ELEMENT_TYPE = associate(InitDefinitionFactory.createInitDefinition_InitFieldKeyword_0ElementType());

	public static final IGrammarAwareElementType InitDefinition_IdAssignment_1_ELEMENT_TYPE = associate(InitDefinitionFactory.createInitDefinition_IdAssignment_1ElementType());

	public static final IGrammarAwareElementType InitDefinition_IdIDTerminalRuleCall_1_0_ELEMENT_TYPE = associate(InitDefinitionFactory.createInitDefinition_IdIDTerminalRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType InitDefinition_InitValueAssignment_2_ELEMENT_TYPE = associate(InitDefinitionFactory.createInitDefinition_InitValueAssignment_2ElementType());

	public static final IGrammarAwareElementType InitDefinition_InitValueSTRINGTerminalRuleCall_2_0_ELEMENT_TYPE = associate(InitDefinitionFactory.createInitDefinition_InitValueSTRINGTerminalRuleCall_2_0ElementType());

	private static class FieldDefinitionFactory {
		public static IGrammarAwareElementType createFieldDefinitionElementType() {
			return new IGrammarAwareElementType("FieldDefinition_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFieldDefinitionRule());
		}
		public static IGrammarAwareElementType createFieldDefinition_GroupElementType() {
			return new IGrammarAwareElementType("FieldDefinition_Group_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFieldDefinitionAccess().getGroup());
		}
		public static IGrammarAwareElementType createFieldDefinition_FieldTypeAssignment_0ElementType() {
			return new IGrammarAwareElementType("FieldDefinition_FieldTypeAssignment_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFieldDefinitionAccess().getFieldTypeAssignment_0());
		}
		public static IGrammarAwareElementType createFieldDefinition_FieldTypeFIELD_TYPEEnumRuleCall_0_0ElementType() {
			return new IGrammarAwareElementType("FieldDefinition_FieldTypeFIELD_TYPEEnumRuleCall_0_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFieldDefinitionAccess().getFieldTypeFIELD_TYPEEnumRuleCall_0_0());
		}
		public static IGrammarAwareElementType createFieldDefinition_IdAssignment_1ElementType() {
			return new IGrammarAwareElementType("FieldDefinition_IdAssignment_1_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFieldDefinitionAccess().getIdAssignment_1());
		}
		public static IGrammarAwareElementType createFieldDefinition_IdIDTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("FieldDefinition_IdIDTerminalRuleCall_1_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFieldDefinitionAccess().getIdIDTerminalRuleCall_1_0());
		}
		public static IGrammarAwareElementType createFieldDefinition_NameAssignment_2ElementType() {
			return new IGrammarAwareElementType("FieldDefinition_NameAssignment_2_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFieldDefinitionAccess().getNameAssignment_2());
		}
		public static IGrammarAwareElementType createFieldDefinition_NameSTRINGTerminalRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("FieldDefinition_NameSTRINGTerminalRuleCall_2_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFieldDefinitionAccess().getNameSTRINGTerminalRuleCall_2_0());
		}
		public static IGrammarAwareElementType createFieldDefinition_AccessAssignment_3ElementType() {
			return new IGrammarAwareElementType("FieldDefinition_AccessAssignment_3_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFieldDefinitionAccess().getAccessAssignment_3());
		}
		public static IGrammarAwareElementType createFieldDefinition_AccessROLEEnumRuleCall_3_0ElementType() {
			return new IGrammarAwareElementType("FieldDefinition_AccessROLEEnumRuleCall_3_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFieldDefinitionAccess().getAccessROLEEnumRuleCall_3_0());
		}
		public static IGrammarAwareElementType createFieldDefinition_RecordClassAssignment_4ElementType() {
			return new IGrammarAwareElementType("FieldDefinition_RecordClassAssignment_4_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFieldDefinitionAccess().getRecordClassAssignment_4());
		}
		public static IGrammarAwareElementType createFieldDefinition_RecordClassRECORDCLASSEnumRuleCall_4_0ElementType() {
			return new IGrammarAwareElementType("FieldDefinition_RecordClassRECORDCLASSEnumRuleCall_4_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFieldDefinitionAccess().getRecordClassRECORDCLASSEnumRuleCall_4_0());
		}
		public static IGrammarAwareElementType createFieldDefinition_ColonKeyword_5ElementType() {
			return new IGrammarAwareElementType("FieldDefinition_ColonKeyword_5_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFieldDefinitionAccess().getColonKeyword_5());
		}
		public static IGrammarAwareElementType createFieldDefinition_FieldNameAssignment_6ElementType() {
			return new IGrammarAwareElementType("FieldDefinition_FieldNameAssignment_6_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFieldDefinitionAccess().getFieldNameAssignment_6());
		}
		public static IGrammarAwareElementType createFieldDefinition_FieldNameIDTerminalRuleCall_6_0ElementType() {
			return new IGrammarAwareElementType("FieldDefinition_FieldNameIDTerminalRuleCall_6_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFieldDefinitionAccess().getFieldNameIDTerminalRuleCall_6_0());
		}
		public static IGrammarAwareElementType createFieldDefinition_LengthAssignment_7ElementType() {
			return new IGrammarAwareElementType("FieldDefinition_LengthAssignment_7_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFieldDefinitionAccess().getLengthAssignment_7());
		}
		public static IGrammarAwareElementType createFieldDefinition_LengthINTTerminalRuleCall_7_0ElementType() {
			return new IGrammarAwareElementType("FieldDefinition_LengthINTTerminalRuleCall_7_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFieldDefinitionAccess().getLengthINTTerminalRuleCall_7_0());
		}
		public static IGrammarAwareElementType createFieldDefinition_OptionsAssignment_8ElementType() {
			return new IGrammarAwareElementType("FieldDefinition_OptionsAssignment_8_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFieldDefinitionAccess().getOptionsAssignment_8());
		}
		public static IGrammarAwareElementType createFieldDefinition_OptionsOptionParserRuleCall_8_0ElementType() {
			return new IGrammarAwareElementType("FieldDefinition_OptionsOptionParserRuleCall_8_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFieldDefinitionAccess().getOptionsOptionParserRuleCall_8_0());
		}
	}

	public static final IGrammarAwareElementType FieldDefinition_ELEMENT_TYPE = associate(FieldDefinitionFactory.createFieldDefinitionElementType());

	public static final IGrammarAwareElementType FieldDefinition_Group_ELEMENT_TYPE = associate(FieldDefinitionFactory.createFieldDefinition_GroupElementType());

	public static final IGrammarAwareElementType FieldDefinition_FieldTypeAssignment_0_ELEMENT_TYPE = associate(FieldDefinitionFactory.createFieldDefinition_FieldTypeAssignment_0ElementType());

	public static final IGrammarAwareElementType FieldDefinition_FieldTypeFIELD_TYPEEnumRuleCall_0_0_ELEMENT_TYPE = associate(FieldDefinitionFactory.createFieldDefinition_FieldTypeFIELD_TYPEEnumRuleCall_0_0ElementType());

	public static final IGrammarAwareElementType FieldDefinition_IdAssignment_1_ELEMENT_TYPE = associate(FieldDefinitionFactory.createFieldDefinition_IdAssignment_1ElementType());

	public static final IGrammarAwareElementType FieldDefinition_IdIDTerminalRuleCall_1_0_ELEMENT_TYPE = associate(FieldDefinitionFactory.createFieldDefinition_IdIDTerminalRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType FieldDefinition_NameAssignment_2_ELEMENT_TYPE = associate(FieldDefinitionFactory.createFieldDefinition_NameAssignment_2ElementType());

	public static final IGrammarAwareElementType FieldDefinition_NameSTRINGTerminalRuleCall_2_0_ELEMENT_TYPE = associate(FieldDefinitionFactory.createFieldDefinition_NameSTRINGTerminalRuleCall_2_0ElementType());

	public static final IGrammarAwareElementType FieldDefinition_AccessAssignment_3_ELEMENT_TYPE = associate(FieldDefinitionFactory.createFieldDefinition_AccessAssignment_3ElementType());

	public static final IGrammarAwareElementType FieldDefinition_AccessROLEEnumRuleCall_3_0_ELEMENT_TYPE = associate(FieldDefinitionFactory.createFieldDefinition_AccessROLEEnumRuleCall_3_0ElementType());

	public static final IGrammarAwareElementType FieldDefinition_RecordClassAssignment_4_ELEMENT_TYPE = associate(FieldDefinitionFactory.createFieldDefinition_RecordClassAssignment_4ElementType());

	public static final IGrammarAwareElementType FieldDefinition_RecordClassRECORDCLASSEnumRuleCall_4_0_ELEMENT_TYPE = associate(FieldDefinitionFactory.createFieldDefinition_RecordClassRECORDCLASSEnumRuleCall_4_0ElementType());

	public static final IGrammarAwareElementType FieldDefinition_ColonKeyword_5_ELEMENT_TYPE = associate(FieldDefinitionFactory.createFieldDefinition_ColonKeyword_5ElementType());

	public static final IGrammarAwareElementType FieldDefinition_FieldNameAssignment_6_ELEMENT_TYPE = associate(FieldDefinitionFactory.createFieldDefinition_FieldNameAssignment_6ElementType());

	public static final IGrammarAwareElementType FieldDefinition_FieldNameIDTerminalRuleCall_6_0_ELEMENT_TYPE = associate(FieldDefinitionFactory.createFieldDefinition_FieldNameIDTerminalRuleCall_6_0ElementType());

	public static final IGrammarAwareElementType FieldDefinition_LengthAssignment_7_ELEMENT_TYPE = associate(FieldDefinitionFactory.createFieldDefinition_LengthAssignment_7ElementType());

	public static final IGrammarAwareElementType FieldDefinition_LengthINTTerminalRuleCall_7_0_ELEMENT_TYPE = associate(FieldDefinitionFactory.createFieldDefinition_LengthINTTerminalRuleCall_7_0ElementType());

	public static final IGrammarAwareElementType FieldDefinition_OptionsAssignment_8_ELEMENT_TYPE = associate(FieldDefinitionFactory.createFieldDefinition_OptionsAssignment_8ElementType());

	public static final IGrammarAwareElementType FieldDefinition_OptionsOptionParserRuleCall_8_0_ELEMENT_TYPE = associate(FieldDefinitionFactory.createFieldDefinition_OptionsOptionParserRuleCall_8_0ElementType());

	private static class OptionFactory {
		public static IGrammarAwareElementType createOptionElementType() {
			return new IGrammarAwareElementType("Option_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionRule());
		}
		public static IGrammarAwareElementType createOption_AlternativesElementType() {
			return new IGrammarAwareElementType("Option_Alternatives_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createOption_OptionValprocParserRuleCall_0ElementType() {
			return new IGrammarAwareElementType("Option_OptionValprocParserRuleCall_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionAccess().getOptionValprocParserRuleCall_0());
		}
		public static IGrammarAwareElementType createOption_OptionStrictParserRuleCall_1ElementType() {
			return new IGrammarAwareElementType("Option_OptionStrictParserRuleCall_1_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionAccess().getOptionStrictParserRuleCall_1());
		}
		public static IGrammarAwareElementType createOption_OptionRangeParserRuleCall_2ElementType() {
			return new IGrammarAwareElementType("Option_OptionRangeParserRuleCall_2_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionAccess().getOptionRangeParserRuleCall_2());
		}
		public static IGrammarAwareElementType createOption_OptionContribParserRuleCall_3ElementType() {
			return new IGrammarAwareElementType("Option_OptionContribParserRuleCall_3_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionAccess().getOptionContribParserRuleCall_3());
		}
	}

	public static final IGrammarAwareElementType Option_ELEMENT_TYPE = associate(OptionFactory.createOptionElementType());

	public static final IGrammarAwareElementType Option_Alternatives_ELEMENT_TYPE = associate(OptionFactory.createOption_AlternativesElementType());

	public static final IGrammarAwareElementType Option_OptionValprocParserRuleCall_0_ELEMENT_TYPE = associate(OptionFactory.createOption_OptionValprocParserRuleCall_0ElementType());

	public static final IGrammarAwareElementType Option_OptionStrictParserRuleCall_1_ELEMENT_TYPE = associate(OptionFactory.createOption_OptionStrictParserRuleCall_1ElementType());

	public static final IGrammarAwareElementType Option_OptionRangeParserRuleCall_2_ELEMENT_TYPE = associate(OptionFactory.createOption_OptionRangeParserRuleCall_2ElementType());

	public static final IGrammarAwareElementType Option_OptionContribParserRuleCall_3_ELEMENT_TYPE = associate(OptionFactory.createOption_OptionContribParserRuleCall_3ElementType());

	private static class OptionValprocFactory {
		public static IGrammarAwareElementType createOptionValprocElementType() {
			return new IGrammarAwareElementType("OptionValproc_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionValprocRule());
		}
		public static IGrammarAwareElementType createOptionValproc_GroupElementType() {
			return new IGrammarAwareElementType("OptionValproc_Group_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionValprocAccess().getGroup());
		}
		public static IGrammarAwareElementType createOptionValproc_ValprocAssignment_0ElementType() {
			return new IGrammarAwareElementType("OptionValproc_ValprocAssignment_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionValprocAccess().getValprocAssignment_0());
		}
		public static IGrammarAwareElementType createOptionValproc_ValprocValprocKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("OptionValproc_ValprocValprocKeyword_0_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionValprocAccess().getValprocValprocKeyword_0_0());
		}
		public static IGrammarAwareElementType createOptionValproc_TclProcAssignment_1ElementType() {
			return new IGrammarAwareElementType("OptionValproc_TclProcAssignment_1_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionValprocAccess().getTclProcAssignment_1());
		}
		public static IGrammarAwareElementType createOptionValproc_TclProcIDTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("OptionValproc_TclProcIDTerminalRuleCall_1_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionValprocAccess().getTclProcIDTerminalRuleCall_1_0());
		}
	}

	public static final IGrammarAwareElementType OptionValproc_ELEMENT_TYPE = associate(OptionValprocFactory.createOptionValprocElementType());

	public static final IGrammarAwareElementType OptionValproc_Group_ELEMENT_TYPE = associate(OptionValprocFactory.createOptionValproc_GroupElementType());

	public static final IGrammarAwareElementType OptionValproc_ValprocAssignment_0_ELEMENT_TYPE = associate(OptionValprocFactory.createOptionValproc_ValprocAssignment_0ElementType());

	public static final IGrammarAwareElementType OptionValproc_ValprocValprocKeyword_0_0_ELEMENT_TYPE = associate(OptionValprocFactory.createOptionValproc_ValprocValprocKeyword_0_0ElementType());

	public static final IGrammarAwareElementType OptionValproc_TclProcAssignment_1_ELEMENT_TYPE = associate(OptionValprocFactory.createOptionValproc_TclProcAssignment_1ElementType());

	public static final IGrammarAwareElementType OptionValproc_TclProcIDTerminalRuleCall_1_0_ELEMENT_TYPE = associate(OptionValprocFactory.createOptionValproc_TclProcIDTerminalRuleCall_1_0ElementType());

	private static class OptionStrictFactory {
		public static IGrammarAwareElementType createOptionStrictElementType() {
			return new IGrammarAwareElementType("OptionStrict_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionStrictRule());
		}
		public static IGrammarAwareElementType createOptionStrict_StrictAssignmentElementType() {
			return new IGrammarAwareElementType("OptionStrict_StrictAssignment_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionStrictAccess().getStrictAssignment());
		}
		public static IGrammarAwareElementType createOptionStrict_StrictStrictKeyword_0ElementType() {
			return new IGrammarAwareElementType("OptionStrict_StrictStrictKeyword_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionStrictAccess().getStrictStrictKeyword_0());
		}
	}

	public static final IGrammarAwareElementType OptionStrict_ELEMENT_TYPE = associate(OptionStrictFactory.createOptionStrictElementType());

	public static final IGrammarAwareElementType OptionStrict_StrictAssignment_ELEMENT_TYPE = associate(OptionStrictFactory.createOptionStrict_StrictAssignmentElementType());

	public static final IGrammarAwareElementType OptionStrict_StrictStrictKeyword_0_ELEMENT_TYPE = associate(OptionStrictFactory.createOptionStrict_StrictStrictKeyword_0ElementType());

	private static class OptionRangeFactory {
		public static IGrammarAwareElementType createOptionRangeElementType() {
			return new IGrammarAwareElementType("OptionRange_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionRangeRule());
		}
		public static IGrammarAwareElementType createOptionRange_GroupElementType() {
			return new IGrammarAwareElementType("OptionRange_Group_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionRangeAccess().getGroup());
		}
		public static IGrammarAwareElementType createOptionRange_RangeKeyword_0ElementType() {
			return new IGrammarAwareElementType("OptionRange_RangeKeyword_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionRangeAccess().getRangeKeyword_0());
		}
		public static IGrammarAwareElementType createOptionRange_ListKeyword_1ElementType() {
			return new IGrammarAwareElementType("OptionRange_ListKeyword_1_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionRangeAccess().getListKeyword_1());
		}
		public static IGrammarAwareElementType createOptionRange_MinAssignment_2ElementType() {
			return new IGrammarAwareElementType("OptionRange_MinAssignment_2_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionRangeAccess().getMinAssignment_2());
		}
		public static IGrammarAwareElementType createOptionRange_MinINTTerminalRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("OptionRange_MinINTTerminalRuleCall_2_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionRangeAccess().getMinINTTerminalRuleCall_2_0());
		}
		public static IGrammarAwareElementType createOptionRange_MaxAssignment_3ElementType() {
			return new IGrammarAwareElementType("OptionRange_MaxAssignment_3_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionRangeAccess().getMaxAssignment_3());
		}
		public static IGrammarAwareElementType createOptionRange_MaxINTTerminalRuleCall_3_0ElementType() {
			return new IGrammarAwareElementType("OptionRange_MaxINTTerminalRuleCall_3_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionRangeAccess().getMaxINTTerminalRuleCall_3_0());
		}
		public static IGrammarAwareElementType createOptionRange_RightSquareBracketKeyword_4ElementType() {
			return new IGrammarAwareElementType("OptionRange_RightSquareBracketKeyword_4_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionRangeAccess().getRightSquareBracketKeyword_4());
		}
	}

	public static final IGrammarAwareElementType OptionRange_ELEMENT_TYPE = associate(OptionRangeFactory.createOptionRangeElementType());

	public static final IGrammarAwareElementType OptionRange_Group_ELEMENT_TYPE = associate(OptionRangeFactory.createOptionRange_GroupElementType());

	public static final IGrammarAwareElementType OptionRange_RangeKeyword_0_ELEMENT_TYPE = associate(OptionRangeFactory.createOptionRange_RangeKeyword_0ElementType());

	public static final IGrammarAwareElementType OptionRange_ListKeyword_1_ELEMENT_TYPE = associate(OptionRangeFactory.createOptionRange_ListKeyword_1ElementType());

	public static final IGrammarAwareElementType OptionRange_MinAssignment_2_ELEMENT_TYPE = associate(OptionRangeFactory.createOptionRange_MinAssignment_2ElementType());

	public static final IGrammarAwareElementType OptionRange_MinINTTerminalRuleCall_2_0_ELEMENT_TYPE = associate(OptionRangeFactory.createOptionRange_MinINTTerminalRuleCall_2_0ElementType());

	public static final IGrammarAwareElementType OptionRange_MaxAssignment_3_ELEMENT_TYPE = associate(OptionRangeFactory.createOptionRange_MaxAssignment_3ElementType());

	public static final IGrammarAwareElementType OptionRange_MaxINTTerminalRuleCall_3_0_ELEMENT_TYPE = associate(OptionRangeFactory.createOptionRange_MaxINTTerminalRuleCall_3_0ElementType());

	public static final IGrammarAwareElementType OptionRange_RightSquareBracketKeyword_4_ELEMENT_TYPE = associate(OptionRangeFactory.createOptionRange_RightSquareBracketKeyword_4ElementType());

	private static class OptionContribFactory {
		public static IGrammarAwareElementType createOptionContribElementType() {
			return new IGrammarAwareElementType("OptionContrib_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionContribRule());
		}
		public static IGrammarAwareElementType createOptionContrib_ContribAssignmentElementType() {
			return new IGrammarAwareElementType("OptionContrib_ContribAssignment_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionContribAccess().getContribAssignment());
		}
		public static IGrammarAwareElementType createOptionContrib_ContribContribKeyword_0ElementType() {
			return new IGrammarAwareElementType("OptionContrib_ContribContribKeyword_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getOptionContribAccess().getContribContribKeyword_0());
		}
	}

	public static final IGrammarAwareElementType OptionContrib_ELEMENT_TYPE = associate(OptionContribFactory.createOptionContribElementType());

	public static final IGrammarAwareElementType OptionContrib_ContribAssignment_ELEMENT_TYPE = associate(OptionContribFactory.createOptionContrib_ContribAssignmentElementType());

	public static final IGrammarAwareElementType OptionContrib_ContribContribKeyword_0_ELEMENT_TYPE = associate(OptionContribFactory.createOptionContrib_ContribContribKeyword_0ElementType());

	private static class FIELD_TYPEFactory {
		public static IGrammarAwareElementType createFIELD_TYPEElementType() {
			return new IGrammarAwareElementType("FIELD_TYPE_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFIELD_TYPERule());
		}
		public static IGrammarAwareElementType createFIELD_TYPE_AlternativesElementType() {
			return new IGrammarAwareElementType("FIELD_TYPE_Alternatives_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFIELD_TYPEAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createFIELD_TYPE_STRING_FIELDEnumLiteralDeclaration_0ElementType() {
			return new IGrammarAwareElementType("FIELD_TYPE_STRING_FIELDEnumLiteralDeclaration_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFIELD_TYPEAccess().getSTRING_FIELDEnumLiteralDeclaration_0());
		}
		public static IGrammarAwareElementType createFIELD_TYPE_STRING_FIELDStringFieldKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("FIELD_TYPE_STRING_FIELDStringFieldKeyword_0_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFIELD_TYPEAccess().getSTRING_FIELDStringFieldKeyword_0_0());
		}
		public static IGrammarAwareElementType createFIELD_TYPE_TIME_FIELDEnumLiteralDeclaration_1ElementType() {
			return new IGrammarAwareElementType("FIELD_TYPE_TIME_FIELDEnumLiteralDeclaration_1_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFIELD_TYPEAccess().getTIME_FIELDEnumLiteralDeclaration_1());
		}
		public static IGrammarAwareElementType createFIELD_TYPE_TIME_FIELDTimeFieldKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("FIELD_TYPE_TIME_FIELDTimeFieldKeyword_1_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFIELD_TYPEAccess().getTIME_FIELDTimeFieldKeyword_1_0());
		}
		public static IGrammarAwareElementType createFIELD_TYPE_INTEGER_FIELDEnumLiteralDeclaration_2ElementType() {
			return new IGrammarAwareElementType("FIELD_TYPE_INTEGER_FIELDEnumLiteralDeclaration_2_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFIELD_TYPEAccess().getINTEGER_FIELDEnumLiteralDeclaration_2());
		}
		public static IGrammarAwareElementType createFIELD_TYPE_INTEGER_FIELDIntegerFieldKeyword_2_0ElementType() {
			return new IGrammarAwareElementType("FIELD_TYPE_INTEGER_FIELDIntegerFieldKeyword_2_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFIELD_TYPEAccess().getINTEGER_FIELDIntegerFieldKeyword_2_0());
		}
		public static IGrammarAwareElementType createFIELD_TYPE_PRICE_FIELDEnumLiteralDeclaration_3ElementType() {
			return new IGrammarAwareElementType("FIELD_TYPE_PRICE_FIELDEnumLiteralDeclaration_3_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFIELD_TYPEAccess().getPRICE_FIELDEnumLiteralDeclaration_3());
		}
		public static IGrammarAwareElementType createFIELD_TYPE_PRICE_FIELDPriceFieldKeyword_3_0ElementType() {
			return new IGrammarAwareElementType("FIELD_TYPE_PRICE_FIELDPriceFieldKeyword_3_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFIELD_TYPEAccess().getPRICE_FIELDPriceFieldKeyword_3_0());
		}
		public static IGrammarAwareElementType createFIELD_TYPE_DOUBLE_FIELDEnumLiteralDeclaration_4ElementType() {
			return new IGrammarAwareElementType("FIELD_TYPE_DOUBLE_FIELDEnumLiteralDeclaration_4_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFIELD_TYPEAccess().getDOUBLE_FIELDEnumLiteralDeclaration_4());
		}
		public static IGrammarAwareElementType createFIELD_TYPE_DOUBLE_FIELDDoubleFieldKeyword_4_0ElementType() {
			return new IGrammarAwareElementType("FIELD_TYPE_DOUBLE_FIELDDoubleFieldKeyword_4_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFIELD_TYPEAccess().getDOUBLE_FIELDDoubleFieldKeyword_4_0());
		}
		public static IGrammarAwareElementType createFIELD_TYPE_DATE_FIELDEnumLiteralDeclaration_5ElementType() {
			return new IGrammarAwareElementType("FIELD_TYPE_DATE_FIELDEnumLiteralDeclaration_5_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFIELD_TYPEAccess().getDATE_FIELDEnumLiteralDeclaration_5());
		}
		public static IGrammarAwareElementType createFIELD_TYPE_DATE_FIELDDateFieldKeyword_5_0ElementType() {
			return new IGrammarAwareElementType("FIELD_TYPE_DATE_FIELDDateFieldKeyword_5_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getFIELD_TYPEAccess().getDATE_FIELDDateFieldKeyword_5_0());
		}
	}

	public static final IGrammarAwareElementType FIELD_TYPE_ELEMENT_TYPE = associate(FIELD_TYPEFactory.createFIELD_TYPEElementType());

	public static final IGrammarAwareElementType FIELD_TYPE_Alternatives_ELEMENT_TYPE = associate(FIELD_TYPEFactory.createFIELD_TYPE_AlternativesElementType());

	public static final IGrammarAwareElementType FIELD_TYPE_STRING_FIELDEnumLiteralDeclaration_0_ELEMENT_TYPE = associate(FIELD_TYPEFactory.createFIELD_TYPE_STRING_FIELDEnumLiteralDeclaration_0ElementType());

	public static final IGrammarAwareElementType FIELD_TYPE_STRING_FIELDStringFieldKeyword_0_0_ELEMENT_TYPE = associate(FIELD_TYPEFactory.createFIELD_TYPE_STRING_FIELDStringFieldKeyword_0_0ElementType());

	public static final IGrammarAwareElementType FIELD_TYPE_TIME_FIELDEnumLiteralDeclaration_1_ELEMENT_TYPE = associate(FIELD_TYPEFactory.createFIELD_TYPE_TIME_FIELDEnumLiteralDeclaration_1ElementType());

	public static final IGrammarAwareElementType FIELD_TYPE_TIME_FIELDTimeFieldKeyword_1_0_ELEMENT_TYPE = associate(FIELD_TYPEFactory.createFIELD_TYPE_TIME_FIELDTimeFieldKeyword_1_0ElementType());

	public static final IGrammarAwareElementType FIELD_TYPE_INTEGER_FIELDEnumLiteralDeclaration_2_ELEMENT_TYPE = associate(FIELD_TYPEFactory.createFIELD_TYPE_INTEGER_FIELDEnumLiteralDeclaration_2ElementType());

	public static final IGrammarAwareElementType FIELD_TYPE_INTEGER_FIELDIntegerFieldKeyword_2_0_ELEMENT_TYPE = associate(FIELD_TYPEFactory.createFIELD_TYPE_INTEGER_FIELDIntegerFieldKeyword_2_0ElementType());

	public static final IGrammarAwareElementType FIELD_TYPE_PRICE_FIELDEnumLiteralDeclaration_3_ELEMENT_TYPE = associate(FIELD_TYPEFactory.createFIELD_TYPE_PRICE_FIELDEnumLiteralDeclaration_3ElementType());

	public static final IGrammarAwareElementType FIELD_TYPE_PRICE_FIELDPriceFieldKeyword_3_0_ELEMENT_TYPE = associate(FIELD_TYPEFactory.createFIELD_TYPE_PRICE_FIELDPriceFieldKeyword_3_0ElementType());

	public static final IGrammarAwareElementType FIELD_TYPE_DOUBLE_FIELDEnumLiteralDeclaration_4_ELEMENT_TYPE = associate(FIELD_TYPEFactory.createFIELD_TYPE_DOUBLE_FIELDEnumLiteralDeclaration_4ElementType());

	public static final IGrammarAwareElementType FIELD_TYPE_DOUBLE_FIELDDoubleFieldKeyword_4_0_ELEMENT_TYPE = associate(FIELD_TYPEFactory.createFIELD_TYPE_DOUBLE_FIELDDoubleFieldKeyword_4_0ElementType());

	public static final IGrammarAwareElementType FIELD_TYPE_DATE_FIELDEnumLiteralDeclaration_5_ELEMENT_TYPE = associate(FIELD_TYPEFactory.createFIELD_TYPE_DATE_FIELDEnumLiteralDeclaration_5ElementType());

	public static final IGrammarAwareElementType FIELD_TYPE_DATE_FIELDDateFieldKeyword_5_0_ELEMENT_TYPE = associate(FIELD_TYPEFactory.createFIELD_TYPE_DATE_FIELDDateFieldKeyword_5_0ElementType());

	private static class ROLEFactory {
		public static IGrammarAwareElementType createROLEElementType() {
			return new IGrammarAwareElementType("ROLE_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getROLERule());
		}
		public static IGrammarAwareElementType createROLE_AlternativesElementType() {
			return new IGrammarAwareElementType("ROLE_Alternatives_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getROLEAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createROLE_RADMINEnumLiteralDeclaration_0ElementType() {
			return new IGrammarAwareElementType("ROLE_RADMINEnumLiteralDeclaration_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getROLEAccess().getRADMINEnumLiteralDeclaration_0());
		}
		public static IGrammarAwareElementType createROLE_RADMINRadminKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("ROLE_RADMINRadminKeyword_0_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getROLEAccess().getRADMINRadminKeyword_0_0());
		}
		public static IGrammarAwareElementType createROLE_NONEEnumLiteralDeclaration_1ElementType() {
			return new IGrammarAwareElementType("ROLE_NONEEnumLiteralDeclaration_1_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getROLEAccess().getNONEEnumLiteralDeclaration_1());
		}
		public static IGrammarAwareElementType createROLE_NONENoneKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("ROLE_NONENoneKeyword_1_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getROLEAccess().getNONENoneKeyword_1_0());
		}
		public static IGrammarAwareElementType createROLE_RTRADEREnumLiteralDeclaration_2ElementType() {
			return new IGrammarAwareElementType("ROLE_RTRADEREnumLiteralDeclaration_2_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getROLEAccess().getRTRADEREnumLiteralDeclaration_2());
		}
		public static IGrammarAwareElementType createROLE_RTRADERRtraderKeyword_2_0ElementType() {
			return new IGrammarAwareElementType("ROLE_RTRADERRtraderKeyword_2_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getROLEAccess().getRTRADERRtraderKeyword_2_0());
		}
		public static IGrammarAwareElementType createROLE_SUPERVISOREnumLiteralDeclaration_3ElementType() {
			return new IGrammarAwareElementType("ROLE_SUPERVISOREnumLiteralDeclaration_3_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getROLEAccess().getSUPERVISOREnumLiteralDeclaration_3());
		}
		public static IGrammarAwareElementType createROLE_SUPERVISORSupervisorKeyword_3_0ElementType() {
			return new IGrammarAwareElementType("ROLE_SUPERVISORSupervisorKeyword_3_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getROLEAccess().getSUPERVISORSupervisorKeyword_3_0());
		}
	}

	public static final IGrammarAwareElementType ROLE_ELEMENT_TYPE = associate(ROLEFactory.createROLEElementType());

	public static final IGrammarAwareElementType ROLE_Alternatives_ELEMENT_TYPE = associate(ROLEFactory.createROLE_AlternativesElementType());

	public static final IGrammarAwareElementType ROLE_RADMINEnumLiteralDeclaration_0_ELEMENT_TYPE = associate(ROLEFactory.createROLE_RADMINEnumLiteralDeclaration_0ElementType());

	public static final IGrammarAwareElementType ROLE_RADMINRadminKeyword_0_0_ELEMENT_TYPE = associate(ROLEFactory.createROLE_RADMINRadminKeyword_0_0ElementType());

	public static final IGrammarAwareElementType ROLE_NONEEnumLiteralDeclaration_1_ELEMENT_TYPE = associate(ROLEFactory.createROLE_NONEEnumLiteralDeclaration_1ElementType());

	public static final IGrammarAwareElementType ROLE_NONENoneKeyword_1_0_ELEMENT_TYPE = associate(ROLEFactory.createROLE_NONENoneKeyword_1_0ElementType());

	public static final IGrammarAwareElementType ROLE_RTRADEREnumLiteralDeclaration_2_ELEMENT_TYPE = associate(ROLEFactory.createROLE_RTRADEREnumLiteralDeclaration_2ElementType());

	public static final IGrammarAwareElementType ROLE_RTRADERRtraderKeyword_2_0_ELEMENT_TYPE = associate(ROLEFactory.createROLE_RTRADERRtraderKeyword_2_0ElementType());

	public static final IGrammarAwareElementType ROLE_SUPERVISOREnumLiteralDeclaration_3_ELEMENT_TYPE = associate(ROLEFactory.createROLE_SUPERVISOREnumLiteralDeclaration_3ElementType());

	public static final IGrammarAwareElementType ROLE_SUPERVISORSupervisorKeyword_3_0_ELEMENT_TYPE = associate(ROLEFactory.createROLE_SUPERVISORSupervisorKeyword_3_0ElementType());

	private static class RECORDCLASSFactory {
		public static IGrammarAwareElementType createRECORDCLASSElementType() {
			return new IGrammarAwareElementType("RECORDCLASS_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getRECORDCLASSRule());
		}
		public static IGrammarAwareElementType createRECORDCLASS_AlternativesElementType() {
			return new IGrammarAwareElementType("RECORDCLASS_Alternatives_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getRECORDCLASSAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createRECORDCLASS_METHOD_READ_ONLYEnumLiteralDeclaration_0ElementType() {
			return new IGrammarAwareElementType("RECORDCLASS_METHOD_READ_ONLYEnumLiteralDeclaration_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getRECORDCLASSAccess().getMETHOD_READ_ONLYEnumLiteralDeclaration_0());
		}
		public static IGrammarAwareElementType createRECORDCLASS_METHOD_READ_ONLYBKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("RECORDCLASS_METHOD_READ_ONLYBKeyword_0_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getRECORDCLASSAccess().getMETHOD_READ_ONLYBKeyword_0_0());
		}
		public static IGrammarAwareElementType createRECORDCLASS_PARENT_READ_ONLYEnumLiteralDeclaration_1ElementType() {
			return new IGrammarAwareElementType("RECORDCLASS_PARENT_READ_ONLYEnumLiteralDeclaration_1_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getRECORDCLASSAccess().getPARENT_READ_ONLYEnumLiteralDeclaration_1());
		}
		public static IGrammarAwareElementType createRECORDCLASS_PARENT_READ_ONLYUKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("RECORDCLASS_PARENT_READ_ONLYUKeyword_1_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getRECORDCLASSAccess().getPARENT_READ_ONLYUKeyword_1_0());
		}
		public static IGrammarAwareElementType createRECORDCLASS_PARENT_READ_WRITEEnumLiteralDeclaration_2ElementType() {
			return new IGrammarAwareElementType("RECORDCLASS_PARENT_READ_WRITEEnumLiteralDeclaration_2_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getRECORDCLASSAccess().getPARENT_READ_WRITEEnumLiteralDeclaration_2());
		}
		public static IGrammarAwareElementType createRECORDCLASS_PARENT_READ_WRITEGKeyword_2_0ElementType() {
			return new IGrammarAwareElementType("RECORDCLASS_PARENT_READ_WRITEGKeyword_2_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getRECORDCLASSAccess().getPARENT_READ_WRITEGKeyword_2_0());
		}
		public static IGrammarAwareElementType createRECORDCLASS_PARENT_READ_REFERENCEEnumLiteralDeclaration_3ElementType() {
			return new IGrammarAwareElementType("RECORDCLASS_PARENT_READ_REFERENCEEnumLiteralDeclaration_3_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getRECORDCLASSAccess().getPARENT_READ_REFERENCEEnumLiteralDeclaration_3());
		}
		public static IGrammarAwareElementType createRECORDCLASS_PARENT_READ_REFERENCERKeyword_3_0ElementType() {
			return new IGrammarAwareElementType("RECORDCLASS_PARENT_READ_REFERENCERKeyword_3_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getRECORDCLASSAccess().getPARENT_READ_REFERENCERKeyword_3_0());
		}
		public static IGrammarAwareElementType createRECORDCLASS_CHILD_READ_ONLYEnumLiteralDeclaration_4ElementType() {
			return new IGrammarAwareElementType("RECORDCLASS_CHILD_READ_ONLYEnumLiteralDeclaration_4_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getRECORDCLASSAccess().getCHILD_READ_ONLYEnumLiteralDeclaration_4());
		}
		public static IGrammarAwareElementType createRECORDCLASS_CHILD_READ_ONLYDKeyword_4_0ElementType() {
			return new IGrammarAwareElementType("RECORDCLASS_CHILD_READ_ONLYDKeyword_4_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getRECORDCLASSAccess().getCHILD_READ_ONLYDKeyword_4_0());
		}
		public static IGrammarAwareElementType createRECORDCLASS_CHILD_READ_WRITEEnumLiteralDeclaration_5ElementType() {
			return new IGrammarAwareElementType("RECORDCLASS_CHILD_READ_WRITEEnumLiteralDeclaration_5_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getRECORDCLASSAccess().getCHILD_READ_WRITEEnumLiteralDeclaration_5());
		}
		public static IGrammarAwareElementType createRECORDCLASS_CHILD_READ_WRITEPKeyword_5_0ElementType() {
			return new IGrammarAwareElementType("RECORDCLASS_CHILD_READ_WRITEPKeyword_5_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getRECORDCLASSAccess().getCHILD_READ_WRITEPKeyword_5_0());
		}
		public static IGrammarAwareElementType createRECORDCLASS_CHILD_READ_REFERENCEEnumLiteralDeclaration_6ElementType() {
			return new IGrammarAwareElementType("RECORDCLASS_CHILD_READ_REFERENCEEnumLiteralDeclaration_6_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getRECORDCLASSAccess().getCHILD_READ_REFERENCEEnumLiteralDeclaration_6());
		}
		public static IGrammarAwareElementType createRECORDCLASS_CHILD_READ_REFERENCESKeyword_6_0ElementType() {
			return new IGrammarAwareElementType("RECORDCLASS_CHILD_READ_REFERENCESKeyword_6_0_ELEMENT_TYPE", DefinitionDSLLanguage.INSTANCE, GRAMMAR_ACCESS.getRECORDCLASSAccess().getCHILD_READ_REFERENCESKeyword_6_0());
		}
	}

	public static final IGrammarAwareElementType RECORDCLASS_ELEMENT_TYPE = associate(RECORDCLASSFactory.createRECORDCLASSElementType());

	public static final IGrammarAwareElementType RECORDCLASS_Alternatives_ELEMENT_TYPE = associate(RECORDCLASSFactory.createRECORDCLASS_AlternativesElementType());

	public static final IGrammarAwareElementType RECORDCLASS_METHOD_READ_ONLYEnumLiteralDeclaration_0_ELEMENT_TYPE = associate(RECORDCLASSFactory.createRECORDCLASS_METHOD_READ_ONLYEnumLiteralDeclaration_0ElementType());

	public static final IGrammarAwareElementType RECORDCLASS_METHOD_READ_ONLYBKeyword_0_0_ELEMENT_TYPE = associate(RECORDCLASSFactory.createRECORDCLASS_METHOD_READ_ONLYBKeyword_0_0ElementType());

	public static final IGrammarAwareElementType RECORDCLASS_PARENT_READ_ONLYEnumLiteralDeclaration_1_ELEMENT_TYPE = associate(RECORDCLASSFactory.createRECORDCLASS_PARENT_READ_ONLYEnumLiteralDeclaration_1ElementType());

	public static final IGrammarAwareElementType RECORDCLASS_PARENT_READ_ONLYUKeyword_1_0_ELEMENT_TYPE = associate(RECORDCLASSFactory.createRECORDCLASS_PARENT_READ_ONLYUKeyword_1_0ElementType());

	public static final IGrammarAwareElementType RECORDCLASS_PARENT_READ_WRITEEnumLiteralDeclaration_2_ELEMENT_TYPE = associate(RECORDCLASSFactory.createRECORDCLASS_PARENT_READ_WRITEEnumLiteralDeclaration_2ElementType());

	public static final IGrammarAwareElementType RECORDCLASS_PARENT_READ_WRITEGKeyword_2_0_ELEMENT_TYPE = associate(RECORDCLASSFactory.createRECORDCLASS_PARENT_READ_WRITEGKeyword_2_0ElementType());

	public static final IGrammarAwareElementType RECORDCLASS_PARENT_READ_REFERENCEEnumLiteralDeclaration_3_ELEMENT_TYPE = associate(RECORDCLASSFactory.createRECORDCLASS_PARENT_READ_REFERENCEEnumLiteralDeclaration_3ElementType());

	public static final IGrammarAwareElementType RECORDCLASS_PARENT_READ_REFERENCERKeyword_3_0_ELEMENT_TYPE = associate(RECORDCLASSFactory.createRECORDCLASS_PARENT_READ_REFERENCERKeyword_3_0ElementType());

	public static final IGrammarAwareElementType RECORDCLASS_CHILD_READ_ONLYEnumLiteralDeclaration_4_ELEMENT_TYPE = associate(RECORDCLASSFactory.createRECORDCLASS_CHILD_READ_ONLYEnumLiteralDeclaration_4ElementType());

	public static final IGrammarAwareElementType RECORDCLASS_CHILD_READ_ONLYDKeyword_4_0_ELEMENT_TYPE = associate(RECORDCLASSFactory.createRECORDCLASS_CHILD_READ_ONLYDKeyword_4_0ElementType());

	public static final IGrammarAwareElementType RECORDCLASS_CHILD_READ_WRITEEnumLiteralDeclaration_5_ELEMENT_TYPE = associate(RECORDCLASSFactory.createRECORDCLASS_CHILD_READ_WRITEEnumLiteralDeclaration_5ElementType());

	public static final IGrammarAwareElementType RECORDCLASS_CHILD_READ_WRITEPKeyword_5_0_ELEMENT_TYPE = associate(RECORDCLASSFactory.createRECORDCLASS_CHILD_READ_WRITEPKeyword_5_0ElementType());

	public static final IGrammarAwareElementType RECORDCLASS_CHILD_READ_REFERENCEEnumLiteralDeclaration_6_ELEMENT_TYPE = associate(RECORDCLASSFactory.createRECORDCLASS_CHILD_READ_REFERENCEEnumLiteralDeclaration_6ElementType());

	public static final IGrammarAwareElementType RECORDCLASS_CHILD_READ_REFERENCESKeyword_6_0_ELEMENT_TYPE = associate(RECORDCLASSFactory.createRECORDCLASS_CHILD_READ_REFERENCESKeyword_6_0ElementType());

	@Override
	public IFileElementType getFileType() {
		return FILE_TYPE;
	}

	@Override
	public IGrammarAwareElementType findElementType(EObject grammarElement) {
		return GRAMMAR_ELEMENT_TYPE.get(grammarElement);
	}
	
	public IGrammarAwareElementType getDefinitionElementType() {
		return Definition_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_GroupElementType() {
		return Definition_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_DefinitionKeyword_0ElementType() {
		return Definition_DefinitionKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_MethodNameAssignment_1ElementType() {
		return Definition_MethodNameAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_MethodNameIDTerminalRuleCall_1_0ElementType() {
		return Definition_MethodNameIDTerminalRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_GuiLabelMethodAssignment_2ElementType() {
		return Definition_GuiLabelMethodAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_GuiLabelMethodSTRINGTerminalRuleCall_2_0ElementType() {
		return Definition_GuiLabelMethodSTRINGTerminalRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_GuiLabelParentAssignment_3ElementType() {
		return Definition_GuiLabelParentAssignment_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_GuiLabelParentSTRINGTerminalRuleCall_3_0ElementType() {
		return Definition_GuiLabelParentSTRINGTerminalRuleCall_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_GuiLabelChildAssignment_4ElementType() {
		return Definition_GuiLabelChildAssignment_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_GuiLabelChildSTRINGTerminalRuleCall_4_0ElementType() {
		return Definition_GuiLabelChildSTRINGTerminalRuleCall_4_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_LeftCurlyBracketKeyword_5ElementType() {
		return Definition_LeftCurlyBracketKeyword_5_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_DataAssignment_6ElementType() {
		return Definition_DataAssignment_6_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_DataDataParserRuleCall_6_0ElementType() {
		return Definition_DataDataParserRuleCall_6_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_InitSectionAssignment_7ElementType() {
		return Definition_InitSectionAssignment_7_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_InitSectionInitSectionParserRuleCall_7_0ElementType() {
		return Definition_InitSectionInitSectionParserRuleCall_7_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_RightCurlyBracketKeyword_8ElementType() {
		return Definition_RightCurlyBracketKeyword_8_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_EventuellTclProceduresAssignment_9ElementType() {
		return Definition_EventuellTclProceduresAssignment_9_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_EventuellTclProceduresAlternatives_9_0ElementType() {
		return Definition_EventuellTclProceduresAlternatives_9_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_EventuellTclProceduresIDTerminalRuleCall_9_0_0ElementType() {
		return Definition_EventuellTclProceduresIDTerminalRuleCall_9_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDefinition_EventuellTclProceduresANY_OTHERTerminalRuleCall_9_0_1ElementType() {
		return Definition_EventuellTclProceduresANY_OTHERTerminalRuleCall_9_0_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDataElementType() {
		return Data_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getData_GroupElementType() {
		return Data_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getData_DataKeyword_0ElementType() {
		return Data_DataKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getData_LeftCurlyBracketKeyword_1ElementType() {
		return Data_LeftCurlyBracketKeyword_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getData_Alternatives_2ElementType() {
		return Data_Alternatives_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getData_DEF_COMMENTTerminalRuleCall_2_0ElementType() {
		return Data_DEF_COMMENTTerminalRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getData_FieldDefinitionsAssignment_2_1ElementType() {
		return Data_FieldDefinitionsAssignment_2_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getData_FieldDefinitionsFieldDefinitionParserRuleCall_2_1_0ElementType() {
		return Data_FieldDefinitionsFieldDefinitionParserRuleCall_2_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getData_RightCurlyBracketKeyword_3ElementType() {
		return Data_RightCurlyBracketKeyword_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getInitSectionElementType() {
		return InitSection_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getInitSection_GroupElementType() {
		return InitSection_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getInitSection_InitKeyword_0ElementType() {
		return InitSection_InitKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getInitSection_LeftCurlyBracketKeyword_1ElementType() {
		return InitSection_LeftCurlyBracketKeyword_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getInitSection_Alternatives_2ElementType() {
		return InitSection_Alternatives_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getInitSection_DEF_COMMENTTerminalRuleCall_2_0ElementType() {
		return InitSection_DEF_COMMENTTerminalRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getInitSection_InitDefinitionsAssignment_2_1ElementType() {
		return InitSection_InitDefinitionsAssignment_2_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getInitSection_InitDefinitionsInitDefinitionParserRuleCall_2_1_0ElementType() {
		return InitSection_InitDefinitionsInitDefinitionParserRuleCall_2_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getInitSection_RightCurlyBracketKeyword_3ElementType() {
		return InitSection_RightCurlyBracketKeyword_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getInitDefinitionElementType() {
		return InitDefinition_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getInitDefinition_GroupElementType() {
		return InitDefinition_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getInitDefinition_InitFieldKeyword_0ElementType() {
		return InitDefinition_InitFieldKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getInitDefinition_IdAssignment_1ElementType() {
		return InitDefinition_IdAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getInitDefinition_IdIDTerminalRuleCall_1_0ElementType() {
		return InitDefinition_IdIDTerminalRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getInitDefinition_InitValueAssignment_2ElementType() {
		return InitDefinition_InitValueAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getInitDefinition_InitValueSTRINGTerminalRuleCall_2_0ElementType() {
		return InitDefinition_InitValueSTRINGTerminalRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFieldDefinitionElementType() {
		return FieldDefinition_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFieldDefinition_GroupElementType() {
		return FieldDefinition_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFieldDefinition_FieldTypeAssignment_0ElementType() {
		return FieldDefinition_FieldTypeAssignment_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFieldDefinition_FieldTypeFIELD_TYPEEnumRuleCall_0_0ElementType() {
		return FieldDefinition_FieldTypeFIELD_TYPEEnumRuleCall_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFieldDefinition_IdAssignment_1ElementType() {
		return FieldDefinition_IdAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFieldDefinition_IdIDTerminalRuleCall_1_0ElementType() {
		return FieldDefinition_IdIDTerminalRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFieldDefinition_NameAssignment_2ElementType() {
		return FieldDefinition_NameAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFieldDefinition_NameSTRINGTerminalRuleCall_2_0ElementType() {
		return FieldDefinition_NameSTRINGTerminalRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFieldDefinition_AccessAssignment_3ElementType() {
		return FieldDefinition_AccessAssignment_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFieldDefinition_AccessROLEEnumRuleCall_3_0ElementType() {
		return FieldDefinition_AccessROLEEnumRuleCall_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFieldDefinition_RecordClassAssignment_4ElementType() {
		return FieldDefinition_RecordClassAssignment_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFieldDefinition_RecordClassRECORDCLASSEnumRuleCall_4_0ElementType() {
		return FieldDefinition_RecordClassRECORDCLASSEnumRuleCall_4_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFieldDefinition_ColonKeyword_5ElementType() {
		return FieldDefinition_ColonKeyword_5_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFieldDefinition_FieldNameAssignment_6ElementType() {
		return FieldDefinition_FieldNameAssignment_6_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFieldDefinition_FieldNameIDTerminalRuleCall_6_0ElementType() {
		return FieldDefinition_FieldNameIDTerminalRuleCall_6_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFieldDefinition_LengthAssignment_7ElementType() {
		return FieldDefinition_LengthAssignment_7_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFieldDefinition_LengthINTTerminalRuleCall_7_0ElementType() {
		return FieldDefinition_LengthINTTerminalRuleCall_7_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFieldDefinition_OptionsAssignment_8ElementType() {
		return FieldDefinition_OptionsAssignment_8_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFieldDefinition_OptionsOptionParserRuleCall_8_0ElementType() {
		return FieldDefinition_OptionsOptionParserRuleCall_8_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionElementType() {
		return Option_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOption_AlternativesElementType() {
		return Option_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOption_OptionValprocParserRuleCall_0ElementType() {
		return Option_OptionValprocParserRuleCall_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOption_OptionStrictParserRuleCall_1ElementType() {
		return Option_OptionStrictParserRuleCall_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOption_OptionRangeParserRuleCall_2ElementType() {
		return Option_OptionRangeParserRuleCall_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOption_OptionContribParserRuleCall_3ElementType() {
		return Option_OptionContribParserRuleCall_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionValprocElementType() {
		return OptionValproc_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionValproc_GroupElementType() {
		return OptionValproc_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionValproc_ValprocAssignment_0ElementType() {
		return OptionValproc_ValprocAssignment_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionValproc_ValprocValprocKeyword_0_0ElementType() {
		return OptionValproc_ValprocValprocKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionValproc_TclProcAssignment_1ElementType() {
		return OptionValproc_TclProcAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionValproc_TclProcIDTerminalRuleCall_1_0ElementType() {
		return OptionValproc_TclProcIDTerminalRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionStrictElementType() {
		return OptionStrict_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionStrict_StrictAssignmentElementType() {
		return OptionStrict_StrictAssignment_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionStrict_StrictStrictKeyword_0ElementType() {
		return OptionStrict_StrictStrictKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionRangeElementType() {
		return OptionRange_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionRange_GroupElementType() {
		return OptionRange_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionRange_RangeKeyword_0ElementType() {
		return OptionRange_RangeKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionRange_ListKeyword_1ElementType() {
		return OptionRange_ListKeyword_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionRange_MinAssignment_2ElementType() {
		return OptionRange_MinAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionRange_MinINTTerminalRuleCall_2_0ElementType() {
		return OptionRange_MinINTTerminalRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionRange_MaxAssignment_3ElementType() {
		return OptionRange_MaxAssignment_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionRange_MaxINTTerminalRuleCall_3_0ElementType() {
		return OptionRange_MaxINTTerminalRuleCall_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionRange_RightSquareBracketKeyword_4ElementType() {
		return OptionRange_RightSquareBracketKeyword_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionContribElementType() {
		return OptionContrib_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionContrib_ContribAssignmentElementType() {
		return OptionContrib_ContribAssignment_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getOptionContrib_ContribContribKeyword_0ElementType() {
		return OptionContrib_ContribContribKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFIELD_TYPEElementType() {
		return FIELD_TYPE_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFIELD_TYPE_AlternativesElementType() {
		return FIELD_TYPE_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFIELD_TYPE_STRING_FIELDEnumLiteralDeclaration_0ElementType() {
		return FIELD_TYPE_STRING_FIELDEnumLiteralDeclaration_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFIELD_TYPE_STRING_FIELDStringFieldKeyword_0_0ElementType() {
		return FIELD_TYPE_STRING_FIELDStringFieldKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFIELD_TYPE_TIME_FIELDEnumLiteralDeclaration_1ElementType() {
		return FIELD_TYPE_TIME_FIELDEnumLiteralDeclaration_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFIELD_TYPE_TIME_FIELDTimeFieldKeyword_1_0ElementType() {
		return FIELD_TYPE_TIME_FIELDTimeFieldKeyword_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFIELD_TYPE_INTEGER_FIELDEnumLiteralDeclaration_2ElementType() {
		return FIELD_TYPE_INTEGER_FIELDEnumLiteralDeclaration_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFIELD_TYPE_INTEGER_FIELDIntegerFieldKeyword_2_0ElementType() {
		return FIELD_TYPE_INTEGER_FIELDIntegerFieldKeyword_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFIELD_TYPE_PRICE_FIELDEnumLiteralDeclaration_3ElementType() {
		return FIELD_TYPE_PRICE_FIELDEnumLiteralDeclaration_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFIELD_TYPE_PRICE_FIELDPriceFieldKeyword_3_0ElementType() {
		return FIELD_TYPE_PRICE_FIELDPriceFieldKeyword_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFIELD_TYPE_DOUBLE_FIELDEnumLiteralDeclaration_4ElementType() {
		return FIELD_TYPE_DOUBLE_FIELDEnumLiteralDeclaration_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFIELD_TYPE_DOUBLE_FIELDDoubleFieldKeyword_4_0ElementType() {
		return FIELD_TYPE_DOUBLE_FIELDDoubleFieldKeyword_4_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFIELD_TYPE_DATE_FIELDEnumLiteralDeclaration_5ElementType() {
		return FIELD_TYPE_DATE_FIELDEnumLiteralDeclaration_5_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFIELD_TYPE_DATE_FIELDDateFieldKeyword_5_0ElementType() {
		return FIELD_TYPE_DATE_FIELDDateFieldKeyword_5_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getROLEElementType() {
		return ROLE_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getROLE_AlternativesElementType() {
		return ROLE_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getROLE_RADMINEnumLiteralDeclaration_0ElementType() {
		return ROLE_RADMINEnumLiteralDeclaration_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getROLE_RADMINRadminKeyword_0_0ElementType() {
		return ROLE_RADMINRadminKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getROLE_NONEEnumLiteralDeclaration_1ElementType() {
		return ROLE_NONEEnumLiteralDeclaration_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getROLE_NONENoneKeyword_1_0ElementType() {
		return ROLE_NONENoneKeyword_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getROLE_RTRADEREnumLiteralDeclaration_2ElementType() {
		return ROLE_RTRADEREnumLiteralDeclaration_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getROLE_RTRADERRtraderKeyword_2_0ElementType() {
		return ROLE_RTRADERRtraderKeyword_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getROLE_SUPERVISOREnumLiteralDeclaration_3ElementType() {
		return ROLE_SUPERVISOREnumLiteralDeclaration_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getROLE_SUPERVISORSupervisorKeyword_3_0ElementType() {
		return ROLE_SUPERVISORSupervisorKeyword_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRECORDCLASSElementType() {
		return RECORDCLASS_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRECORDCLASS_AlternativesElementType() {
		return RECORDCLASS_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRECORDCLASS_METHOD_READ_ONLYEnumLiteralDeclaration_0ElementType() {
		return RECORDCLASS_METHOD_READ_ONLYEnumLiteralDeclaration_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRECORDCLASS_METHOD_READ_ONLYBKeyword_0_0ElementType() {
		return RECORDCLASS_METHOD_READ_ONLYBKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRECORDCLASS_PARENT_READ_ONLYEnumLiteralDeclaration_1ElementType() {
		return RECORDCLASS_PARENT_READ_ONLYEnumLiteralDeclaration_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRECORDCLASS_PARENT_READ_ONLYUKeyword_1_0ElementType() {
		return RECORDCLASS_PARENT_READ_ONLYUKeyword_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRECORDCLASS_PARENT_READ_WRITEEnumLiteralDeclaration_2ElementType() {
		return RECORDCLASS_PARENT_READ_WRITEEnumLiteralDeclaration_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRECORDCLASS_PARENT_READ_WRITEGKeyword_2_0ElementType() {
		return RECORDCLASS_PARENT_READ_WRITEGKeyword_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRECORDCLASS_PARENT_READ_REFERENCEEnumLiteralDeclaration_3ElementType() {
		return RECORDCLASS_PARENT_READ_REFERENCEEnumLiteralDeclaration_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRECORDCLASS_PARENT_READ_REFERENCERKeyword_3_0ElementType() {
		return RECORDCLASS_PARENT_READ_REFERENCERKeyword_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRECORDCLASS_CHILD_READ_ONLYEnumLiteralDeclaration_4ElementType() {
		return RECORDCLASS_CHILD_READ_ONLYEnumLiteralDeclaration_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRECORDCLASS_CHILD_READ_ONLYDKeyword_4_0ElementType() {
		return RECORDCLASS_CHILD_READ_ONLYDKeyword_4_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRECORDCLASS_CHILD_READ_WRITEEnumLiteralDeclaration_5ElementType() {
		return RECORDCLASS_CHILD_READ_WRITEEnumLiteralDeclaration_5_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRECORDCLASS_CHILD_READ_WRITEPKeyword_5_0ElementType() {
		return RECORDCLASS_CHILD_READ_WRITEPKeyword_5_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRECORDCLASS_CHILD_READ_REFERENCEEnumLiteralDeclaration_6ElementType() {
		return RECORDCLASS_CHILD_READ_REFERENCEEnumLiteralDeclaration_6_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRECORDCLASS_CHILD_READ_REFERENCESKeyword_6_0ElementType() {
		return RECORDCLASS_CHILD_READ_REFERENCESKeyword_6_0_ELEMENT_TYPE;
	}

}
