/**
 * generated by Xtext 2.9.2
 */
package ch.raiffeisen.ipricer.definition.definitionDSL.impl;

import ch.raiffeisen.ipricer.definition.definitionDSL.Data;
import ch.raiffeisen.ipricer.definition.definitionDSL.Definition;
import ch.raiffeisen.ipricer.definition.definitionDSL.DefinitionDSLFactory;
import ch.raiffeisen.ipricer.definition.definitionDSL.DefinitionDSLPackage;
import ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition;
import ch.raiffeisen.ipricer.definition.definitionDSL.InitDefinition;
import ch.raiffeisen.ipricer.definition.definitionDSL.InitSection;
import ch.raiffeisen.ipricer.definition.definitionDSL.Option;
import ch.raiffeisen.ipricer.definition.definitionDSL.OptionContrib;
import ch.raiffeisen.ipricer.definition.definitionDSL.OptionListSection;
import ch.raiffeisen.ipricer.definition.definitionDSL.OptionMaskSection;
import ch.raiffeisen.ipricer.definition.definitionDSL.OptionRange;
import ch.raiffeisen.ipricer.definition.definitionDSL.OptionStrict;
import ch.raiffeisen.ipricer.definition.definitionDSL.OptionValproc;
import ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskDefinition;
import ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskSection;
import ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListDefintion;
import ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListSection;
import ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingMaskDefinition;
import ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingMaskSection;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class DefinitionDSLPackageImpl extends EPackageImpl implements DefinitionDSLPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass definitionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dataEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass initSectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass typeMaskSectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass underlyingMaskSectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass underlyingListSectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass optionListSectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass optionMaskSectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass underlyingListDefintionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass typeMaskDefinitionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass underlyingMaskDefinitionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass initDefinitionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fieldDefinitionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass optionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass optionValprocEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass optionStrictEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass optionRangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass optionContribEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum fielD_TYPEEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum roleEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum recordclassEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see ch.raiffeisen.ipricer.definition.definitionDSL.DefinitionDSLPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private DefinitionDSLPackageImpl()
  {
    super(eNS_URI, DefinitionDSLFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link DefinitionDSLPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static DefinitionDSLPackage init()
  {
    if (isInited) return (DefinitionDSLPackage)EPackage.Registry.INSTANCE.getEPackage(DefinitionDSLPackage.eNS_URI);

    // Obtain or create and register package
    DefinitionDSLPackageImpl theDefinitionDSLPackage = (DefinitionDSLPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof DefinitionDSLPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new DefinitionDSLPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theDefinitionDSLPackage.createPackageContents();

    // Initialize created meta-data
    theDefinitionDSLPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theDefinitionDSLPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(DefinitionDSLPackage.eNS_URI, theDefinitionDSLPackage);
    return theDefinitionDSLPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDefinition()
  {
    return definitionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDefinition_MethodName()
  {
    return (EAttribute)definitionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDefinition_GuiLabelMethod()
  {
    return (EAttribute)definitionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDefinition_GuiLabelParent()
  {
    return (EAttribute)definitionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDefinition_GuiLabelChild()
  {
    return (EAttribute)definitionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDefinition_Data()
  {
    return (EReference)definitionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDefinition_InitSection()
  {
    return (EReference)definitionEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDefinition_TypeMaskSection()
  {
    return (EReference)definitionEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDefinition_UnderlyingListSection()
  {
    return (EReference)definitionEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDefinition_UnderlyingMaskSection()
  {
    return (EReference)definitionEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDefinition_OptionListSection()
  {
    return (EReference)definitionEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDefinition_OptionListLabelSection()
  {
    return (EAttribute)definitionEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDefinition_OptionMaskSection()
  {
    return (EReference)definitionEClass.getEStructuralFeatures().get(11);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDefinition_EventuellTclProcedures()
  {
    return (EAttribute)definitionEClass.getEStructuralFeatures().get(12);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getData()
  {
    return dataEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getData_FieldDefinitions()
  {
    return (EReference)dataEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getInitSection()
  {
    return initSectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getInitSection_InitDefinitions()
  {
    return (EReference)initSectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTypeMaskSection()
  {
    return typeMaskSectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getTypeMaskSection_TypeMaskDefinitions()
  {
    return (EReference)typeMaskSectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getUnderlyingMaskSection()
  {
    return underlyingMaskSectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getUnderlyingMaskSection_UnderlyingMaskDefinitions()
  {
    return (EReference)underlyingMaskSectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getUnderlyingListSection()
  {
    return underlyingListSectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getUnderlyingListSection_UnderlyingListDefinitions()
  {
    return (EReference)underlyingListSectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getOptionListSection()
  {
    return optionListSectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getOptionListSection_OptionListDefinitions()
  {
    return (EReference)optionListSectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getOptionMaskSection()
  {
    return optionMaskSectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getOptionMaskSection_OptionMaskDefinitions()
  {
    return (EReference)optionMaskSectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getUnderlyingListDefintion()
  {
    return underlyingListDefintionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getUnderlyingListDefintion_Id()
  {
    return (EAttribute)underlyingListDefintionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getUnderlyingListDefintion_Width()
  {
    return (EAttribute)underlyingListDefintionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getUnderlyingListDefintion_Title()
  {
    return (EAttribute)underlyingListDefintionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTypeMaskDefinition()
  {
    return typeMaskDefinitionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTypeMaskDefinition_Id()
  {
    return (EAttribute)typeMaskDefinitionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTypeMaskDefinition_Row()
  {
    return (EAttribute)typeMaskDefinitionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTypeMaskDefinition_Col()
  {
    return (EAttribute)typeMaskDefinitionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTypeMaskDefinition_Width()
  {
    return (EAttribute)typeMaskDefinitionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTypeMaskDefinition_Separator()
  {
    return (EAttribute)typeMaskDefinitionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getUnderlyingMaskDefinition()
  {
    return underlyingMaskDefinitionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getUnderlyingMaskDefinition_Id()
  {
    return (EAttribute)underlyingMaskDefinitionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getUnderlyingMaskDefinition_Row()
  {
    return (EAttribute)underlyingMaskDefinitionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getUnderlyingMaskDefinition_Col()
  {
    return (EAttribute)underlyingMaskDefinitionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getUnderlyingMaskDefinition_Width()
  {
    return (EAttribute)underlyingMaskDefinitionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getUnderlyingMaskDefinition_Separator()
  {
    return (EAttribute)underlyingMaskDefinitionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getInitDefinition()
  {
    return initDefinitionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getInitDefinition_Id()
  {
    return (EAttribute)initDefinitionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getInitDefinition_InitValue()
  {
    return (EAttribute)initDefinitionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFieldDefinition()
  {
    return fieldDefinitionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFieldDefinition_FieldType()
  {
    return (EAttribute)fieldDefinitionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFieldDefinition_Id()
  {
    return (EAttribute)fieldDefinitionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFieldDefinition_Name()
  {
    return (EAttribute)fieldDefinitionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFieldDefinition_Access()
  {
    return (EAttribute)fieldDefinitionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFieldDefinition_RecordClass()
  {
    return (EAttribute)fieldDefinitionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFieldDefinition_FieldName()
  {
    return (EAttribute)fieldDefinitionEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFieldDefinition_Length()
  {
    return (EAttribute)fieldDefinitionEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFieldDefinition_Options()
  {
    return (EReference)fieldDefinitionEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getOption()
  {
    return optionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getOptionValproc()
  {
    return optionValprocEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getOptionValproc_Valproc()
  {
    return (EAttribute)optionValprocEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getOptionValproc_TclProc()
  {
    return (EAttribute)optionValprocEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getOptionStrict()
  {
    return optionStrictEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getOptionStrict_Strict()
  {
    return (EAttribute)optionStrictEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getOptionRange()
  {
    return optionRangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getOptionRange_Min()
  {
    return (EAttribute)optionRangeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getOptionRange_Max()
  {
    return (EAttribute)optionRangeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getOptionContrib()
  {
    return optionContribEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getOptionContrib_Contrib()
  {
    return (EAttribute)optionContribEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getFIELD_TYPE()
  {
    return fielD_TYPEEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getROLE()
  {
    return roleEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getRECORDCLASS()
  {
    return recordclassEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DefinitionDSLFactory getDefinitionDSLFactory()
  {
    return (DefinitionDSLFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    definitionEClass = createEClass(DEFINITION);
    createEAttribute(definitionEClass, DEFINITION__METHOD_NAME);
    createEAttribute(definitionEClass, DEFINITION__GUI_LABEL_METHOD);
    createEAttribute(definitionEClass, DEFINITION__GUI_LABEL_PARENT);
    createEAttribute(definitionEClass, DEFINITION__GUI_LABEL_CHILD);
    createEReference(definitionEClass, DEFINITION__DATA);
    createEReference(definitionEClass, DEFINITION__INIT_SECTION);
    createEReference(definitionEClass, DEFINITION__TYPE_MASK_SECTION);
    createEReference(definitionEClass, DEFINITION__UNDERLYING_LIST_SECTION);
    createEReference(definitionEClass, DEFINITION__UNDERLYING_MASK_SECTION);
    createEReference(definitionEClass, DEFINITION__OPTION_LIST_SECTION);
    createEAttribute(definitionEClass, DEFINITION__OPTION_LIST_LABEL_SECTION);
    createEReference(definitionEClass, DEFINITION__OPTION_MASK_SECTION);
    createEAttribute(definitionEClass, DEFINITION__EVENTUELL_TCL_PROCEDURES);

    dataEClass = createEClass(DATA);
    createEReference(dataEClass, DATA__FIELD_DEFINITIONS);

    initSectionEClass = createEClass(INIT_SECTION);
    createEReference(initSectionEClass, INIT_SECTION__INIT_DEFINITIONS);

    typeMaskSectionEClass = createEClass(TYPE_MASK_SECTION);
    createEReference(typeMaskSectionEClass, TYPE_MASK_SECTION__TYPE_MASK_DEFINITIONS);

    underlyingMaskSectionEClass = createEClass(UNDERLYING_MASK_SECTION);
    createEReference(underlyingMaskSectionEClass, UNDERLYING_MASK_SECTION__UNDERLYING_MASK_DEFINITIONS);

    underlyingListSectionEClass = createEClass(UNDERLYING_LIST_SECTION);
    createEReference(underlyingListSectionEClass, UNDERLYING_LIST_SECTION__UNDERLYING_LIST_DEFINITIONS);

    optionListSectionEClass = createEClass(OPTION_LIST_SECTION);
    createEReference(optionListSectionEClass, OPTION_LIST_SECTION__OPTION_LIST_DEFINITIONS);

    optionMaskSectionEClass = createEClass(OPTION_MASK_SECTION);
    createEReference(optionMaskSectionEClass, OPTION_MASK_SECTION__OPTION_MASK_DEFINITIONS);

    underlyingListDefintionEClass = createEClass(UNDERLYING_LIST_DEFINTION);
    createEAttribute(underlyingListDefintionEClass, UNDERLYING_LIST_DEFINTION__ID);
    createEAttribute(underlyingListDefintionEClass, UNDERLYING_LIST_DEFINTION__WIDTH);
    createEAttribute(underlyingListDefintionEClass, UNDERLYING_LIST_DEFINTION__TITLE);

    typeMaskDefinitionEClass = createEClass(TYPE_MASK_DEFINITION);
    createEAttribute(typeMaskDefinitionEClass, TYPE_MASK_DEFINITION__ID);
    createEAttribute(typeMaskDefinitionEClass, TYPE_MASK_DEFINITION__ROW);
    createEAttribute(typeMaskDefinitionEClass, TYPE_MASK_DEFINITION__COL);
    createEAttribute(typeMaskDefinitionEClass, TYPE_MASK_DEFINITION__WIDTH);
    createEAttribute(typeMaskDefinitionEClass, TYPE_MASK_DEFINITION__SEPARATOR);

    underlyingMaskDefinitionEClass = createEClass(UNDERLYING_MASK_DEFINITION);
    createEAttribute(underlyingMaskDefinitionEClass, UNDERLYING_MASK_DEFINITION__ID);
    createEAttribute(underlyingMaskDefinitionEClass, UNDERLYING_MASK_DEFINITION__ROW);
    createEAttribute(underlyingMaskDefinitionEClass, UNDERLYING_MASK_DEFINITION__COL);
    createEAttribute(underlyingMaskDefinitionEClass, UNDERLYING_MASK_DEFINITION__WIDTH);
    createEAttribute(underlyingMaskDefinitionEClass, UNDERLYING_MASK_DEFINITION__SEPARATOR);

    initDefinitionEClass = createEClass(INIT_DEFINITION);
    createEAttribute(initDefinitionEClass, INIT_DEFINITION__ID);
    createEAttribute(initDefinitionEClass, INIT_DEFINITION__INIT_VALUE);

    fieldDefinitionEClass = createEClass(FIELD_DEFINITION);
    createEAttribute(fieldDefinitionEClass, FIELD_DEFINITION__FIELD_TYPE);
    createEAttribute(fieldDefinitionEClass, FIELD_DEFINITION__ID);
    createEAttribute(fieldDefinitionEClass, FIELD_DEFINITION__NAME);
    createEAttribute(fieldDefinitionEClass, FIELD_DEFINITION__ACCESS);
    createEAttribute(fieldDefinitionEClass, FIELD_DEFINITION__RECORD_CLASS);
    createEAttribute(fieldDefinitionEClass, FIELD_DEFINITION__FIELD_NAME);
    createEAttribute(fieldDefinitionEClass, FIELD_DEFINITION__LENGTH);
    createEReference(fieldDefinitionEClass, FIELD_DEFINITION__OPTIONS);

    optionEClass = createEClass(OPTION);

    optionValprocEClass = createEClass(OPTION_VALPROC);
    createEAttribute(optionValprocEClass, OPTION_VALPROC__VALPROC);
    createEAttribute(optionValprocEClass, OPTION_VALPROC__TCL_PROC);

    optionStrictEClass = createEClass(OPTION_STRICT);
    createEAttribute(optionStrictEClass, OPTION_STRICT__STRICT);

    optionRangeEClass = createEClass(OPTION_RANGE);
    createEAttribute(optionRangeEClass, OPTION_RANGE__MIN);
    createEAttribute(optionRangeEClass, OPTION_RANGE__MAX);

    optionContribEClass = createEClass(OPTION_CONTRIB);
    createEAttribute(optionContribEClass, OPTION_CONTRIB__CONTRIB);

    // Create enums
    fielD_TYPEEEnum = createEEnum(FIELD_TYPE);
    roleEEnum = createEEnum(ROLE);
    recordclassEEnum = createEEnum(RECORDCLASS);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    optionValprocEClass.getESuperTypes().add(this.getOption());
    optionStrictEClass.getESuperTypes().add(this.getOption());
    optionRangeEClass.getESuperTypes().add(this.getOption());
    optionContribEClass.getESuperTypes().add(this.getOption());

    // Initialize classes and features; add operations and parameters
    initEClass(definitionEClass, Definition.class, "Definition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDefinition_MethodName(), ecorePackage.getEString(), "methodName", null, 0, 1, Definition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDefinition_GuiLabelMethod(), ecorePackage.getEString(), "guiLabelMethod", null, 0, 1, Definition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDefinition_GuiLabelParent(), ecorePackage.getEString(), "guiLabelParent", null, 0, 1, Definition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDefinition_GuiLabelChild(), ecorePackage.getEString(), "guiLabelChild", null, 0, 1, Definition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDefinition_Data(), this.getData(), null, "data", null, 0, 1, Definition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDefinition_InitSection(), this.getInitSection(), null, "initSection", null, 0, 1, Definition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDefinition_TypeMaskSection(), this.getTypeMaskSection(), null, "typeMaskSection", null, 0, 1, Definition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDefinition_UnderlyingListSection(), this.getUnderlyingListSection(), null, "underlyingListSection", null, 0, 1, Definition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDefinition_UnderlyingMaskSection(), this.getUnderlyingMaskSection(), null, "underlyingMaskSection", null, 0, 1, Definition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDefinition_OptionListSection(), this.getOptionListSection(), null, "optionListSection", null, 0, 1, Definition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDefinition_OptionListLabelSection(), ecorePackage.getEString(), "optionListLabelSection", null, 0, 1, Definition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDefinition_OptionMaskSection(), this.getOptionMaskSection(), null, "optionMaskSection", null, 0, 1, Definition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDefinition_EventuellTclProcedures(), ecorePackage.getEString(), "eventuellTclProcedures", null, 0, -1, Definition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dataEClass, Data.class, "Data", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getData_FieldDefinitions(), this.getFieldDefinition(), null, "fieldDefinitions", null, 0, -1, Data.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(initSectionEClass, InitSection.class, "InitSection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getInitSection_InitDefinitions(), this.getInitDefinition(), null, "initDefinitions", null, 0, -1, InitSection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(typeMaskSectionEClass, TypeMaskSection.class, "TypeMaskSection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getTypeMaskSection_TypeMaskDefinitions(), this.getTypeMaskDefinition(), null, "typeMaskDefinitions", null, 0, -1, TypeMaskSection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(underlyingMaskSectionEClass, UnderlyingMaskSection.class, "UnderlyingMaskSection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getUnderlyingMaskSection_UnderlyingMaskDefinitions(), this.getTypeMaskDefinition(), null, "underlyingMaskDefinitions", null, 0, -1, UnderlyingMaskSection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(underlyingListSectionEClass, UnderlyingListSection.class, "UnderlyingListSection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getUnderlyingListSection_UnderlyingListDefinitions(), this.getUnderlyingListDefintion(), null, "underlyingListDefinitions", null, 0, -1, UnderlyingListSection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(optionListSectionEClass, OptionListSection.class, "OptionListSection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOptionListSection_OptionListDefinitions(), this.getUnderlyingListDefintion(), null, "optionListDefinitions", null, 0, -1, OptionListSection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(optionMaskSectionEClass, OptionMaskSection.class, "OptionMaskSection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOptionMaskSection_OptionMaskDefinitions(), this.getTypeMaskDefinition(), null, "optionMaskDefinitions", null, 0, -1, OptionMaskSection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(underlyingListDefintionEClass, UnderlyingListDefintion.class, "UnderlyingListDefintion", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUnderlyingListDefintion_Id(), ecorePackage.getEString(), "id", null, 0, 1, UnderlyingListDefintion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnderlyingListDefintion_Width(), ecorePackage.getEInt(), "width", null, 0, 1, UnderlyingListDefintion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnderlyingListDefintion_Title(), ecorePackage.getEString(), "title", null, 0, 1, UnderlyingListDefintion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(typeMaskDefinitionEClass, TypeMaskDefinition.class, "TypeMaskDefinition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTypeMaskDefinition_Id(), ecorePackage.getEString(), "id", null, 0, 1, TypeMaskDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTypeMaskDefinition_Row(), ecorePackage.getEInt(), "row", null, 0, 1, TypeMaskDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTypeMaskDefinition_Col(), ecorePackage.getEInt(), "col", null, 0, 1, TypeMaskDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTypeMaskDefinition_Width(), ecorePackage.getEInt(), "width", null, 0, 1, TypeMaskDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTypeMaskDefinition_Separator(), ecorePackage.getEString(), "separator", null, 0, 1, TypeMaskDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(underlyingMaskDefinitionEClass, UnderlyingMaskDefinition.class, "UnderlyingMaskDefinition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUnderlyingMaskDefinition_Id(), ecorePackage.getEString(), "id", null, 0, 1, UnderlyingMaskDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnderlyingMaskDefinition_Row(), ecorePackage.getEInt(), "row", null, 0, 1, UnderlyingMaskDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnderlyingMaskDefinition_Col(), ecorePackage.getEInt(), "col", null, 0, 1, UnderlyingMaskDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnderlyingMaskDefinition_Width(), ecorePackage.getEInt(), "width", null, 0, 1, UnderlyingMaskDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnderlyingMaskDefinition_Separator(), ecorePackage.getEString(), "separator", null, 0, 1, UnderlyingMaskDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(initDefinitionEClass, InitDefinition.class, "InitDefinition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getInitDefinition_Id(), ecorePackage.getEString(), "id", null, 0, 1, InitDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getInitDefinition_InitValue(), ecorePackage.getEString(), "initValue", null, 0, 1, InitDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fieldDefinitionEClass, FieldDefinition.class, "FieldDefinition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFieldDefinition_FieldType(), this.getFIELD_TYPE(), "fieldType", null, 0, 1, FieldDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFieldDefinition_Id(), ecorePackage.getEString(), "id", null, 0, 1, FieldDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFieldDefinition_Name(), ecorePackage.getEString(), "name", null, 0, 1, FieldDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFieldDefinition_Access(), this.getROLE(), "access", null, 0, 1, FieldDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFieldDefinition_RecordClass(), this.getRECORDCLASS(), "recordClass", null, 0, 1, FieldDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFieldDefinition_FieldName(), ecorePackage.getEString(), "fieldName", null, 0, 1, FieldDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFieldDefinition_Length(), ecorePackage.getEInt(), "length", null, 0, 1, FieldDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFieldDefinition_Options(), this.getOption(), null, "options", null, 0, -1, FieldDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(optionEClass, Option.class, "Option", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(optionValprocEClass, OptionValproc.class, "OptionValproc", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getOptionValproc_Valproc(), ecorePackage.getEString(), "valproc", null, 0, 1, OptionValproc.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getOptionValproc_TclProc(), ecorePackage.getEString(), "tclProc", null, 0, 1, OptionValproc.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(optionStrictEClass, OptionStrict.class, "OptionStrict", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getOptionStrict_Strict(), ecorePackage.getEBoolean(), "strict", null, 0, 1, OptionStrict.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(optionRangeEClass, OptionRange.class, "OptionRange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getOptionRange_Min(), ecorePackage.getEInt(), "min", null, 0, 1, OptionRange.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getOptionRange_Max(), ecorePackage.getEInt(), "max", null, 0, 1, OptionRange.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(optionContribEClass, OptionContrib.class, "OptionContrib", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getOptionContrib_Contrib(), ecorePackage.getEBoolean(), "contrib", null, 0, 1, OptionContrib.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(fielD_TYPEEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.FIELD_TYPE.class, "FIELD_TYPE");
    addEEnumLiteral(fielD_TYPEEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.FIELD_TYPE.STRING_FIELD);
    addEEnumLiteral(fielD_TYPEEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.FIELD_TYPE.TIME_FIELD);
    addEEnumLiteral(fielD_TYPEEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.FIELD_TYPE.INTEGER_FIELD);
    addEEnumLiteral(fielD_TYPEEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.FIELD_TYPE.PRICE_FIELD);
    addEEnumLiteral(fielD_TYPEEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.FIELD_TYPE.DOUBLE_FIELD);
    addEEnumLiteral(fielD_TYPEEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.FIELD_TYPE.ZAHL_FIELD);
    addEEnumLiteral(fielD_TYPEEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.FIELD_TYPE.DATE_FIELD);

    initEEnum(roleEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.ROLE.class, "ROLE");
    addEEnumLiteral(roleEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.ROLE.RADMIN);
    addEEnumLiteral(roleEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.ROLE.NONE);
    addEEnumLiteral(roleEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.ROLE.RTRADER);
    addEEnumLiteral(roleEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.ROLE.SUPERVISOR);

    initEEnum(recordclassEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.RECORDCLASS.class, "RECORDCLASS");
    addEEnumLiteral(recordclassEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.RECORDCLASS.METHOD_READ_ONLY);
    addEEnumLiteral(recordclassEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.RECORDCLASS.PARENT_READ_ONLY);
    addEEnumLiteral(recordclassEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.RECORDCLASS.PARENT_READ_WRITE);
    addEEnumLiteral(recordclassEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.RECORDCLASS.PARENT_READ_REFERENCE);
    addEEnumLiteral(recordclassEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.RECORDCLASS.CHILD_READ_ONLY);
    addEEnumLiteral(recordclassEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.RECORDCLASS.CHILD_READ_WRITE);
    addEEnumLiteral(recordclassEEnum, ch.raiffeisen.ipricer.definition.definitionDSL.RECORDCLASS.CHILD_READ_REFERENCE);

    // Create resource
    createResource(eNS_URI);
  }

} //DefinitionDSLPackageImpl
