/**
 * generated by Xtext 2.9.2
 */
package ch.raiffeisen.ipricer.definition.definitionDSL.impl;

import ch.raiffeisen.ipricer.definition.definitionDSL.DefinitionDSLPackage;
import ch.raiffeisen.ipricer.definition.definitionDSL.FIELD_TYPE;
import ch.raiffeisen.ipricer.definition.definitionDSL.FieldDefinition;
import ch.raiffeisen.ipricer.definition.definitionDSL.Option;
import ch.raiffeisen.ipricer.definition.definitionDSL.RECORDCLASS;
import ch.raiffeisen.ipricer.definition.definitionDSL.ROLE;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Field Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.FieldDefinitionImpl#getFieldType <em>Field Type</em>}</li>
 *   <li>{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.FieldDefinitionImpl#getId <em>Id</em>}</li>
 *   <li>{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.FieldDefinitionImpl#getName <em>Name</em>}</li>
 *   <li>{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.FieldDefinitionImpl#getAccess <em>Access</em>}</li>
 *   <li>{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.FieldDefinitionImpl#getRecordClass <em>Record Class</em>}</li>
 *   <li>{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.FieldDefinitionImpl#getFieldName <em>Field Name</em>}</li>
 *   <li>{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.FieldDefinitionImpl#getLength <em>Length</em>}</li>
 *   <li>{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.FieldDefinitionImpl#getOptions <em>Options</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FieldDefinitionImpl extends MinimalEObjectImpl.Container implements FieldDefinition
{
  /**
   * The default value of the '{@link #getFieldType() <em>Field Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFieldType()
   * @generated
   * @ordered
   */
  protected static final FIELD_TYPE FIELD_TYPE_EDEFAULT = FIELD_TYPE.STRING_FIELD;

  /**
   * The cached value of the '{@link #getFieldType() <em>Field Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFieldType()
   * @generated
   * @ordered
   */
  protected FIELD_TYPE fieldType = FIELD_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected static final String ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected String id = ID_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getAccess() <em>Access</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAccess()
   * @generated
   * @ordered
   */
  protected static final ROLE ACCESS_EDEFAULT = ROLE.RADMIN;

  /**
   * The cached value of the '{@link #getAccess() <em>Access</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAccess()
   * @generated
   * @ordered
   */
  protected ROLE access = ACCESS_EDEFAULT;

  /**
   * The default value of the '{@link #getRecordClass() <em>Record Class</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRecordClass()
   * @generated
   * @ordered
   */
  protected static final RECORDCLASS RECORD_CLASS_EDEFAULT = RECORDCLASS.METHOD_READ_ONLY;

  /**
   * The cached value of the '{@link #getRecordClass() <em>Record Class</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRecordClass()
   * @generated
   * @ordered
   */
  protected RECORDCLASS recordClass = RECORD_CLASS_EDEFAULT;

  /**
   * The default value of the '{@link #getFieldName() <em>Field Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFieldName()
   * @generated
   * @ordered
   */
  protected static final String FIELD_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFieldName() <em>Field Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFieldName()
   * @generated
   * @ordered
   */
  protected String fieldName = FIELD_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getLength() <em>Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLength()
   * @generated
   * @ordered
   */
  protected static final int LENGTH_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getLength() <em>Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLength()
   * @generated
   * @ordered
   */
  protected int length = LENGTH_EDEFAULT;

  /**
   * The cached value of the '{@link #getOptions() <em>Options</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOptions()
   * @generated
   * @ordered
   */
  protected EList<Option> options;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FieldDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DefinitionDSLPackage.Literals.FIELD_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FIELD_TYPE getFieldType()
  {
    return fieldType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFieldType(FIELD_TYPE newFieldType)
  {
    FIELD_TYPE oldFieldType = fieldType;
    fieldType = newFieldType == null ? FIELD_TYPE_EDEFAULT : newFieldType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DefinitionDSLPackage.FIELD_DEFINITION__FIELD_TYPE, oldFieldType, fieldType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getId()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setId(String newId)
  {
    String oldId = id;
    id = newId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DefinitionDSLPackage.FIELD_DEFINITION__ID, oldId, id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DefinitionDSLPackage.FIELD_DEFINITION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ROLE getAccess()
  {
    return access;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAccess(ROLE newAccess)
  {
    ROLE oldAccess = access;
    access = newAccess == null ? ACCESS_EDEFAULT : newAccess;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DefinitionDSLPackage.FIELD_DEFINITION__ACCESS, oldAccess, access));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RECORDCLASS getRecordClass()
  {
    return recordClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRecordClass(RECORDCLASS newRecordClass)
  {
    RECORDCLASS oldRecordClass = recordClass;
    recordClass = newRecordClass == null ? RECORD_CLASS_EDEFAULT : newRecordClass;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DefinitionDSLPackage.FIELD_DEFINITION__RECORD_CLASS, oldRecordClass, recordClass));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getFieldName()
  {
    return fieldName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFieldName(String newFieldName)
  {
    String oldFieldName = fieldName;
    fieldName = newFieldName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DefinitionDSLPackage.FIELD_DEFINITION__FIELD_NAME, oldFieldName, fieldName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getLength()
  {
    return length;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLength(int newLength)
  {
    int oldLength = length;
    length = newLength;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DefinitionDSLPackage.FIELD_DEFINITION__LENGTH, oldLength, length));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Option> getOptions()
  {
    if (options == null)
    {
      options = new EObjectContainmentEList<Option>(Option.class, this, DefinitionDSLPackage.FIELD_DEFINITION__OPTIONS);
    }
    return options;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DefinitionDSLPackage.FIELD_DEFINITION__OPTIONS:
        return ((InternalEList<?>)getOptions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DefinitionDSLPackage.FIELD_DEFINITION__FIELD_TYPE:
        return getFieldType();
      case DefinitionDSLPackage.FIELD_DEFINITION__ID:
        return getId();
      case DefinitionDSLPackage.FIELD_DEFINITION__NAME:
        return getName();
      case DefinitionDSLPackage.FIELD_DEFINITION__ACCESS:
        return getAccess();
      case DefinitionDSLPackage.FIELD_DEFINITION__RECORD_CLASS:
        return getRecordClass();
      case DefinitionDSLPackage.FIELD_DEFINITION__FIELD_NAME:
        return getFieldName();
      case DefinitionDSLPackage.FIELD_DEFINITION__LENGTH:
        return getLength();
      case DefinitionDSLPackage.FIELD_DEFINITION__OPTIONS:
        return getOptions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DefinitionDSLPackage.FIELD_DEFINITION__FIELD_TYPE:
        setFieldType((FIELD_TYPE)newValue);
        return;
      case DefinitionDSLPackage.FIELD_DEFINITION__ID:
        setId((String)newValue);
        return;
      case DefinitionDSLPackage.FIELD_DEFINITION__NAME:
        setName((String)newValue);
        return;
      case DefinitionDSLPackage.FIELD_DEFINITION__ACCESS:
        setAccess((ROLE)newValue);
        return;
      case DefinitionDSLPackage.FIELD_DEFINITION__RECORD_CLASS:
        setRecordClass((RECORDCLASS)newValue);
        return;
      case DefinitionDSLPackage.FIELD_DEFINITION__FIELD_NAME:
        setFieldName((String)newValue);
        return;
      case DefinitionDSLPackage.FIELD_DEFINITION__LENGTH:
        setLength((Integer)newValue);
        return;
      case DefinitionDSLPackage.FIELD_DEFINITION__OPTIONS:
        getOptions().clear();
        getOptions().addAll((Collection<? extends Option>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DefinitionDSLPackage.FIELD_DEFINITION__FIELD_TYPE:
        setFieldType(FIELD_TYPE_EDEFAULT);
        return;
      case DefinitionDSLPackage.FIELD_DEFINITION__ID:
        setId(ID_EDEFAULT);
        return;
      case DefinitionDSLPackage.FIELD_DEFINITION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case DefinitionDSLPackage.FIELD_DEFINITION__ACCESS:
        setAccess(ACCESS_EDEFAULT);
        return;
      case DefinitionDSLPackage.FIELD_DEFINITION__RECORD_CLASS:
        setRecordClass(RECORD_CLASS_EDEFAULT);
        return;
      case DefinitionDSLPackage.FIELD_DEFINITION__FIELD_NAME:
        setFieldName(FIELD_NAME_EDEFAULT);
        return;
      case DefinitionDSLPackage.FIELD_DEFINITION__LENGTH:
        setLength(LENGTH_EDEFAULT);
        return;
      case DefinitionDSLPackage.FIELD_DEFINITION__OPTIONS:
        getOptions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DefinitionDSLPackage.FIELD_DEFINITION__FIELD_TYPE:
        return fieldType != FIELD_TYPE_EDEFAULT;
      case DefinitionDSLPackage.FIELD_DEFINITION__ID:
        return ID_EDEFAULT == null ? id != null : !ID_EDEFAULT.equals(id);
      case DefinitionDSLPackage.FIELD_DEFINITION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case DefinitionDSLPackage.FIELD_DEFINITION__ACCESS:
        return access != ACCESS_EDEFAULT;
      case DefinitionDSLPackage.FIELD_DEFINITION__RECORD_CLASS:
        return recordClass != RECORD_CLASS_EDEFAULT;
      case DefinitionDSLPackage.FIELD_DEFINITION__FIELD_NAME:
        return FIELD_NAME_EDEFAULT == null ? fieldName != null : !FIELD_NAME_EDEFAULT.equals(fieldName);
      case DefinitionDSLPackage.FIELD_DEFINITION__LENGTH:
        return length != LENGTH_EDEFAULT;
      case DefinitionDSLPackage.FIELD_DEFINITION__OPTIONS:
        return options != null && !options.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (fieldType: ");
    result.append(fieldType);
    result.append(", id: ");
    result.append(id);
    result.append(", name: ");
    result.append(name);
    result.append(", access: ");
    result.append(access);
    result.append(", recordClass: ");
    result.append(recordClass);
    result.append(", fieldName: ");
    result.append(fieldName);
    result.append(", length: ");
    result.append(length);
    result.append(')');
    return result.toString();
  }

} //FieldDefinitionImpl
