/**
 * generated by Xtext 2.9.2
 */
package ch.raiffeisen.ipricer.definition.definitionDSL.impl;

import ch.raiffeisen.ipricer.definition.definitionDSL.DefinitionDSLPackage;
import ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskDefinition;
import ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskSection;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Type Mask Section</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.TypeMaskSectionImpl#getTypeMaskDefinitions <em>Type Mask Definitions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TypeMaskSectionImpl extends MinimalEObjectImpl.Container implements TypeMaskSection
{
  /**
   * The cached value of the '{@link #getTypeMaskDefinitions() <em>Type Mask Definitions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeMaskDefinitions()
   * @generated
   * @ordered
   */
  protected EList<TypeMaskDefinition> typeMaskDefinitions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TypeMaskSectionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DefinitionDSLPackage.Literals.TYPE_MASK_SECTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<TypeMaskDefinition> getTypeMaskDefinitions()
  {
    if (typeMaskDefinitions == null)
    {
      typeMaskDefinitions = new EObjectContainmentEList<TypeMaskDefinition>(TypeMaskDefinition.class, this, DefinitionDSLPackage.TYPE_MASK_SECTION__TYPE_MASK_DEFINITIONS);
    }
    return typeMaskDefinitions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DefinitionDSLPackage.TYPE_MASK_SECTION__TYPE_MASK_DEFINITIONS:
        return ((InternalEList<?>)getTypeMaskDefinitions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DefinitionDSLPackage.TYPE_MASK_SECTION__TYPE_MASK_DEFINITIONS:
        return getTypeMaskDefinitions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DefinitionDSLPackage.TYPE_MASK_SECTION__TYPE_MASK_DEFINITIONS:
        getTypeMaskDefinitions().clear();
        getTypeMaskDefinitions().addAll((Collection<? extends TypeMaskDefinition>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DefinitionDSLPackage.TYPE_MASK_SECTION__TYPE_MASK_DEFINITIONS:
        getTypeMaskDefinitions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DefinitionDSLPackage.TYPE_MASK_SECTION__TYPE_MASK_DEFINITIONS:
        return typeMaskDefinitions != null && !typeMaskDefinitions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //TypeMaskSectionImpl
