/**
 * generated by Xtext 2.9.2
 */
package ch.raiffeisen.ipricer.definition.definitionDSL.impl;

import ch.raiffeisen.ipricer.definition.definitionDSL.DefinitionDSLPackage;
import ch.raiffeisen.ipricer.definition.definitionDSL.TypeMaskDefinition;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Type Mask Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.TypeMaskDefinitionImpl#getId <em>Id</em>}</li>
 *   <li>{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.TypeMaskDefinitionImpl#getRow <em>Row</em>}</li>
 *   <li>{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.TypeMaskDefinitionImpl#getCol <em>Col</em>}</li>
 *   <li>{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.TypeMaskDefinitionImpl#getWidth <em>Width</em>}</li>
 *   <li>{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.TypeMaskDefinitionImpl#getSeparator <em>Separator</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TypeMaskDefinitionImpl extends MinimalEObjectImpl.Container implements TypeMaskDefinition
{
  /**
   * The default value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected static final String ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected String id = ID_EDEFAULT;

  /**
   * The default value of the '{@link #getRow() <em>Row</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRow()
   * @generated
   * @ordered
   */
  protected static final int ROW_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getRow() <em>Row</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRow()
   * @generated
   * @ordered
   */
  protected int row = ROW_EDEFAULT;

  /**
   * The default value of the '{@link #getCol() <em>Col</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCol()
   * @generated
   * @ordered
   */
  protected static final int COL_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getCol() <em>Col</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCol()
   * @generated
   * @ordered
   */
  protected int col = COL_EDEFAULT;

  /**
   * The default value of the '{@link #getWidth() <em>Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWidth()
   * @generated
   * @ordered
   */
  protected static final int WIDTH_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getWidth() <em>Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWidth()
   * @generated
   * @ordered
   */
  protected int width = WIDTH_EDEFAULT;

  /**
   * The default value of the '{@link #getSeparator() <em>Separator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeparator()
   * @generated
   * @ordered
   */
  protected static final String SEPARATOR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSeparator() <em>Separator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeparator()
   * @generated
   * @ordered
   */
  protected String separator = SEPARATOR_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TypeMaskDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DefinitionDSLPackage.Literals.TYPE_MASK_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getId()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setId(String newId)
  {
    String oldId = id;
    id = newId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DefinitionDSLPackage.TYPE_MASK_DEFINITION__ID, oldId, id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getRow()
  {
    return row;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRow(int newRow)
  {
    int oldRow = row;
    row = newRow;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DefinitionDSLPackage.TYPE_MASK_DEFINITION__ROW, oldRow, row));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getCol()
  {
    return col;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCol(int newCol)
  {
    int oldCol = col;
    col = newCol;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DefinitionDSLPackage.TYPE_MASK_DEFINITION__COL, oldCol, col));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getWidth()
  {
    return width;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setWidth(int newWidth)
  {
    int oldWidth = width;
    width = newWidth;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DefinitionDSLPackage.TYPE_MASK_DEFINITION__WIDTH, oldWidth, width));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSeparator()
  {
    return separator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSeparator(String newSeparator)
  {
    String oldSeparator = separator;
    separator = newSeparator;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DefinitionDSLPackage.TYPE_MASK_DEFINITION__SEPARATOR, oldSeparator, separator));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__ID:
        return getId();
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__ROW:
        return getRow();
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__COL:
        return getCol();
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__WIDTH:
        return getWidth();
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__SEPARATOR:
        return getSeparator();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__ID:
        setId((String)newValue);
        return;
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__ROW:
        setRow((Integer)newValue);
        return;
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__COL:
        setCol((Integer)newValue);
        return;
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__WIDTH:
        setWidth((Integer)newValue);
        return;
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__SEPARATOR:
        setSeparator((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__ID:
        setId(ID_EDEFAULT);
        return;
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__ROW:
        setRow(ROW_EDEFAULT);
        return;
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__COL:
        setCol(COL_EDEFAULT);
        return;
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__WIDTH:
        setWidth(WIDTH_EDEFAULT);
        return;
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__SEPARATOR:
        setSeparator(SEPARATOR_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__ID:
        return ID_EDEFAULT == null ? id != null : !ID_EDEFAULT.equals(id);
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__ROW:
        return row != ROW_EDEFAULT;
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__COL:
        return col != COL_EDEFAULT;
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__WIDTH:
        return width != WIDTH_EDEFAULT;
      case DefinitionDSLPackage.TYPE_MASK_DEFINITION__SEPARATOR:
        return SEPARATOR_EDEFAULT == null ? separator != null : !SEPARATOR_EDEFAULT.equals(separator);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (id: ");
    result.append(id);
    result.append(", row: ");
    result.append(row);
    result.append(", col: ");
    result.append(col);
    result.append(", width: ");
    result.append(width);
    result.append(", separator: ");
    result.append(separator);
    result.append(')');
    return result.toString();
  }

} //TypeMaskDefinitionImpl
