/**
 * generated by Xtext 2.9.2
 */
package ch.raiffeisen.ipricer.definition.definitionDSL.impl;

import ch.raiffeisen.ipricer.definition.definitionDSL.DefinitionDSLPackage;
import ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListDefintion;
import ch.raiffeisen.ipricer.definition.definitionDSL.UnderlyingListSection;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Underlying List Section</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ch.raiffeisen.ipricer.definition.definitionDSL.impl.UnderlyingListSectionImpl#getUnderlyingListDefinitions <em>Underlying List Definitions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UnderlyingListSectionImpl extends MinimalEObjectImpl.Container implements UnderlyingListSection
{
  /**
   * The cached value of the '{@link #getUnderlyingListDefinitions() <em>Underlying List Definitions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnderlyingListDefinitions()
   * @generated
   * @ordered
   */
  protected EList<UnderlyingListDefintion> underlyingListDefinitions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UnderlyingListSectionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DefinitionDSLPackage.Literals.UNDERLYING_LIST_SECTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<UnderlyingListDefintion> getUnderlyingListDefinitions()
  {
    if (underlyingListDefinitions == null)
    {
      underlyingListDefinitions = new EObjectContainmentEList<UnderlyingListDefintion>(UnderlyingListDefintion.class, this, DefinitionDSLPackage.UNDERLYING_LIST_SECTION__UNDERLYING_LIST_DEFINITIONS);
    }
    return underlyingListDefinitions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DefinitionDSLPackage.UNDERLYING_LIST_SECTION__UNDERLYING_LIST_DEFINITIONS:
        return ((InternalEList<?>)getUnderlyingListDefinitions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DefinitionDSLPackage.UNDERLYING_LIST_SECTION__UNDERLYING_LIST_DEFINITIONS:
        return getUnderlyingListDefinitions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DefinitionDSLPackage.UNDERLYING_LIST_SECTION__UNDERLYING_LIST_DEFINITIONS:
        getUnderlyingListDefinitions().clear();
        getUnderlyingListDefinitions().addAll((Collection<? extends UnderlyingListDefintion>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DefinitionDSLPackage.UNDERLYING_LIST_SECTION__UNDERLYING_LIST_DEFINITIONS:
        getUnderlyingListDefinitions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DefinitionDSLPackage.UNDERLYING_LIST_SECTION__UNDERLYING_LIST_DEFINITIONS:
        return underlyingListDefinitions != null && !underlyingListDefinitions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //UnderlyingListSectionImpl
