/**
 * generated by Xtext 2.9.2
 */
package ch.raiffeisen.ipricer.definition;

import ch.raiffeisen.ipricer.definition.AbstractDefinitionDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DefinitionDSLRuntimeModule extends AbstractDefinitionDSLRuntimeModule {
}
