/**
 * generated by Xtext 2.9.2
 */
package ch.raiffeisen.ipricer.definition.validation;

import ch.raiffeisen.ipricer.definition.validation.AbstractDefinitionDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DefinitionDSLValidator extends AbstractDefinitionDSLValidator {
}
