/*
 * generated by Xtext 2.9.2
 */
package ch.raiffeisen.ipricer.definition.idea;

import ch.raiffeisen.ipricer.definition.idea.lang.DefinitionDSLLanguage;
import com.intellij.openapi.extensions.ExtensionFactory;

public class DefinitionDSLExtensionFactory implements ExtensionFactory {
	@Override
	public Object createInstance(String factoryArgument, String implementationClass) {
		Class<?> clazz;
		try {
			clazz = Class.forName(implementationClass);
		} catch (ClassNotFoundException e) {
			throw new IllegalArgumentException("Couldn't load "+implementationClass, e);
		}
		return DefinitionDSLLanguage.INSTANCE.<Object> getInstance(clazz);
	}
}
